### ISSUE TITLE
Distro-agnosticism

### ISSUE THREAD

**Issue by baimafeima** [ebruck/radiotray-ng#10]
The description of radiotray-ng here on GitHub says: "An Internet radio player for Ubuntu". Would you mind making it more distro-agnostic to allow for wider adoption? I believe this would also be in line with your goals of making it cross-platform?

**Comment by ebruck** [comment]
In what way does it needs more work to be distro agnostic?  Packaging?

**Comment by baimafeima** [comment]
Your current branding suggests that your main developing and testing base is Ubuntu. There is nothing wrong with that but it limits you mainly to an Ubuntu user base. While radiotray-ng _might_ work on other systems and desktop environments as well, many potential users from openSUSE, Fedora, and Solus probably don't have it on their radar.

**Comment by ebruck** [comment]
Actually I've already changed that in my v0.1.5 branch.

**Comment by ebruck** [comment]
I've updated the repo description.
