### ISSUE TITLE
Add the deb ubuntu 18.04 package for the latest release 0.2.4

### ISSUE THREAD

**Issue by KOT040188** [ebruck/radiotray-ng#101]
I have a small request. Please add the deb ubuntu 18.04 package for the latest release 0.2.4. Thank you!

**Comment by kalligator** [comment]
I've uploaded the one I compiled here http://www.mediafire.com/file/29y1ul0dc11yedc/radiotray-ng_0.2.4_ubuntu_18.04_amd64_2019.3.09.deb/file but to be safe you should build it yourself as well. Not hard at all if you follow the [instructions](https://github.com/ebruck/radiotray-ng#build-radiotray-ng--debian-package).

**Comment by KOT040188** [comment]
Thank you. I've already compiled follow the instructions while waiting for an answer. It was simple.

**Comment by KOT040188** [comment]
Now I'm waiting for implementation support MPRIS.

**Comment by MAlfare** [comment]
@kalligator
Thank you for the deb-package.
Maybe it wouldn't be hard to build, but a lot of packages where to install, which I never would use for anything else.

**Comment by ebruck** [comment]
Debian package added to v0.2.5 release
