### ISSUE TITLE
Make application relocateable

### ISSUE THREAD

**Issue by probonopd** [ebruck/radiotray-ng#102]
I am trying to make an [AppImage](https://appimage.org/) of radiotray-ng. I can build one, but when running it I am getting

```
me@host:~$ Downloads/Radiotray-NG-9827364-x86_64.AppImage 
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::copy: Function not implemented: "/usr/share/radiotray-ng/bookmarks.json", "/home/me/.config/radiotray-ng/bookmarks.json"
Aborted
```

AppImages are not installed within `/usr`.

Please do not assume that resources are at a fixed absolute path location within `/usr/share/` but rather use a path relative to the main executable (determined at runtime rather than compile time), e.g., using http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath.

**Comment by ebruck** [comment]
I only support Debian packaging. I am open to a pull request that supports both.

**Comment by ebruck** [comment]
How is XDG_DATA_DIRS set when using an appimage?

**Comment by probonopd** [comment]
`XDG_DATA_DIRS` is not touched, unless you use the C version of `AppRun` from AppImageKit which does the following:

https://github.com/AppImage/AppImageKit/blob/6baa36d0b1e0481aa36a36bb54140b81959b3874/src/AppRun.c#L180-L181
