### ISSUE TITLE
polling for icon file

### ISSUE THREAD

**Issue by mxmilkb** [ebruck/radiotray-ng#103]
radiotray-ng appears to constantly be polling for an icon file

[strace](https://gist.github.com/mxmilkb/c93e3d801a5d2dbf72f23495d83598d6)

(n.b. the above strace is from swaybar, which is having CPU spike issues, some of which are appear linked to this issue).

> access("/usr/local/share/icons/hicolor/scalable/stock/text/radiotray-ng-off.png", R_OK) = -1 ENOENT (No such file or directory)

There are two of these available from the radiotray-ng-git package, but in they don't show up in the strace.

/usr/share/icons/ubuntu-mono-dark/apps/24/radiotray-ng-off.svg
/usr/share/icons/ubuntu-mono-light/apps/24/radiotray-ng-off.svg

**Comment by ebruck** [comment]
Perhaps it's the notify library being used which is looking for an icon that matches what was requested for a message? Unless the user specifies a complete path, the library should be searching based on the name such as radiotray-ng-on, radiotray-ng-off etc.

Quick run of strace on Ubuntu 18.04/Gnome shows no polling.

**Comment by mxmilkb** [comment]
Notification system I'm using https://github.com/emersion/mako though I'm not sure it was running when I did the log. Doesn't change trying now though.

Or if it's libnotify? Hmm.

**Comment by ianyfan** [comment]
I explained a bit badly in my previous comment, but this is a swaybar issue, so this issue can be closed.
