### ISSUE TITLE
Logging and co-existence with multiple computers sharing configuration setup

### ISSUE THREAD

**Issue by al-right** [ebruck/radiotray-ng#106]
First a big thanks for radiotray-ng!
I use it all day everyday! :)

**Summary**
I am missing a way to prevent logging in the .config/radiotray-ng/logs/ directory.
This is the primary concern. It is although not a high priority enhancement request, but it would simply be nice to have.
Reasons:
* I do not need the logs (at least for now.)
* Privacy concern. What I listen to only concerns me.
* Notifications from 3rd party synchronization program:
I would like to avoid notifications from a (free/open source) 3rd party "dropbox" alternative called Seafile.

Secondary this post mentions ways to let the Seafile synchronization application share radiotray-ng settings and prevent synchronization of logs, pid files etc.

I am using radiotray-ng v0.2.5 on Ubuntu 18.04 64 bit and Seafile client v.6.2.9.

**Background**
I have a setup where I use Seafile to share files (and configurations) between computers: A desktop and a laptop.
I share the directory .config/radiotray-ng/ in Seafile using a symbolic link from my home directory pointing towards the just mentioned "radiotray-ng" directory.
Since I normally do not use radiotray-ng at the same time on both computers I have not experienced issues with the pid files, but the Seafile messages about the log file notifications (messages about created and updated files) and their content (privacy) and the created pid files (sharing) have although annoyed me a bit.

**What I have tried**
1. Searched for options to prevent logging in radiotray-ng with these options:
   "notification-verbose" : false,
   "notifications" : false,
   "debug-logging" : false
, but they do not prevent log files from showing up in the logs directory nor do they prevent those log files from being updated.

2. I have tried to make the logs directory read only.
It works only while radiotray-ng is already running.
On subsequent startups of radiotray-ng the application never succeeds to show the radiotray-ng tray icon.
(A pid file is although made.)
Switching back to having a writable logs directory makes radiotray-ng start again.

3. The only workaround was to let Seafile not sync some directories and files.
If interested about how to tell Seafile not to synchronize certain directories and files please see: https://help.seafile.com/en/syncing_client/excluding_files.html
But still it would be nice to have an option to prevent radiotray-ng from creating and updating the log files.

Please find below the full radiotray-ng.json config file and seafile-ignore.txt file.
Besides letting Seafile ignore the content within the logs directory and the pid file I have also
considered ignoring the radiotray-ng.json file so that each computer is able to have their own
setup (e.g. for the sake of the volume level), but then again it is nice to have the other options
shared.
(An alternative synchronization setup could be to only synchronize the ".config/radiotray-ng/bookmarks.json" file by making a sym link to that file in a Seafile share. It all depends on the desired use case.)

**radiotray-ng.json**
```
{
   "bookmarks" : "/home/user/.config/radiotray-ng/bookmarks.json",
   "last-station" : "P7 MIX",
   "last-station-group" : "DR",
   "last-station-notifications" : true,
   "notification-verbose" : false,
   "notifications" : false,
   "split-title" : true,
   "tag-info-verbose" : true,
   "volume-level" : 78
}
```

**seafile-ignore.txt placed in root of seafile share**
```
# Prevent radiotray-ng logs from being synchronized
.config/radiotray-ng/logs/

# Prevent radiotray-ng pid files from being synchronized so that different computers do not see another computer's radiotray-ng pid file of a running radiotray-ng instance.
.config/radiotray-ng/radiotray-ng.pid
```

**Comment by ebruck** [comment]
Glad you found a workaround. 

This brings up an issue of where I'm placing the pid files. They should go into the location defined by XDG_RUNTIME_DIR. I'll fix that next release and I'll also see what I can do about adding a logging enable/disable option.

**Comment by ebruck** [comment]
@al-right hopefully these changes will work for you.

**Comment by ebruck** [comment]
@al-right can you build v0.2.6-dev branch and test with your setup?

**Comment by al-right** [comment]
@ebruck It seems to work (I have build it from the 0.2.6 branch.) Thanks a lot :)
* Disabling of logging works.
* Re. the pid-file: I cannot find it anymore in the .config/radiotray-ng directory which is fine,
_but I cannot seem to find it anywhere on the system at all - is this good or bad; where should it be located?_

**Comment by ebruck** [comment]
try: cd $XDG_RUNTIME_DIR

**Comment by al-right** [comment]
You are right - it is there. Everything works :)
Thanks a lot!
