### ISSUE TITLE
[Q] Use xdgCacheHome for logs?

### ISSUE THREAD

**Issue by dafanasiev** [ebruck/radiotray-ng#107]
Now in `v0.2.6-dev` you use `xdgRuntimeDirectory` for logs.

Can you use something like

```
    inline std::string get_log_dir(const std::string& app_name)
    {
	    // XDG Base Directory Specification says nothing about logs,
	    // so, we use user cache directory
        std::string rv = xdgCacheHome(nullptr);

        rv += std::string("/") + app_name + std::string("/");
        return rv;
    }
```
as log directory (and, of course, create directory if not exists) ?

//After that users can backup/sync app data directory without excluding *.log files (even when `disable-logging` set to `false` in config)

**Comment by ebruck** [comment]
I had lumped the config and logs together so they were easier to find. I'll look into this next.
thanks!

**Comment by dafanasiev** [comment]
@ebruck also need create directory (that `get_cache_dir` returns) if not exists.

**Comment by ebruck** [comment]
boost logging does that for you
