### ISSUE TITLE
XML parsing

### ISSUE THREAD

**Issue by sexynavigator** [ebruck/radiotray-ng#108]
m80 radios have non parsed or wrongly parsed info, as a result the usually small window of radiotray becomes quite large and difficult to manage. You can verify this with any of the following streams. If you cannot make them be parsed as supposed could you please include an option not to parse them. It happens both on m3u and xspf.

http://195.23.102.207/m80Pop.m3u
http://195.23.102.207/m80Dance.xspf
http://195.23.102.207/M80BALLADS.xspf

**Comment by ebruck** [comment]
It appears that this encoding is meant for a station's website player?
I'm going to filter out any tags that look encoded.

**Comment by ebruck** [comment]
If you can, please build v0.2.6-dev branch and test my change.

thx!
