### ISSUE TITLE
Unclear sleep timer functionality

### ISSUE THREAD

**Issue by baimafeima** [ebruck/radiotray-ng#11]
Under _Preferences_ there is an option to activate a _Sleep Timer_. It seems that it is not fully implemented yet. At least I couldn't get it to work.

**Comment by ebruck** [comment]
Today you only have the option to enable/disable it from the menu.  To change the timer value (default is 30 min) then you must exit radiotray-ng and edit your configuration file. Have a look at the README.md file for that and other entries that are available.

**Comment by baimafeima** [comment]
Thanks for clarifying this. It would be great to be able to edit the timer duration via a dedicated settings tab. I assume you probably have it on the roadmap.

**Comment by ebruck** [comment]
I'll add a dialog box similar to what the original RadioTray had.
