### ISSUE TITLE
particular radio station not able to connect

### ISSUE THREAD

**Issue by noreasternhumidity** [ebruck/radiotray-ng#110]
Hi, nice program.  I use this with Linux Mint on a regular basis.

Here is a potential situation which so far only occurs for me with this station.
KXL AM

program reports: 
Error server sent bad data

These links I harvested from Firefox using the Network analyzer (my go-to method for using this program):

https://live.wostreaming.net/direct/alphacorporate-kxlfmaac-ibc4
https://live.wostreaming.net/direct/alphacorporate-kxlfmaac-ibc4&source=website
https://prod-34-209-247-255.wostreaming.net/alphacorporate-kxlfmaac-ibc4
https://prod-34-209-247-255.wostreaming.net/alphacorporate-kxlfmaac-ibc4?source=website

Thanks

**Comment by ebruck** [comment]
gstreamer doesn't like what the server is sending. My guess it's meant for a website player.

$ gst-play-1.0  https://live.wostreaming.net/direct/alphacorporate-kxlfmaac-ibc4
Press 'k' to see a list of keyboard shortcuts.
Now playing https://live.wostreaming.net/direct/alphacorporate-kxlfmaac-ibc4
ERROR Server sent bad data. for https://live.wostreaming.net/direct/alphacorporate-kxlfmaac-ibc4
ERROR debug information: gstsouphttpsrc.c(1392): gst_soup_http_src_parse_status (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
Message Corrupt (8), URL: https://live.wostreaming.net/direct/alphacorporate-kxlfmaac-ibc4, Redirect to: https://prod-18-236-222-179.wostreaming.net/alphacorporate-kxlfmaac-ibc4?session-id=6722d01f9a3fb136efc942fd83c3de96
Reached end of play list.

**Comment by noreasternhumidity** [comment]
Okay, I kind of figured.  So either they are intentionally making it difficult for non-browser clients to connect, or else maybe just using a different approach.  I'm guessing they just aren't following standard protocol.

**Comment by ebruck** [comment]
Switching to http and in Wireshark I see that they are using aacp. 

GET /alphacorporate-kxlfmaac-ibc4?session-id=6722d01f9a3fb136efc942fd83c3de96 HTTP/1.1
Host: prod-18-236-222-179.wostreaming.net
User-Agent: GStreamer souphttpsrc 1.15.90 libsoup/2.66.1
icy-metadata: 1
Connection: Keep-Alive

HTTP/1.1 200 OK
Connection: close
Date: Fri, 03 May 2019 19:15:22 GMT
Content-Type: audio/aacp
Cache-Control: no-cache
Pragma: no-cache
Transfer-Encoding: identity
Content-Encoding: identity
Expires: Thu, 01 Jan 1970 00:00:01 GMT
icy-br: 64
icy-metaint: 2048
icy-name: KXL-FM

VLC can play it.

**Comment by noreasternhumidity** [comment]
Thanks for confirming.  Maybe a new thing?  If relevant then gstreamer will adopt it sooner or later.

This sort of reminds me of the newer Google WebP picture format, which I can so far only open using the latest and greatest version of Gimp.

**Comment by ebruck** [comment]
There's may be some patent issues.
