### ISSUE TITLE
App-Level Volume Adjustment Using Mouse-Scroll-Wheel

### ISSUE THREAD

**Issue by Lonniebiz** [ebruck/radiotray-ng#112]
In Ubuntu 16.04, you could perform app-level volume adjustment in RadioTray by scrolling your mouse-wheel on top of RadioTray's top-panel icon.

In Ubuntu 19.04, which uses the Gnome desktop, this nice feature is missing. Furthermore, since I upgraded Ubuntu from 16.04, the App-Level volume is set to the app-level volume I last adjusted back in Ubuntu 16.04 and I cannot even find an alternative way to adjust it.

As you can see, in this screenshot, the app-level volume is stuck at 5%:
![screenshot](https://i.imgur.com/5PH5Ncd.png)

I suspect I can just delete the radiotray folder to get app-level volume back to 100%:
`/home/username/.local/share/radiotray`

However, having convenient app-level volume control (via mouse-scroll-wheel-adjustment) was a nice feature, because it allowed me to have low background music while having louder sounds for more urgent things elsewhere.

```
ProblemType: Bug
DistroRelease: Ubuntu 19.04
Package: radiotray 0.7.3-6ubuntu2
ProcVersionSignature: Ubuntu 5.0.0-13.14-generic 5.0.6
Uname: Linux 5.0.0-13-generic x86_64
NonfreeKernelModules: nvidia_modeset nvidia
ApportVersion: 2.20.10-0ubuntu27
Architecture: amd64
CurrentDesktop: ubuntu:GNOME
Date: Tue May 7 09:49:14 2019
InstallationDate: Installed on 2019-01-07 (120 days ago)
InstallationMedia: Ubuntu 16.04.5 LTS "Xenial Xerus" - Release amd64 (20180731)
PackageArchitecture: all
ProcEnviron:
 TERM=xterm-256color
 PATH=(custom, no user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/bin/bash
SourcePackage: radiotray
UpgradeStatus: Upgraded to disco on 2019-04-21 (16 days ago)
```

Downstream bug report:
https://bugs.launchpad.net/radiotray/+bug/1828069

**Comment by ebruck** [comment]
I had already discovered this bug and reported it here:
https://bugs.launchpad.net/ubuntu/disco/+source/gnome-shell-extension-appindicator/+bug/1825447

**Comment by Lonniebiz** [comment]
That's true, but my report is more prettier and yours is ugly!

**Comment by ebruck** [comment]
But this is radiotray-ng's github repo and not the old unsupported and dead python version!  ;-)

**Comment by Lonniebiz** [comment]
I'm glad some kind soul is keeping the radiotray going. I hope they can fix this issue with volume adjustment; its a great feature.

**Comment by ebruck** [comment]
Grab the fixed version from:

https://launchpad.net/ubuntu/+archive/primary/+files/gnome-shell-extension-appindicator_29-1_all.deb

**Comment by Lonniebiz** [comment]
Do you maintain a repo for this, so that I can just auto-get updates you make?

**Comment by Lonniebiz** [comment]
Go to this page:
https://snapcraft.io/radiotray-ng

Now, click on the link that says "Contact Dmitry Afanasiev".

Instead of allowing you to contact Dmitry Afanasiev, it goes to:
https://github.com/ebruck/radiotray-ng
