### ISSUE TITLE
Avoid relying on lsb_release command

### ISSUE THREAD

**Issue by gasinvein** [ebruck/radiotray-ng#116]
The `lsb_release` command is not necessarily present in non-Debian-based distros, and even if it exists, it may behave in unexpected way, since there are multiple implementations.
Instead, consider reading the `/etc/os-release` file, or allow the user to define needed variables at build time.

**Comment by ebruck** [comment]
What sort of issues have you seen with `lsb_release`? Looking at the source code, it is reading `/etc/os-release`. What distro have you run across that did not have it available?

**Comment by ebruck** [comment]
I have found examples of cmake code to parse the file, but unless this is a real issue that is stopping packaging from working then I'll probably not change it anytime soon.

**Comment by gasinvein** [comment]
`lsb_release` is available out of box only in Debian-based distros. In Fedora, Arch, Gentoo and probably others else it has to installed manually.
For some environments, like Flatpak SDKs, `lsb_release` is unavailable at all, meaning that your app e.g. can't be packaged as flatpak without patches or hacks.

**Comment by ebruck** [comment]
I think what I can do in the mean time before cmake has this builtin (https://gitlab.kitware.com/cmake/cmake/issues/18979), is to not fail if `lsb_release` is missing, but rather use default values for `DISTRO`, `CODENAME` & `RELEASE`. These can be overridden on the cmake command line using `-DDISTRO=ubuntu` etc.

**Comment by gasinvein** [comment]
Seems like building without `lsb_release` is still broken:
```
CMake Error at package/CMakeLists.txt:7 (string):
  string no output variable specified


Building version: 0.2.6-dev for   -- DEB packaging...
CMake Error at package/CMakeLists.txt:53 (if):
  if given arguments:

    "STREQUAL" "16.04" "OR" "STREQUAL" "stretch"

  Unknown arguments specified

```

**Comment by ebruck** [comment]
I'll have a fix soon.
