### ISSUE TITLE
Python2 dependency

### ISSUE THREAD

**Issue by Vascom** [ebruck/radiotray-ng#118]
In src/radiotray-ng/extras/scripts/rt2rtng I see shebang **python2.7**.
It really require python2 or can be launched with python3?

**Comment by ebruck** [comment]
Thanks for bringing it his up. It's about time to revisit this script with all the EOL of 2.7 looming.
I ran it through 2to3 and it seems to work fine. I'll add this change to the next release.

**Comment by Vascom** [comment]
Thanks.
