### ISSUE TITLE
Some warnings at build

### ISSUE THREAD

**Issue by Vascom** [ebruck/radiotray-ng#119]
I found some warnings during build for Fedora. Please correct it so radiotray-ng will have clear builds.
```
src/radiotray-ng/config/config.cpp:34:16: warning: 'Json::Reader::Reader()' is deprecated: Use CharReader and CharReaderBuilder instead [-Wdeprecated-declarations]
BUILDSTDERR:    34 |   Json::Reader reader;
src/radiotray-ng/config/config.cpp:60:31: warning: 'StyledWriter' is deprecated: Use StreamWriterBuilder instead [-Wdeprecated-declarations]
BUILDSTDERR:    60 |   ofile << Json::StyledWriter().write(this->config);
```
And same in other place. Please see https://kojipkgs.fedoraproject.org//packages/radiotray-ng/0.2.6/2.fc31/data/logs/x86_64/build.log

**Comment by ebruck** [comment]
There is nothing to correct if you use compiler flags I specify in the cmake file.
 `-Wno-deprecated-declarations` was added for https://github.com/ebruck/radiotray-ng/issues/43

There are several distros still using older versions of jsoncpp, so I can't move to the newer calls just yet.

**Comment by Vascom** [comment]
OK. It is just warning.

**Comment by ebruck** [comment]
It's time to move to the new calls. I'm reopening this and will add to the next release.
