### ISSUE TITLE
Support HLS

### ISSUE THREAD

**Issue by rpcmaringa** [ebruck/radiotray-ng#124]
Please support HLS, for example - https://medias.sgr.globo.com/hls/aCBNSP/aCBNSP.m3u8.

Thank you.

**Comment by ebruck** [comment]
HLS/m3u8 support was added a while ago.
This particular url is not working for some reason:
```
$ gst-play-1.0 https://medias.sgr.globo.com/hls/aCBNSP/aCBNSP.m3u8
Press 'k' to see a list of keyboard shortcuts.
Now playing https://medias.sgr.globo.com/hls/aCBNSP/aCBNSP.m3u8
Prerolling...
```
It just sits there. I don't know what more I can do if gstreamer can't play it. Sorry.

**Comment by ebruck** [comment]
To verify try this which works in radiotray-ng as well.

`$ gst-play-1.0 http://c11.prod.playlists.ihrhls.com/709/playlist.m3u8`
