### ISSUE TITLE
Option for audio fade in/out?

### ISSUE THREAD

**Issue by mxmilkb** [ebruck/radiotray-ng#125]
Would make for a nicer experience. Maybe the user could set the time of the fade also?

**Comment by al-right** [comment]
You mean when starting playback and also when switching from radio channel A to B?
I like the idea :)

**Comment by ebruck** [comment]
I'm sorry the features proposed here are far beyond what radiotray-ng was intended to be and are things I don't find very useful. Most will require a major rewrite of the code base to support.
