### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by saltymedic** [ebruck/radiotray-ng#127]
Radio tray was working great. Now when I try to load it I get:

`radiotray-ng: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory`

**Comment by Swipe650** [comment]
You must have had some libraries updated. Assuming you compiled this from source, recompiling radiotray-ng should fix it.

**Comment by saltymedic** [comment]
That fixed it. Thank you for the easy solution! :)
