### ISSUE TITLE
Light Desktop Environment Tray Icons?

### ISSUE THREAD

**Issue by diximinga** [ebruck/radiotray-ng#13]
Hi,

first of all: Thank you very much for your project

Is there or will there be a possibility to change Tray-Icons to a light color desktop environment in the config file?

I'm using Arch

**Comment by ebruck** [comment]
You can change them by installing new versions under /usr/share/icons/<theme>/apps/.... 
Arch I believe it is using the "hicolor" versions.

The icon names are: radiotray-ng-notification, radiotray-ng-on & radiotray-ng-off

**Comment by diximinga** [comment]
Yes:
/usr/share/icons/hicolor/256x256/apps/radiotray-ng-off.png
/usr/share/icons/hicolor/256x256/apps/radiotray-ng-on.png

I did it for "radiotray-ng-off.png" and changed white to black, and it works; but actually I don't like to change system files.

So, "make it configurable" is only a feature request, a "nice to have"

THX

**Comment by ebruck** [comment]
You can place an icon theme in ~/.icons and modify it there.
https://developer.gnome.org/icon-theme-spec/

**Comment by diximinga** [comment]
unfortunately local folder does not work, maybe because I use KDE and not Gnome

**Comment by ebruck** [comment]
I'll see what I can do for the next release to make this configurable.

**Comment by ebruck** [comment]
@diximinga v0.1.6 released with this new feature
