### ISSUE TITLE
Allow HTTP-Basic authentication or whitelist website certificate

### ISSUE THREAD

**Issue by AlphaJack** [ebruck/radiotray-ng#130]
Is it possible to add support for HTTP-Basic protected streams?  
Alternatively, can we have an option to whitelist the website certificate if the domain name mismatches, like VLC does?  
My radio streams are reachable from  
- https://example.com/radio/ reachable from everywhere, requires HTTP-Basic 
- https://10.0.0.1/radio/ reachable from VPN, no further authentication needed  

In the latter case I would need to trust the certificate, because the domain name is "example.com" and not "10.0.0.1"

Logs:
```
[...]
[info ] (radiotray_ng.cpp:499) - downloading: TEST, Test1, https://example.com/radio/mp3
[debug] (notification.cpp:63) - notify: Connecting, Radiotray-NG, radiotray-ng-notification
[debug] (playlist_downloader.cpp:140) - http-timeout=15
[error] (playlist_downloader.cpp:158) - curl_easy_perform() failed: Unsupported protocol 0
[error] (playlist_downloader.cpp:75) - Could not download playlist!
[error] (playlist_downloader.cpp:85) - http_resp_code = 0
[error] (radiotray_ng.cpp:533) - failed to download playlist: https://example.com/radio/mp3
[debug] (notification.cpp:63) - notify: Error, Failed to download playlist, radiotray-ng-notification
[info ] (main.cpp:296) - radiotray-ng shutting down
[...]
```

```
[...]
[info ] (radiotray_ng.cpp:499) - downloading: TEST, TEST2, https://10.0.0.1/radio/mp3
[debug] (notification.cpp:63) - notify: Connecting, Radiotray-NG, radiotray-ng-notification
[debug] (playlist_downloader.cpp:140) - http-timeout=15
[error] (playlist_downloader.cpp:158) - curl_easy_perform() failed: Unsupported protocol 0
[error] (playlist_downloader.cpp:75) - Could not download playlist!
[error] (playlist_downloader.cpp:85) - http_resp_code = 0
[error] (radiotray_ng.cpp:533) - failed to download playlist: https://10.0.0.1/radio/mp3
[debug] (notification.cpp:63) - notify: Error, Failed to download playlist, radiotray-ng-notification
[info ] (main.cpp:296) - radiotray-ng shutting down
[...]
```

**Comment by ebruck** [comment]
@AlphaJack have you tried changing the station URL like so?

https://admin:123456@example.com/radio/

I've decided not to ignore bad or self signed certs.
See https://github.com/ebruck/radiotray-ng/issues/95#issuecomment-450586709

**Comment by AlphaJack** [comment]
I've tried, but it doesn't work:
```
[...]
[info ] (radiotray_ng.cpp:499) - downloading: TEST, Test4, https://username:password@example.com/radio/mp3
[debug] (notification.cpp:63) - notify: Connecting, Radiotray-NG, radiotray-ng-notification
[debug] (playlist_downloader.cpp:140) - http-timeout=15
[error] (playlist_downloader.cpp:158) - curl_easy_perform() failed: Unsupported protocol 0
[error] (playlist_downloader.cpp:75) - Could not download playlist!
[error] (playlist_downloader.cpp:85) - http_resp_code = 0
[error] (radiotray_ng.cpp:533) - failed to download playlist: https://username:password@example.com/radio/mp3
[debug] (notification.cpp:63) - notify: Error, Failed to download playlist, radiotray-ng-notification
[info ] (main.cpp:296) - radiotray-ng shutting down
[...]
```

Entering that URL in a browser allows me to login and listen directly to the stream

**Comment by ebruck** [comment]
@AlphaJack What version of radiotray-ng are you using? 
Do you have a real station behind basic auth that I can test against?

My output is a bit different:

 [info ] (radiotray_ng.cpp:499) - downloading: root, Test, https://username:password@example.com/radio/mp3
 [debug] (notification.cpp:63) - notify: Connecting, Radiotray-NG, /usr/share/icons/hicolor/256x256/apps/radiotray-ng-notification.png
 [debug] (playlist_downloader.cpp:140) - http-timeout=15
 [error] (playlist_downloader.cpp:158) - curl_easy_perform() failed: HTTP response code said error 404
 [error] (playlist_downloader.cpp:75) - Could not download playlist!
 [error] (playlist_downloader.cpp:85) - http_resp_code = 404
 [error] (radiotray_ng.cpp:533) - failed to download playlist: https://username:password@example.com/radio/mp3
 [debug] (notification.cpp:63) - notify: Error, Failed to download playlist, /usr/share/icons/hicolor/256x256/apps/radiotray-ng-notification.png

**Comment by AlphaJack** [comment]
v0.2.7
Can I DM you somehow? I can provide you a real username to debug further

**Comment by ebruck** [comment]
@AlphaJack you can reach me at the email listed in the authors file.

**Comment by AlphaJack** [comment]
The problem was the outdated `libcurl` in my repo (v7.58). Compiling the latest version (v7.69) from source solved the issue, now I can login with https://admin:123456@example.com/radio/  
Thanks again @ebruck for the support
