### ISSUE TITLE
Support MATE DE's media keys interface

### ISSUE THREAD

**Issue by paravoid** [ebruck/radiotray-ng#131]
The MATE desktop environment is a maintained and modernized (GTK3 etc.) fork of GNOME 2. It's fairly popular, at least as far Linux desktop environments go :)

Its media keys interface is the same as GNOME's, but in a different D-Bus path. radiotray supported this with the MateMediaKeysPlugin, that differed from the GnomeMediaKeysPlugin like so:
```diff
             self.bus = dbus.SessionBus()
-            self.bus_object = self.bus.get_object('org.gnome.SettingsDaemon', '/org/gnome/SettingsDaemon/MediaKeys')
-            self.bus_object.GrabMediaPlayerKeys("RadioTray", 0, dbus_interface='org.gnome.SettingsDaemon.MediaKeys')
+            self.bus_object = self.bus.get_object('org.mate.SettingsDaemon', '/org/mate/SettingsDaemon/MediaKeys')
+            self.bus_object.GrabMediaPlayerKeys("RadioTray", 0, dbus_interface='org.mate.SettingsDaemon.MediaKeys')
             self.bus_object.connect_to_signal('MediaPlayerKeyPressed', self.handle_mediakey)
```

I see radiotray-ng has native support for GNOME's media keys. It'd be neat if MATE's was also supported :) Thanks a lot for your work!

**Comment by ebruck** [comment]
@paravoid could you please test my v0.2.8-dev branch?
