### ISSUE TITLE
iheart currently playing stopped working correctly

### ISSUE THREAD

**Issue by bonelifer** [ebruck/radiotray-ng#132]
OLD issue: https://github.com/ebruck/radiotray-ng/issues/37

Has iheart changed something, it now displays "text="?

**Comment by ebruck** [comment]
@bonelifer just tried the two stations listed in the old ticket and they display fine. Can you provide a screenshot and a URL of what is not working for you?

**Comment by bonelifer** [comment]
KSSN: https://stream.revma.ihrhls.com/zc105

![Screenshot_2020-04-15_15-41-47](https://user-images.githubusercontent.com/121736/79386383-ab28f500-7f2f-11ea-9728-faa134eba6f2.png)

**Comment by ebruck** [comment]
They are doubling up the "tag" text= for some reason:

"text=\"text=\"Spot Block End\" amgTrackId=\"9876543\"\" length=\"00:00:00\""

**Comment by ebruck** [comment]
Not all stations are doing this. 
http://c10icyelb.prod.playlists.ihrhls.com/101_icy

**Comment by ebruck** [comment]
@bonelifer do you know of any other stations that do this? If it's just this one then it's probably a bug that they may fix eventually.

**Comment by bonelifer** [comment]
No, but I'll try some others tomorrow. Screwed up my install and had to re-install ubuntu. Just got around to compiling and installing RadioTray.

**Comment by ebruck** [comment]
@bonelifer looks like the zc105 stream is being "fixed". 
I'm hesitant to change any code if it's just this stream, which is betting "better".

**Comment by bonelifer** [comment]
No problem. Things piled up and I forgot to check those out. The old ICY linked no longer works, but the new one does, so I assume they were probably in the process of changing out infrastructure when that happened. Thanks for taking on Radiotray and adding a much easier bookmark feature. Look forward to pulling out my radio.sh compile script and installing future fixes-etc. If you think this is "fixed" you can go ahead and close it.
