### ISSUE TITLE
Missing Default List of Streaming Radio Stations in Kubuntu 20.04

### ISSUE THREAD

**Issue by Lonniebiz** [ebruck/radiotray-ng#133]
In Kubuntu 20.04, I installed RadioTray like this:
`snap install --edge radiotray-ng`

After clicking the radiotray-ng icon, from the system tray, it didn't list any streaming radio stations.

Is this intentional? If so, you should consider listing some defaults streams like did `sudo apt install radiotray` in versions of RadioTray prior to Ubuntu/Kubuntu 20.04.

**Comment by al-right** [comment]
I think you should reach out to the publisher of the snap (Dmitry Afanasiev) :
https://snapcraft.io/install/radiotray-ng/ubuntu
, and report the problem to him. The version that Dmitry has in store is 0.2.7 (which works fine in Ubuntu 18.04 using Ed's deb-build - see below. I updated my laptop to Ubuntu MATE 20.04 yesterday and it continues to use version 0.2.**6** just fine.)

As soon as Ed releases the next release (0.2.8) you should be able to install a ppa / deb package as an alternative if Dmitry has not fixed the issue yet. Releases are found here:
https://github.com/ebruck/radiotray-ng/releases

**Comment by Lonniebiz** [comment]
@al-right : I never know how to give feedback on these snaps. Snapcraft.io really should make a better effort at making it clear where to submit issues for each snap in the repository. You shouldn't be able to even submit a snap without indicating where to submit issues for them, in my opinion.

I'll have to check out the PPA. It is a shame they couldn't get radiotray-ng into the default repository in 20.04. I've always installed it for years. I like it.

**Comment by al-right** [comment]
@Lonniebiz Yeah, snaps look polished in one way, but the information seems fragmented to other places. Must say I haven't tried to search for snap authors before, but...

I think I might have found the author - please take a look here:
https://github.com/dafanasiev/radiotray-ng-snap
Contact details to the left of this page: https://github.com/dafanasiev

Cheers :)

**Comment by ebruck** [comment]
@Lonniebiz please file a bug at: https://github.com/dafanasiev/radiotray-ng-snap

**Comment by Lonniebiz** [comment]
This issue has been moved here: https://github.com/dafanasiev/radiotray-ng-snap/issues/1
