### ISSUE TITLE
Any chance for a Debian distribution?

### ISSUE THREAD

**Issue by tassoman** [ebruck/radiotray-ng#134]
[Looks like old radiotray project is getting kicked out of Debian](http://forums.debian.net/viewtopic.php?f=6&t=146154)... 
Maybe it's time to switch to a New Generation of Radiotray?
I have no clue about how it could happen. But I hope.

**Comment by ebruck** [comment]
Please file a bug with your favourite distro. I provide the ability to create a debian package in the meantime. Sorry but this means you have to build from source.
