### ISSUE TITLE
dbus toggle_play ?

### ISSUE THREAD

**Issue by pjz** [ebruck/radiotray-ng#136]
I have a script that I used with the old radiotray that did, in part:
```
dbus-send --session --type="method_call" \                                    
            --dest='net.sourceforge.radiotray' \                              
            '/net/sourceforge/radiotray' \                                    
            'net.sourceforge.radiotray.togglePlay' 
```
which I then hooked up to the right media keys via my window manager (i3).
Any chance you could add a `toggle_play` (or `togglePlay` or something) DBUS target to radioplay-ng so that I can replicate this?  Thanks!

**Comment by ebruck** [comment]
Please see the readme for available dbus commands.

>    get_bookmarks
    get_config
    get_player_state
    play
    play_station 'group' 'station'
    play_url 'url'
    previous_station
    next_station
    reload_bookmarks
    set_volume 'level'        
    volume_down
    volume_up
    mute
    stop
    quit

**Comment by pjz** [comment]
I'm aware.  I meant it to be a feature request to restore feature parity to the original radiotry.  Sorry if that was unclear.

**Comment by ebruck** [comment]
"play" does what you want unless I'm mistaken.

**Comment by pjz** [comment]
'toggle' means 'on if off, off if on'; I presume (wrongly?) that 'play' was just 'turn on'.  Admittedly 'toggle' is a convenience for '_get status_; if playing: _stop_ else: _play_', but it's so common that it's useful.

**Comment by pjz** [comment]
ah, fair enough; just tested and 'play' does indeed toggle.  Sorry to bug you.
