### ISSUE TITLE
[xfce:xubuntu]:don't show in tray

### ISSUE THREAD

**Issue by Kwaskoff** [ebruck/radiotray-ng#137]
radiotray-ng installed by deb package from github release and it's not show in tray

this command $ radiotray-ng --play
show me just error pop up window

my OS installed from http://ftp.uni-kl.de/pub/linux/ubuntu-dvd/xubuntu/releases/20.04/release/xubuntu-20.04-desktop-amd64.iso
Kernel: Linux 5.4.0-31-generic
Radiotray-NG: v0.2.7 (v0.2.7-1-gfa0ea63)

**Comment by ebruck** [comment]
Did you run: `sudo apt-get install -f `to ensure all dependencies are installed?

**Comment by ebruck** [comment]
There doesn't seem to be a problem running radiotray-ng on Xubuntu 20.04. 

![image](https://user-images.githubusercontent.com/1168556/83019443-cd586d00-9fdb-11ea-8660-2e9e67d41731.png)

**Comment by braoult** [comment]
Not sure if this will help, but I had the issue with Xubuntu 21.04. For some reason, the "indicator plugin" disappeared during the upgrade, and the radiotray-ng did not show in panel. Adding the "indicator plugin" to the panel did fix the problem.
