### ISSUE TITLE
Can't install DEB on Ubuntu 20.04

### ISSUE THREAD

**Issue by iPublicis** [ebruck/radiotray-ng#138]
When installing the package with `sudo dpkg -i` it throws a lot of errors:

``pkg: radiotray-ng: problemas com dependências, mas a configurar à mesma conforme pedido:
 radiotray-ng depende de libjsoncpp1; no entanto:
  O pacote libjsoncpp1 não está instalado.
 radiotray-ng depende de libxdg-basedir1; no entanto:
  O pacote libxdg-basedir1 não está instalado.
 radiotray-ng depende de libboost-system1.71.0; no entanto:
  O pacote libboost-system1.71.0 não está instalado.
 radiotray-ng depende de libboost-log1.71.0; no entanto:
  O pacote libboost-log1.71.0 não está instalado.
 radiotray-ng depende de libboost-program-options1.71.0; no entanto:
  O pacote libboost-program-options1.71.0 não está instalado.
 radiotray-ng depende de gstreamer1.0-plugins-bad; no entanto:
  O pacote gstreamer1.0-plugins-bad não está instalado.``

Tried also with `sudo dpkg -i --force-depends`and it installed but without the dependencies and, of course, won't run.

Need to execute afterwards `sudo apt-get -f install`to install all dependencies.

**Comment by ebruck** [comment]
You do need to execute that command if installing from the command line.
