### ISSUE TITLE
dbus support

### ISSUE THREAD

**Issue by Swipe650** [ebruck/radiotray-ng#14]
Hi Ed,

I've just installed radiotray-ng and I'm very impressed, great job!

I have a number of bash and conky scripts I use with the old radiotray app and would like to rewrite them to work with radiotray-ng but they make prolific use of these two dbus commands to get the current station and song/artist:

```
qdbus net.sourceforge.radiotray /net/sourceforge/radiotray net.sourceforge.radiotray.getCurrentRadio
qdbus net.sourceforge.radiotray /net/sourceforge/radiotray getCurrentMetaData
```

I queried dbus while radiotray-ng was running and didn't see any output. Do you have any plans to offer dbus support or if you could let me know of any equivalent commands that can get me that info, that would be great.

Thanks

Swipe

**Comment by ebruck** [comment]
I was wondering when someone was going to ask for this. :-)
I'll have a look to see what's involved in supporting Radiotray's non-mpris dbus messaging interface.

**Comment by ebruck** [comment]
@Swipe650 I finally have some dbus calls working. I'm thinking of exposing everything Radiotray-NG can return and do. Would the format of the data be useful in JSON? 

Instead of a bunch of calls I'd like to expose one that returns an encoded message with:

title, artist, group, station, icon path, state, bitrate, codec & volume level

and actions to:

set station, next/prev station in group, dump bookmarks, start/stop etc. etc.

**Comment by Swipe650** [comment]
@ebruck Yes, JSON would be great. I can then use 'jq -r' to extract the bits I need.

**Comment by ebruck** [comment]
Sample output:

```
qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_state
{
   "artist" : "Suspense",
   "group" : "Old Time Radio",
   "state" : "playing",
   "station" : "AM 1710 Antioch OTR",
   "title" : "Nov 24, 1952: Mann Alive w/Paul Douglas",
   "volume" : "11"
}

```

**Comment by Swipe650** [comment]
Excellent.  Using [jq](https://stedolan.github.io/jq/) I should now be able to extract the required bits from the json formatted output. For example to get the artist:

qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state| jq -r '.artist'

**Comment by Swipe650** [comment]
It does appear that the artist field is not getting populated though and instead being included in the title field:

```
$ qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state
{
   "artist" : "",
   "group" : "Oldies",
   "image" : "~/.config/radiotray-ng/bookmark_icons/oldtimeradio",
   "state" : "playing",
   "station" : "Antioch Old Time Radio",
   "title" : "The Line-Up - Jul 15, 1952: (94) The Twitching Twist's Twenty-Two Tweaking Case",
   "volume" : "34"
}
```

**Comment by ebruck** [comment]
There is no artist info in the stream. I attempt to find it by looking for the first "dash".
Not sure what happened there, but putting that string into a test does extract the artist. 
Do you have:
 "split-title" : true 
in your ~/.config/radiotray-ng/radiotray-ng.json?

**Comment by Swipe650** [comment]
It was set to false. Fixed now

**Comment by Swipe650** [comment]
Hi Ed. 

I have an additional dbus request if possible...

In the old Radiotray app you could launch a station included your bookmarks via script/terminal  with the following command:

`qdbus net.sourceforge.radiotray /net/sourceforge/radiotray playRadio 'StationName'`

This was useful for toggling stations while a commercial break was playing. Would it also be possible to incorporate the 'playRadio' feature into your current dbus code?

I've updated my scripts and completely migrated from radiotray to Radiotray-NG now on both my machines and this is the only thing missing. I also wanted to thank you for the dbus support that you provided so swiftly.

**Comment by ebruck** [comment]
It's already there.  

```
"    <method name='play_station'>"
		"      <arg type='s' direction='in'/>"
		"      <arg type='s' direction='in'/>"
		"    </method>"
```
Pass the "group" "station name" on the command line.
