### ISSUE TITLE
Files built without respecting CFLAGS

### ISSUE THREAD

**Issue by blshkv** [ebruck/radiotray-ng#140]
Could you please fix CMakeLists.txt or wherever appropriate to address this:

 * QA Notice: Files built without respecting CFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/bin/rtng-bookmark-editor
 * /usr/bin/radiotray-ng

Thanks

**Comment by ebruck** [comment]
@blshkv radiotray-ng is written in C++ and CXXFLAGS should be picked up by cmake when generating the build files.

**Comment by blshkv** [comment]
The problem is that the current cmake does not respect global flags currenly.
You should fix using something like this:
```
-CXXFLAGS=" -Wall -Wextra"
+CXXFLAGS="${CXXFLAGS} -Wall -Wextra"
```

**Comment by blshkv** [comment]
Thanks 👌
