### ISSUE TITLE
[Feature Request] Reduce icon size

### ISSUE THREAD

**Issue by msegmx** [ebruck/radiotray-ng#144]
I've installed Radio Tray NG on Linux Mint 20 Cinnamon, it works great.

In LM20, they fixed the system tray and made all icons look similar in size and color.

Radio Tray NG 's icon looks good but is way bigger than LM20's default icons.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/X7qHjSK/systemtray.png" alt="systemtray" border="0" /></a>

Keep up the good work!

**Comment by ebruck** [comment]
The AppIndicator support a DE provides should be resizing any icon it receives to match its "standard" size. The alternative is to create new Mint theme, which I'm sorry I have no time for nor use that distro.

You can also override the icon loaded by resizing them yourself and placing them in a known location. 
Add these config entries and point them to your newly resized images.

```
"radiotray-ng-on" : "radiotray-ng-on",
"radiotray-ng-off" : "radiotray-ng-off",
"radiotray-ng-notification" : "radiotray-ng-notification",
```
