### ISSUE TITLE
CMake can't find curl in Debian?

### ISSUE THREAD

**Issue by WuShufei** [ebruck/radiotray-ng#146]
I'm trying to build to rolling Debian with MATE.  I've tried several things, but for some reason it won't cmake.  I have all the dependencies that I can tell.
``
└──╼ $cmake . -DCMAKE_BUILD_TYPE=Release
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindCURL.cmake:143 (find_package_handle_standard_args)
  CMakeLists.txt:30 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/kk03b/.radiotray-ng/radiotray-ng/CMakeFiles/CMakeOutput.log".
``
I dunno what it's looking for, as I certainly have curl.  I thought it is looking for something via curl.

``
──╼ $curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.8.0 nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

──╼ $whereis curl
curl: /usr/bin/curl /usr/share/man/man1/curl.1.gz

``
Thanks for any pointers.  I love radiotray and would like to have it back again.  Please consider a Debian binary sometime?

TTFN

**Comment by bonelifer** [comment]
It's not looking for the binary, it's looking for the curl dev lib package: libcurl4-openssl-dev  The list on the front page is for Ubuntu, but you should be able to use it to make sure you have what you need installed.  Not that you need it but here github gist with the shell script I use to build radiotray:
[build radiotray-ng](https://gist.github.com/bonelifer/e17bcea920d3bb2b8c211ed20f48f33d)
