### ISSUE TITLE
Snap Package Install Produces a Blank Icon on the System Tray in Kubuntu 20.04

### ISSUE THREAD

**Issue by Lonniebiz** [ebruck/radiotray-ng#147]
In Kubuntu 20.04, I installed radio-tray-ng like this:
sudo snap install radiotray-ng --edge

This creates a blank System Tray icon that would be completely invisible if not for the gap of space it adds between two other System Tray icons.

If you right-click on this "blank space" you do get a context menu from radio-tray-ng, however it is [missing all the categories and streams](https://github.com/ebruck/radiotray-ng/issues/148).

**Comment by ebruck** [comment]
I don't provide snap packages and you've already filed an issue like this before. You were pointed to the maintainer of the snap. Please file a bug at: https://github.com/dafanasiev/radiotray-ng-snap

**Comment by Lonniebiz** [comment]
Sorry. I completely forgot about it and had this project bookmarked for some reason. Thank you.
