### ISSUE TITLE
Context Menu is Missing All Default Categories and Streams in Kubuntu 20.04 via Snap Package Installation

### ISSUE THREAD

**Issue by Lonniebiz** [ebruck/radiotray-ng#148]
In Kubuntu 20.04, I installed radio-tray-ng like this:
sudo snap install radiotray-ng --edge

Upon right-clicking on the [Blank System Tray icon](https://github.com/ebruck/radiotray-ng/issues/147), although you do indeed see a context menu, **it is missing stream categories and provides no streams that you can click on to play.**

Please at least provide the default categories and streams that the classic RadioTray (via apt repositories) provided. Those were all I ever needed and no one wants to have to go hunting for streams the first time they try out RadioTray-NG, so please get those in there.

**Comment by ebruck** [comment]
See #147
