### ISSUE TITLE
Snapcraft.io RadioTray-NG Points Here instead of to Dmitry Afanasiev

### ISSUE THREAD

**Issue by Lonniebiz** [ebruck/radiotray-ng#149]
Go to this page:
https://snapcraft.io/radiotray-ng

Now, click on the link that says "Developer website" or the one that says "Contact Dmitry Afanasiev".

Instead of going to the correct "Developer website" or allowing you to "Contact Dmitry Afanasiev", it goes to:
https://github.com/ebruck/radiotray-ng

I realize this isn't a bug in your project, but so far I have not succeeded in getting them to correct that misdirection.

**Comment by dafanasiev** [comment]
This because snap package is owned by me (my snapcrafe account) (WIP, not finished): https://github.com/dafanasiev/radiotray-ng-snap . Now snap is private. I will try to fix snap and give @ebruck full rights afap.

**Comment by Lonniebiz** [comment]
@dafanasiev Fixing it would be appreciated by me, but I'm not sure that you should point [this page](https://snapcraft.io/radiotray-ng) to ebruck's project. You see, I've submitted issues to ebruck's project regarding your snap package and he kindly told me it was the wrong place to submit issues regarding that snap.

Perhaps you can still give credit to ebruck as an upstream resource, but also make it clear where to submit issues with the snap itself.

**Comment by dafanasiev** [comment]
@Lonniebiz - my mistake now fixed, isn't it? So, you can close this issue.

**Comment by Lonniebiz** [comment]
I guess so:
![radiotray](https://user-images.githubusercontent.com/151919/90116748-91e85780-dd1b-11ea-8362-d1e59c764d3e.png)

If you ultimately decided to create another snap. I'd like to try it. Thanks.
