### ISSUE TITLE
Failed install on CentOS 8-2004

### ISSUE THREAD

**Issue by enigma131** [ebruck/radiotray-ng#150]
Hi,
There is no Flatpak nor install package for CentOS and i like to have radio when i work :) 
So I've decided to compile source by following the Fedora method.
In required package there was missing on CentOS 8 : libxdg-basedir-devel
I got source from here : https://pkgs.dyn.su/el8/base/SRPMS/libxdg-basedir-1.2.0-22.el8.src.rpm 
I have compile it and libxdg-basedir.so.1 is in /usr/lib64 and all .h in relevant include dir etc.
Then i have follow you classic compile scheme. It is producing a . deb package. Nice then a have added a missing : 
cpack -G RPM     produce .rpm for CentOS (same is required for Fedora)
Then sudo dnf install ./radiotray-ng_0.2.7_centos_8.2.2004_amd64.rpm
gives me the error: 
Error : 
 Problem: conflicting requests
  - nothing provides libxdg-basedir.so.1()(64bit) needed by radiotray-ng-0.2.7-1.x86_64

But library is in /usr/lib64 !
What is the mess and how to solve it ?

**Comment by ebruck** [comment]
Can you please try installing **libxdg-basedir-devel-1.2.0-22.el8.x86_64.rpm** instead?

https://centos.pkgs.org/8/raven-x86_64/libxdg-basedir-devel-1.2.0-22.el8.x86_64.rpm.html

**Comment by enigma131** [comment]
Hi,
problem is not to get the necessary rmp, but to install it:
sudo rpm -i libxdg-basedir-devel-1.2.0-22.el8.x86_64.rpm
warning: libxdg-basedir-devel-1.2.0-22.el8.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 2dcd03a2: NOKEY
error: Failed dependencies:
	libxdg-basedir = 1.2.0-22.el8 is needed by libxdg-basedir-devel-1.2.0-22.el8.x86_64
	libxdg-basedir.so.1()(64bit) is needed by libxdg-basedir-devel-1.2.0-22.el8.x86_64

**Comment by ebruck** [comment]
I'm sorry I don't have anymore advice regarding centos. It's not one of the platforms I support.
