### ISSUE TITLE
Solus OS - Bookmark editor doesn't save

### ISSUE THREAD

**Issue by Skukkuk** [ebruck/radiotray-ng#151]
Hi,

I'm trying radiotray-ng on Solus and tried to add new radio stations. The first stations/groups I added where only visible after system restart. Then I added several stations and saved a *.json file to keep them, but the system/player doesn't load the stations. On every restart I do have the old incomplete list. Even when I load the before saved list, I do not get the option to save it to the system. Reloading the stations doesn't help either. 

Any idea how to solve the issue?

Thx!

**Comment by ebruck** [comment]
Did you change your "bookmarks" entry in "~/.config/radiotray-ng/radiotray-ng.json" to point to your new file?
If not then first exit radiotray-ng and update the entry.

**Comment by Skukkuk** [comment]
@ebruck Thx for pointing me into this direction. Never was able to find the config file. Now I updated it and restarted radiotray-ng, but it is still the old bookmark list. 

Here is my entry:
```
{
	# "bookmarks" : "/home/kepos/.config/radiotray-ng/bookmarks.json",
	"bookmarks" : "/home/kepos/Dokumente/Radiostreams/radiotray_ng_2020.json",
	"notification-verbose" : true,
	"notifications" : true,
	"split-title" : true,
	"volume-level" : 100
}
```
Unfortunately the former entry is restored every time I start or end radiotray-ng.

**Comment by ebruck** [comment]
You can't comment out entries in a JSON file. You have to either rename the key or delete it.
What is happening is that radiotray-ng is unable to parse the file which causes it to recreate it on shutdown.

**Comment by Skukkuk** [comment]
Ok, understood. Now it works. Many thanks for supporting me @ebruck 

Question: why so complicated? Wouldn't it be more conveniant to have a failsave.json if something went wrong and save your radio stations directly into bookmarks.json? Just my view on it.
