### ISSUE TITLE
App-Level Volume Adjustment Using Mouse-Scroll-Wheel in KDE

### ISSUE THREAD

**Issue by sispus** [ebruck/radiotray-ng#152]
In Manjaro KDE (KDE 5.73.0 / Plasma 5.19.5) this nice feature is missing. This is related, i think, with #112 
I'm not sure if it is the right place to complain or not. 
Is there a way to fix it?

**Comment by ebruck** [comment]
I've encountered these issue before with KDE and its appindicator support.
There are other issues such as line wrapped text is not rendered correctly in a menu. Please file a bug with the KDE appindicator maintainers. I have looked into this in the past and there is nothing I can do.
