### ISSUE TITLE
[FEATURE REQUEST] Package in Ubuntu 20.04 on rpi4 arch aarch64

### ISSUE THREAD

**Issue by lesar** [ebruck/radiotray-ng#154]
I have an Ubuntu 20.04 64bit and ubuntu-desktop on a rpi 4b 8G
I like tu install radiotray-ng  
can you add aarch64 architecture on deb package?  

I have ask for similar request on this project:  
[cherrytree-issue](https://github.com/giuspen/cherrytree/issues/1180)
I do not know how have they do it but @giuspen have do it in few time so I think that is not a big problem to solve.  

best regards,
Leonardo

**Comment by AquaMCU** [comment]
I just tried to build a package for rasbian. Unfortunately your build environment just compiles i386 code.

I think, the 1st step to roll out this software on RPI is to change the build environment. The distributions will pick it up and add it to their repos. But if the code does not compile they will not.

**Comment by lesar** [comment]
I do not know if is useful but I found this:  
[gcc-aarch64-linux-gnu](https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/gcc-aarch64-linux-gnu_9.3.0-1ubuntu2_amd64.deb.html)  

sudo apt-get install -y gcc-aarch64-linux-gnu

**Comment by AquaMCU** [comment]
I am compiling the code on a raspberry pi. Nevertheless, when I install the package, I get 

dpkg: Fehler beim Bearbeiten des Archivs radiotray-ng_0.2.7_raspbian_10_armhf.deb (--install):
 Paket-Architektur (i386) passt nicht zum System (armhf)
Fehler traten auf beim Bearbeiten von:
 radiotray-ng_0.2.7_raspbian_10_armhf.deb

When I start the binary in the package manually, it seems to work. So I think, we only have an issue with the cmake environment.

**Comment by AquaMCU** [comment]
In order to get the build up an running, we need to change this, so that armhf is detected and selected:
if (${CMAKE_SIZEOF_VOID_P} EQUAL 4)
        set(CPACK_SYSTEM_NAME "i386")
    else()
        if (DISTRIBUTOR_ID STREQUAL "fedora")
            set(CPACK_SYSTEM_NAME "x86_64")
        else()
            set(CPACK_SYSTEM_NAME "amd64")
        endif()
    endif()
