### ISSUE TITLE
Contact Debian for inclusion

### ISSUE THREAD

**Issue by AquaMCU** [ebruck/radiotray-ng#156]
Since we have fixed now the build for Raspberry, it would be nice to get this software into the debian repositories, so it will end up in a ton of distributions like Ubuntu and Raspberry OS.

**Comment by ebruck** [comment]
There is already a request for Ubuntu: https://bugs.launchpad.net/ubuntu/+source/radiotray/+bug/1745829
Please file one with Debian if you'd like it included there.
