### ISSUE TITLE
Left click on tray icon

### ISSUE THREAD

**Issue by enigma131** [ebruck/radiotray-ng#157]
Hi,
Installed on Linux Mint 20 via Ubuntu 20.04 's  .deb. I have Cinnamon 4.6.7 installed.
On this PC, when I left mouse click on tray icon, i have same menu as right click.
On previous PC with Cinnamon LM 19.3, when I left click on tray icon it toggles on/off playing last channel. I expected same on LM 20 but why it didn't work as previous?

**Comment by ebruck** [comment]
There is no special menu for toggling on/off when clicking the left button. Radiotray-ng has always been this way with both left/right showing the same full menu. It's been a while, but could you be mixing the behaviour up with the original python based radiotray application?

**Comment by enigma131** [comment]
Yes on old PC I had a older Radiotray installed on it but actually the same as on this PC (-ng 0.2.7 version ). Visibly old installation interact with yours ?
I found the feature interesant, I mean toggle On/Off whit 1 click. Could it be restored and how?

An other request what would be great:
On Gnome desktops i have try :  https://extensions.gnome.org/extension/836/internet-radio/
This one have a dedicated volume control from the tray icon. 
Could this feature be implemented too ?

**Comment by ebruck** [comment]
You can toggle on/off by middle clicking on the icon.

**Comment by enigma131** [comment]
No it's not a bug from Linux mint. All theses tricks are impossible on my laptop because no real mouse but touchpad.

**Comment by ebruck** [comment]
I'm sorry then there's nothing more I can do.

**Comment by enigma131** [comment]
Shame.

**Comment by ebruck** [comment]
All touchpads should be able to send middle clicks and scroll events. I don't know what more I can do when I support everything you want?

**Comment by enigma131** [comment]
Hi. Ok forget sound volume control. It was a feature I've seen on competitor application (it is done to have separate volume control of application)
My request was to have left click to toggle as i have it on other computer, it is a little funny to have same effect for left and right click, but it's my personal opinion and I haven't see that elsewhere. Forget If you don't want to consider it.

**Comment by ebruck** [comment]
This has been discussed before.
Appindicators do not allow you to differentiate between left/right clicks. https://github.com/ebruck/radiotray-ng/issues/25#issuecomment-329048268

**Comment by enigma131** [comment]
Thanks for the link.
The thing I didn't understand is why it is working on PC A and not on PC B . Linux Mint cinnamon in both cases (not same revision of cinnamon of course). Very strange this situation
