### ISSUE TITLE
Not enough space to read radio information data

### ISSUE THREAD

**Issue by r-da** [ebruck/radiotray-ng#159]
Hi,
beautiful program, with a small issue.
See the second line, below "Turn Off...": not enough space to read the full text. Could you please fix it?

![image](https://user-images.githubusercontent.com/25054264/97114824-1d566f80-16f3-11eb-98db-5f95ee12a5be.png)

Thanks in advance.

**Comment by ebruck** [comment]
Are you using Plasma/QT? 
This is a limitation of the way menus are rendered. https://github.com/ebruck/radiotray-ng/issues/68

**Comment by r-da** [comment]
Yes ... I am using KDE with Ubuntu 20.04 (therefore, I am using Qt 5.12.5).
Since 2018 still a limitation... what a pity.
