### ISSUE TITLE
Doesn't handle AAC streams well

### ISSUE THREAD

**Issue by KayTaneJupiter** [ebruck/radiotray-ng#160]
Doesn't seem to handle AAC streams well

Examples:

https://somafm.com/groovesalad64.pls

http://totalbroadcast.net/zenith/zenith32.pls

**Comment by ebruck** [comment]
Both streams play fine for me. What issues are you having?

**Comment by KayTaneJupiter** [comment]
"Internal data stream error"

**Comment by ebruck** [comment]
Try this:  

`$ gst-play-1.0 "http://ice6.somafm.com/groovesalad-64-aac"`

If this doesn't play then you need to install more codecs.
How did you install radiotray-ng and what version of Linux are you using?

**Comment by KayTaneJupiter** [comment]
Nope. Works in Firefox and VLC but not radiotray-ng.

What additional codecs are required?

Using OpenSUSE Tumbleweed, installed from repos.

**Comment by ebruck** [comment]
Did you run that command?

**Comment by KayTaneJupiter** [comment]
Ooops. Sorry. Didn't realize that's what it was.

`$ gst-play-1.0 "http://ice6.somafm.com/groovesalad-64-aac"
Press 'k' to see a list of keyboard shortcuts.
Now playing http://ice6.somafm.com/groovesalad-64-aac
Prerolling...
WARNING No decoder available for type 'audio/mpeg, framed=(boolean)true, mpegversion=(int)2, level=(string)1, profile=(string)lc, rate=(int)22050, channels=(int)2, stream-format=(string)adts'.
WARNING debug information: ../gst/playback/gsturidecodebin.c(957): unknown_type_cb (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0
ERROR Your GStreamer installation is missing a plug-in. for http://ice6.somafm.com/groovesalad-64-aac
ERROR debug information: ../gst/playback/gsturidecodebin.c(1024): no_more_pads_full (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0:
no suitable plugins found:
../gst/playback/gstdecodebin2.c(4719): gst_decode_bin_expose (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: MPEG-2 AAC (audio/mpeg, framed=(boolean)true, mpegversion=(int)2, level=(string)1, profile=(string)lc, rate=(int)22050, channels=(int)2, stream-format=(string)adts)

Reached end of play list.`

**Comment by ebruck** [comment]
Ensure that these are installed.  The naming may be different under OpenSUSE:

 gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly

**Comment by KayTaneJupiter** [comment]
They are simply "gstreamer-plugs-..." in OpenSUSE. However, even with them all installed (they were previously) the stream does not play. I suspect an MPEG2 licensing / patent problem. SUSE's lawyers are particular touchy about that.

Ironically, the MP3 streams work fine. I'll just use those.
