### ISSUE TITLE
non-continuous playback

### ISSUE THREAD

**Issue by lexmarko** [ebruck/radiotray-ng#161]
Hello guys,

I have been using the program with satisfaction for a long time, thank you.
I'm using Radiotray NG 0.2.7 ubuntu package under debian 10.
I have wired internet access, but lately, playback has been interrupted many times, sometimes not even restarting just by turning it on manually.
The sample radiotray-ng.json file contains a buffer entry, however not in my own file, in fact, if I type and go every time I turn it on it overwrites again and again without the buffer is not found.
Content of your own and non-overwritable file:
"bookmarks" : "/home/lexmarko/.config/radiotray-ng/bookmarks.json",
	"last-station" : "Magic Disco Radio stream2",
	"last-station-group" : "RMI",
	"last-station-notifications" : true,
	"notification-verbose" : true,
	"notifications" : true,
	"split-title" : true,
	"volume-level" : 100 

How to solve the interruption, to set the buffering?
I hope that would resolve the rift.

**Comment by ebruck** [comment]
You must not edit the config file while radiotray-ng is running.

**Comment by lexmarko** [comment]
Thanks, so I can already change the buffering time and size, it helped.
