### ISSUE TITLE
Cant get any radio to load

### ISSUE THREAD

**Issue by InvisibleRasta** [ebruck/radiotray-ng#163]
Hello guys. I have just built radiotray-ng on my gentoo install and i cant figure out why all the radios will just error saying:
Failed to download playlist.
This is the ebuild i am using:

EAPI=7

inherit cmake-utils

DESCRIPTION="Online radio streaming player"
HOMEPAGE="https://github.com/ebruck/radiotray-ng"

case ${PV} in
9999)
	EGIT_REPO_URI="https://github.com/ebruck/${PN}.git"
	inherit git-r3
	;;
*)
	KEYWORDS="~amd64 ~x86"
	SRC_URI="https://github.com/ebruck/radiotray-ng/archive/v${PV}.tar.gz -> ${P}.tar.gz"
	;;
esac

LICENSE="GPL-3"
SLOT="0"
IUSE=""

DEPEND="
	dev-libs/libbsd
	net-misc/curl
	dev-libs/jsoncpp
	dev-libs/libxdg-basedir
	x11-libs/libnotify
	dev-lang/python:2.7
	dev-python/lxml
	dev-cpp/glibmm
	dev-libs/boost
	media-libs/gstreamer
	dev-libs/libappindicator
	media-libs/gst-plugins-bad
	media-libs/gst-plugins-good
	media-libs/gst-plugins-ugly
	media-plugins/gst-plugins-mpg123
	media-plugins/gst-plugins-faad
	x11-libs/wxGTK:3.0-gtk3
"

RDEPEND="${DEPEND}"
BDEPEND=""

**Comment by ebruck** [comment]
I'm sorry I can't help you with this as it's not one of the distros I support. Please see the ebuild creators for help.
