### ISSUE TITLE
Install / build for Mac?

### ISSUE THREAD

**Issue by steveharman** [ebruck/radiotray-ng#167]
HI,

I couldn't find a release or build instructions for Mac - did I miss something?

Thanks

**Comment by ebruck** [comment]
The code as it is today cannot be easily compiled on a Mac. I no longer have the time nor interest in making it work. When I'm on a Mac I use this script to convert my bookmarks into something the Music app can open.
https://github.com/ebruck/radiotray-ng/blob/master/src/radiotray-ng/extras/scripts/rtng2xml
