### ISSUE TITLE
GTK3 instead GTK2?

### ISSUE THREAD

**Issue by TomaszGasior** [ebruck/radiotray-ng#17]
I thank you for your simple app. It is incomplete, but very useful even in current state.

Why did you use GTK2 instead GTK3? GTK2 is deprecated and outdated. It is possible to add compile option to use GTK3?

Also, please do not use stock menu item such as "About", "Preferences", "Close". Stock is deprecated. Instead, create this menu items manually.

**Comment by ebruck** [comment]
I've already converted Radiotray-NG to gtk3. It's in my v0.1.7-dev branch along with a few other missing features.

**Comment by TomaszGasior** [comment]
Sorry for my mistake. ;)
