### ISSUE TITLE
volume level configuration doesn't mantain settings

### ISSUE THREAD

**Issue by stekturku** [ebruck/radiotray-ng#170]
i am using
uname -a
Linux <hostname> 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

I have set the volume-level in the json configuration file

~/.config/radiotray-ng/
-rw-rw-r-- 1 esti esti  278 giu 25 21:26 radiotray-ng.json

{
	"bookmarks" : "/home/esti/.config/radiotray-ng/bookmarks.json",
	"last-station" : "Rai Radio 1",
	"last-station-group" : "Radio Rai",
	"last-station-notifications" : true,
	"notification-verbose" : true,
	"notifications" : true,
	"split-title" : true,
	"volume-level" : 10
}

i exec radiotray-ng
i turn on the radio
and i listen it at the volume-level set.
i turn off the radio station or i close the app or i change the radio station
i turn on the same or different radio station the volume is newly set at 100 (the file is properly modified)
the same thing happen if i close and run the app or change the radio station

**Comment by ebruck** [comment]
@stekturku I believe there is a bug here and I am investigating, but in the mean time if you use your mouse wheel over radiotray-ng's icon to adjust the volume then it should be fine.

**Comment by rogue-ronin** [comment]
Hey! Long time no comment, radiotray-ng has just been a workhorse.

But I'm commenting here because I can no longer adjust volume using my mouse wheel.

Should I open a new issue?

[info.txt](https://github.com/ebruck/radiotray-ng/files/6757528/info.txt)

**Comment by ebruck** [comment]
This would be an issue with appindicator support in Xfce.

**Comment by rogue-ronin** [comment]
Is this something that's known, or something I should pursue with XFCE?

Thanks for the quick response.

**Comment by stekturku** [comment]
sorry i am late to answer to you... thanks for the tip, i will try...


--
Stek Turku
(irl Stefano Tarquini)
Inviato dal mio tablet Android

Il sab 26 giu 2021, 20:49 Ed Bruck ***@***.***> ha scritto:

**Comment by stekturku** [comment]
> @rogue-ronin This would be an issue with appindicator support in Xfce.

right i am using Xubuntu 20.04.3 LTS (5.4.0-81-generic #91  x86_64)

**Comment by stekturku** [comment]
> Hey! Long time no comment, radiotray-ng has just been a workhorse.
> 
> But I'm commenting here because I can no longer adjust volume using my mouse wheel.
> 

me too.

I cannot adjust it.

**Comment by zen2** [comment]
Actually, volume control on tray icon works here but:
- no indicator of volume level set/change
- I can only see volume level in menu after have change it
- volume can go from 0% to 200% ! (why 200% ?)

Do I need a specific dependencie to get volume level indicator ?
I have currently libnotify and libappindicator linked in radiotray-ng binary.

**Comment by rogue-ronin** [comment]
@ebruck Would you consider a 10|20|30|40|50|60|70|80|90|100 selector in the menu as a workaround?

**Comment by ebruck** [comment]
> Actually, volume control on tray icon works here but:
> 
> * no indicator of volume level set/change
> * I can only see volume level in menu after have change it
> * volume can go from 0% to 200% ! (why 200% ?)
> 
> Do I need a specific dependencie to get volume level indicator ?
> I have currently libnotify and libappindicator linked in radiotray-ng binary.

There is no notify popup when volume levels change except when use dbus to change it.
I did not add it for normal use as it's annoying to say the least having it popup for every change.

**Comment by zen2** [comment]
> There is no notify popup when volume levels change except when using DBUS to change it.
> I did not add it for normal use as it's annoying to say the least having it popup for every change.
> Maximum volume level can be changed if you want. Please have a look at https://github.com/ebruck/radiotray-ng/blob/master/README.md#config-file

In old python radiotray, a little popup appeared to show radiotray local volume when you use the mouse wheel to change it.
You can see it at the beginning of this video: https://www.youtube.com/watch?v=RfT-lGz1dFA

**Comment by ebruck** [comment]
> > There is no notify popup when volume levels change except when using DBUS to change it.
> > I did not add it for normal use as it's annoying to say the least having it popup for every change.
> > Maximum volume level can be changed if you want. Please have a look at https://github.com/ebruck/radiotray-ng/blob/master/README.md#config-file
> 
> In old python radiotray, a little popup appeared to show radiotray local volume when you use the mouse wheel to change it.
> You can see it at the beginning of this video: https://www.youtube.com/watch?v=RfT-lGz1dFA
> It was really convenient since you can see in real time volume specific to radiotray.

Yes and tooltips no longer exist so the recommended way of displaying that info is within the menu as a "disabled" item.

**Comment by zen2** [comment]
> Tooltips no longer exist so the recommended way of displaying that info is within the menu as a "disabled" item.

Oh I see. So why not add the volume as an overlay on the tray icon and refresh it simply ?
Is it possible ?

**Comment by rogue-ronin** [comment]
Rolling over the tray icon with the mousewheel is working again. Don't know whether to thank you or to thank the XFCE guys, but you deserve thanks anyway because radiotray-ng is awesome and does one thing extremely well.

Aloha, brother!

**Comment by Iamwithin** [comment]
Is there some way to give a financial contribution to this project? Man has to have his music. :-)

Bill Skiles
