### ISSUE TITLE
Start playing the last station

### ISSUE THREAD

**Issue by dulvi** [ebruck/radiotray-ng#172]
Hello and thanks for this great app!

Is it possible that the app starts playing automatically the last radio station?

**Comment by ebruck** [comment]
Yes. 

From the README.md:

--play command line option for resuming playback

**Comment by dulvi** [comment]
Would you be so kind to explain to an ignorant how and where should I put that in order to get the app starts playing automatically?
Many thanks in advance

**Comment by ebruck** [comment]
Run **gnome-session-properties** (Startup Applications Preferences) and edit Radiotray-NG's command:

![Screenshot from 2021-07-26 19-31-19](https://user-images.githubusercontent.com/1168556/127085775-47796009-400c-4086-9dc6-e9dd154a7332.png)

**Comment by dulvi** [comment]
OHH!
It was so easy!
Thank you very much for your nice help, you were so kind
Keep up the great work!
