### ISSUE TITLE
Crostini problem

### ISSUE THREAD

**Issue by binMonkey** [ebruck/radiotray-ng#173]
Hi, I'm new to github so I'm not sure if I'm allowed to ask for help.

I've successfully installed radiotray-ng on my linux side, but running it from the command line gives me this error:  (radiotray-ng:3271): Gtk-CRITICAL **: 09:25:23.425: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

Running it from the icon just shows a spinning cirlce over the icon.  I have all the dependencies I could find installed and my chromeos is up to date.  I'm on an Acer 14 CB3-431.  Can you please help me with this?

**Comment by ebruck** [comment]
I'm sorry I have no idea what Crostini is or how radiotray-ng behaves on ChromeOS.
My guess would be appindicator support is not complete.
