### ISSUE TITLE
Dependency update in ubuntu 21.04

### ISSUE THREAD

**Issue by csoeder** [ebruck/radiotray-ng#174]
Hi, I did a fresh install of Kubuntu 21.04 and when I was reinstalling my software found that radiotray-ng wouldn't install. Following the instructions on the github repo, including installing the given dependencies (in particular libjsoncpp-dev ) everything goes smoothly until:

`$ sudo dpkg -i radiotray-ng_0.2.7_ubuntu_21.04_amd64.deb`
_Selecting previously unselected package radiotray-ng._
_(Reading database ... 299488 files and directories currently installed.)_
_Preparing to unpack radiotray-ng_0.2.7_ubuntu_21.04_amd64.deb ..._
_Unpacking radiotray-ng (0.2.7) ..._
_dpkg: dependency problems prevent configuration of radiotray-ng:_
 _radiotray-ng depends on libjsoncpp1; however:_
  _Package libjsoncpp1 is not installed._

_dpkg: error processing package radiotray-ng (--install):_
 _dependency problems - leaving unconfigured_
_Processing triggers for mailcap (3.68ubuntu1) ..._
_Processing triggers for desktop-file-utils (0.26-1ubuntu1) ..._
_Processing triggers for hicolor-icon-theme (0.17-2) ..._
_Errors were encountered while processing:_
 _radiotray-ng_

Trying to install that particular package fails: 

`$ sudo apt-get install libjsoncpp1`
_Reading package lists... Done_
_Building dependency tree... Done_
_Reading state information... Done_
_Package libjsoncpp1 is not available, but is referred to by another package._
_This may mean that the package is missing, has been obsoleted, or_
_is only available from another source_

_E: Package 'libjsoncpp1' has no installation candidate_

Worse, once the radiotray-ng installation fails, the package manager gets messed up:

`$ sudo apt-get upgrade `
_Reading package lists... Done_
_Building dependency tree... Done_
_Reading state information... Done_
_Calculating upgrade... Done_
_The following packages will be REMOVED:_
  _radiotray-ng_
_The following packages have been kept back:_
  _libegl-mesa0 libgbm1 libgl1-mesa-dri libglapi-mesa libglx-mesa0_
  _libxatracker2 mesa-va-drivers mesa-vdpau-drivers mesa-vulkan-drivers_
  _ubuntu-advantage-tools_
_0 upgraded, 0 newly installed, 1 to remove and 10 not upgraded._
_1 not fully installed or removed._
_After this operation, 1,606 kB disk space will be freed._
_Do you want to continue? [Y/n] y_
_(Reading database ... 299489 files and directories currently installed.)_
_Removing radiotray-ng (0.2.7) ..._
_gtk-update-icon-cache: Failed to open file /usr/share/icons/Yaru/.icon-theme.cache : No such file or directory_
_dpkg: error processing package radiotray-ng (--remove):_
 _installed radiotray-ng package post-removal script subprocess returned error exit status 1_
_dpkg: too many errors, stopping_
_Errors were encountered while processing:_
 _radiotray-ng_
_Processing was halted because there were too many errors._
_E: Sub-process /usr/bin/dpkg returned an error code (1)_

running remove, autoremove, purge, --fix-broken, etc don't fix. 
I was eventually able to fix the package manager thus:

`$ sudo rm /var/lib/dpkg/info/radiotray-ng.* ; sudo apt-get purge`

**Comment by ebruck** [comment]
This has already been addresses in the v0.2.8-dev branch. https://github.com/ebruck/radiotray-ng/commit/4197a0ceb38092eb950ff0ef36d2614f24cc93f4
