### ISSUE TITLE
doesn't start

### ISSUE THREAD

**Issue by Kwaskoff** [ebruck/radiotray-ng#176]
console start: 
Gtk-CRITICAL **: 14:12:33.419: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

fedora 34, gnome 40

**Comment by ebruck** [comment]
You need to install this: https://extensions.gnome.org/extension/615/appindicator-support/
Unfortunately it's not installed by default like Ubuntu does.
