### ISSUE TITLE
Debian package is missing libappindicator3-1 dependency 

### ISSUE THREAD

**Issue by brentr** [ebruck/radiotray-ng#177]
Debian package is missing dependency on required libappindicator3-1 library

**Comment by ebruck** [comment]
What version of Debian are you using?

**Comment by bamper45** [comment]
> Какую версию Debian вы используете?

Apparently debian 11, since I use it and I also write

**Comment by xtrahigh** [comment]
As a temporary kludge you can use `libayatana-appindicator3-1` instead of `libappindicator3-1`
```
dpkg-deb -x radiotray-ng*amd64.deb radiotray-ng-fix
dpkg-deb -e radiotray-ng*amd64.deb radiotray-ng-fix/DEBIAN
rm -f radiotray-ng*amd64.deb
sed -i 's/libappindicator3-1/libayatana-appindicator3-1/' radiotray-ng-fix/DEBIAN/control
dpkg-deb -b radiotray-ng-fix radiotray-ng-fix_amd64.deb
rm -rf radiotray-ng-fix
sudo apt install ./radiotray-ng-fix_amd64.deb
```
Now you should get the _"cannot open shared object file"_ error when trying to run `radiotray-ng`, let's fix it:
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libayatana-appindicator3.so.1 /usr/lib/x86_64-linux-gnu/libappindicator3.so.1
```
Works on my Debian Sid.

**Comment by ebruck** [comment]
Are you building from source or using the Ubuntu version?

**Comment by brentr** [comment]
I installed the .deb package on debian 11
It works fine after I manually installed the missing libappindicator3-1

**Comment by ebruck** [comment]
If you build the package from source. it should use the correct library:
https://github.com/ebruck/radiotray-ng/blob/20a7904fa62dedc3c5880afd84d91030dd26d92d/package/CMakeLists.txt#L65
