### ISSUE TITLE
A method to trigger notification

### ISSUE THREAD

**Issue by apitanga** [ebruck/radiotray-ng#178]
I'm trying to figure out a method to wrap a keyboard shortcut around to display (send notification of) the currently playing Station, Artist and Title, not unlike how radiotray-ng already does normally when that information changes, but upon request.

I could not find a dbus method or a CLI flag to just show/notify the currently playing  information.  Is there a simple way that I may be missing, or is this a fair request for new feature?

**Comment by ebruck** [comment]
Have a look at the [README.md](https://github.com/ebruck/radiotray-ng#dbus-interface)

**Comment by ebruck** [comment]
Using the helper script [rtng-dbus](https://github.com/ebruck/radiotray-ng/blob/master/src/radiotray-ng/extras/scripts/rtng-dbus) you can do something like this:

$ rtng-dbus get_player_state |  jq .title,.artist | xargs notify-send

**Comment by apitanga** [comment]
I should have clarified that I am currently using this method, 

`station=$(/usr/bin/qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq '.station' | tr -d '"')`

But I've found constructing the notification (I'm using notify-send) using this variable generates a notification that's despite my efforts not as aesthetically pleasing as the one generated automatically by radiotray-ng itself.  That's why I was wondering if there was  away to trigger the notification, rather than parse the json from the whole palyer_state dump.

Also I would prefer not to have to code this myself, but rather rely on a simple flag or method in the player itself if one existed.

**Comment by apitanga** [comment]
Thank you, I'll check it out

**Comment by apitanga** [comment]
Ended up going with,
```

artist_title=$(rtng-dbus get_player_state | jq '.artist,.title | select( . != null )' | tr -d '"' | tr -d
'\\')
station=$(rtng-dbus get_player_state | jq '.station' | tr -d '"' | tr -d '\\')
notify-send -i radiotray-ng-notification "$station" "$artist_title"
```
