### ISSUE TITLE
Customizable Color of tray icon

### ISSUE THREAD

**Issue by RealVegOs** [ebruck/radiotray-ng#179]
I would suggest an option to set the color of the tray icon. My taskbar background color is #D8E3E8 (blueish light gray) and the tray icon is nearly white. I would prefer a better contrast. BTW I really like the icon. Will radiotray-ng make its way into the official Debian repos? radiotray is gone radiotray-lite looks like abandoned. Thanks for your good work, enjoy coming holidays.

**Comment by ebruck** [comment]
@RealVegOs radiotray-ng supports using icon themes.
You can also override the default entry in the config for "radiotray-ng-on" and "radiotray-ng-off" by pointing them to an icon you'd like to use.

**Comment by RealVegOs** [comment]
Thank you! Works, but the settings do not accept a path. I have to put my icons to yours with own names or modify the originals.

**Comment by ebruck** [comment]
Hmm... this works for me.

"radiotray-ng-on" : "/home/ebruck/Google Drive/.radiotray-ng/icons/ihradio.jpg",
"radiotray-ng-notification" : "/usr/share/icons/hicolor/256x256/apps/radiotray-ng-notification.png",
