### ISSUE TITLE
xfce 4.16 no icon change in the tray

### ISSUE THREAD

**Issue by fre-ac** [ebruck/radiotray-ng#181]
I have changed from Slackware 14.2 xfce 4.12 to Slackware 15 xfce version 4.16 .
Now when I turn on radiotray-ng the tray icon does not change (radiotray-ng on/off).
Only the radiotray-ng off icon is visible.
xfce 4.12
![xfce4 12_raiotray-ng_off](https://user-images.githubusercontent.com/85880630/151008513-f41a5458-101f-4904-852d-4859c2be68d0.png)
![xfce4 12_raiotray-ng_on](https://user-images.githubusercontent.com/85880630/151008528-4f70184b-2704-4d94-b7f2-5f8adaf65659.png)

xfce 4.16
![xfce4 16_radiotray-ng off](https://user-images.githubusercontent.com/85880630/151008594-bb862e07-06ce-46a5-991e-ead88601b7b5.png)
![xfce4 16_radiotray-ng on](https://user-images.githubusercontent.com/85880630/151008622-a8229235-0405-47e5-8e91-e5ac2c939457.png)
I am using version 0.2.8 which I compiled from source.
What should I do to make the icon change?

**Comment by ebruck** [comment]
Experience has shown that this is likely an issue with xfce's support of appindicators.
https://github.com/ebruck/radiotray-ng/issues?q=is%3Aissue+is%3Aclosed+xfce
