### ISSUE TITLE
No radiotray-ng icon in tray

### ISSUE THREAD

**Issue by eisraeli** [ebruck/radiotray-ng#182]
Hi,
Just installed `radiotray-ng` for the first time.
No icon was showing after installation so I tried running it from the CLI (`/usr/bin/radiotray-ng`).

I'm getting the following error:
`(radiotray-ng:205953): Gtk-CRITICAL **: 16:11:49.869: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`

Running on:
Fedora 35 (5.15.16-200.fc35.x86_64), GNOME Shell 41.3

**Comment by ebruck** [comment]
Please have a look at #176
