### ISSUE TITLE
Build on Ubuntu 22.04

### ISSUE THREAD

**Issue by Kwaskoff** [ebruck/radiotray-ng#185]
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:890 (message):
  None of the required 'ayatana-appindicator3-0.1' found
Call Stack (most recent call first):
  CMakeLists.txt:71 (pkg_search_module)
```
```

libgtk-3-dev : Depends: gir1.2-gtk-3.0 (= 3.24.33-1ubuntu1) but 3.24.33-1ubuntu2 is to be installed
                Depends: libgtk-3-0 (= 3.24.33-1ubuntu1) but 3.24.33-1ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I can't solve this issue

**Comment by ebruck** [comment]
From the readme:

# For Ubuntu 22.04 and newer install libayatana-appindicator3-dev otherwise use libappindicator3-dev

See if that helps.

**Comment by ebruck** [comment]
You can also download from the latest release page:  https://github.com/ebruck/radiotray-ng/releases/download/v0.2.8/radiotray-ng_0.2.8_ubuntu_22.04_amd64.deb

**Comment by Kwaskoff** [comment]
> From the readme:
> 
> For Ubuntu 22.04 and newer install libayatana-appindicator3-dev otherwise use libappindicator3-dev
> 
> See if that helps.
of course, i did it before

**Comment by Kwaskoff** [comment]
> You can also download from the latest release page: https://github.com/ebruck/radiotray-ng/releases/download/v0.2.8/radiotray-ng_0.2.8_ubuntu_22.04_amd64.deb

yeah, it works! Thx
