### ISSUE TITLE
error dependency is not satisfiable libjsoncpp1

### ISSUE THREAD

**Issue by satxtreme** [ebruck/radiotray-ng#187]
When compiling I used Linux Mint 21...
Compilation runs without errors, but when starting .deb i have **error dependency is not satisfiable libjsoncpp1**
**p.s** If rebuild the deb package and change the line in control> libjsoncpp1 to libjsoncpp25. All good install without mistakes

**Full log**
`satxtreme@satxtreme:~/test/radiotray-ng/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.81.0")  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: filesystem system log program_options thread 
-- wxWidgets: Found gtk3 version, using it.
-- Found wxWidgets: -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_gtk3u_core-3.0;-lwx_baseu-3.0;-lwx_gtk3u_adv-3.0 (found version "3.0.5") 
-- Checking for one of the modules 'jsoncpp'
-- Checking for one of the modules 'gstreamer-1.0'
-- Checking for one of the modules 'libxdg-basedir'
-- Checking for one of the modules 'libbsd'
-- Checking for one of the modules 'appindicator3-0.1'
-- Checking for one of the modules 'ayatana-appindicator3-0.1'
-- Checking for one of the modules 'libnotify'
-- Checking for one of the modules 'glibmm-2.4'
-- Checking for one of the modules 'giomm-2.4'
Building version: 0.2.8 for linuxmint 21 -- DEB packaging...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/satxtreme/test/radiotray-ng/build
satxtreme@satxtreme:~/test/radiotray-ng/build$ make package
[  2%] Generating rtng_user_agent.hpp
[  2%] Built target user-agent
[  4%] Building CXX object src/radiotray-ng/gui/appindicator/CMakeFiles/appindicator_gui.dir/appindicator_gui.cpp.o
[  7%] Linking CXX static library libappindicator_gui.a
[  7%] Built target appindicator_gui
[  9%] Building CXX object src/radiotray-ng/config/CMakeFiles/config.dir/config.cpp.o
[ 11%] Linking CXX static library libconfig.a
[ 11%] Built target config
[ 14%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/asf_decoder.cpp.o
[ 16%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/asx_decoder.cpp.o
[ 19%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/m3u_decoder.cpp.o
[ 21%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/ds_decoder.cpp.o
[ 23%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/pls_decoder.cpp.o
[ 26%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/ram_decoder.cpp.o
[ 28%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/xspf_decoder.cpp.o
[ 30%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/playlist_downloader.cpp.o
[ 33%] Linking CXX static library libplaylist.a
[ 33%] Built target playlist
[ 35%] Building CXX object src/radiotray-ng/bookmarks/CMakeFiles/bookmarks.dir/bookmarks.cpp.o
[ 38%] Linking CXX static library libbookmarks.a
[ 38%] Built target bookmarks
[ 40%] Building CXX object src/radiotray-ng/event_bus/CMakeFiles/event_bus.dir/event_bus.cpp.o
[ 42%] Linking CXX static library libevent_bus.a
[ 42%] Built target event_bus
[ 45%] Building CXX object src/radiotray-ng/player/CMakeFiles/player.dir/player.cpp.o
[ 47%] Linking CXX static library libplayer.a
[ 47%] Built target player
[ 50%] Building CXX object src/radiotray-ng/notification/CMakeFiles/notification.dir/linux/notification.cpp.o
[ 52%] Linking CXX static library libnotification.a
[ 52%] Built target notification
[ 54%] Building CXX object src/radiotray-ng/extras/media_keys/CMakeFiles/media_keys.dir/linux/media_keys.cpp.o
[ 57%] Linking CXX static library libmedia_keys.a
[ 57%] Built target media_keys
[ 59%] Building CXX object src/radiotray-ng/extras/rtng_dbus/CMakeFiles/rtng_dbus.dir/rtng_dbus.cpp.o
[ 61%] Linking CXX static library librtng_dbus.a
[ 61%] Built target rtng_dbus
[ 64%] Building CXX object src/radiotray-ng/CMakeFiles/radiotray-ng.dir/main.cpp.o
[ 66%] Building CXX object src/radiotray-ng/CMakeFiles/radiotray-ng.dir/radiotray_ng.cpp.o
[ 69%] Linking CXX executable ../../radiotray-ng
[ 69%] Built target radiotray-ng
[ 71%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/editor_app.cpp.o
[ 73%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/editor_bookmarks.cpp.o
[ 76%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/editor_dialog_base.cpp.o
[ 78%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/editor_frame.cpp.o
[ 80%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/group_drop_target.cpp.o
[ 83%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/group_editor_dialog.cpp.o
[ 85%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/group_list.cpp.o
[ 88%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/image_list.cpp.o
[ 90%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/station_drop_target.cpp.o
[ 92%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/station_editor_dialog.cpp.o
[ 95%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/station_list.cpp.o
[ 97%] Building CXX object src/radiotray-ng/gui/editor/CMakeFiles/rtng-bookmark-editor.dir/status_dialog.cpp.o
[100%] Linking CXX executable ../../../../rtng-bookmark-editor
[100%] Built target rtng-bookmark-editor
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: radiotray-ng
CPack: - Install project: radiotray-ng []
CPack: Create package
CPack: - package: /home/satxtreme/test/radiotray-ng/build/radiotray-ng_0.2.8_linuxmint_21_amd64.deb generated`

**Comment by ebruck** [comment]
Could you please post the output from:  `lsb_release -a`

**Comment by satxtreme** [comment]
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa

**Comment by satxtreme** [comment]
`No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa`

**Comment by ebruck** [comment]
Could you try changing package/CMakeLists.txt line 54 to this and see if helps?

`if (${RELEASE} STREQUAL "21.04" OR ${RELEASE} STREQUAL "21")`

**Comment by satxtreme** [comment]
``CMake Error at CMakeLists.txt:58 (if):
  Flow control statements are not properly nested

**Comment by satxtreme** [comment]
`CMake Error at CMakeLists.txt:58 (if):
  Flow control statements are not properly nested`

**Comment by ebruck** [comment]
Not sure why that doesn't work for you. Try reverting the line and change "22.04" to "21" instead.

**Comment by satxtreme** [comment]
Please add modified file

**Comment by satxtreme** [comment]
Please add modified file

**Comment by satxtreme** [comment]
> `if (${RELEASE} STREQUAL "22.04" OR ${RELEASE} STREQUAL "21")`
Working, now  all so good

**Comment by satxtreme** [comment]
Many thanks for help !

**Comment by satxtreme** [comment]
> Not sure why that doesn't work for you. 
Sorry, my mistake

**Comment by Systemk2** [comment]
I had exactly the same problem after upgrading to Linux Mint 21 Vanessa. I had to replace libjsoncpp1 by libjsoncpp25 in package/CMakeLists.txt to make it work.

```
cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21
DISTRIB_CODENAME=vanessa
DISTRIB_DESCRIPTION="Linux Mint 21 Vanessa"

```

@ebruck Is there a reason you depend on a specific *.so version, rather than depending on generic libjsoncpp-dev?
