### ISSUE TITLE
broken dependencies

### ISSUE THREAD

**Issue by razbone** [ebruck/radiotray-ng#190]
any possibility to make it workDeepin 20.7.1 

![1](https://user-images.githubusercontent.com/53272125/200979463-6bb6e778-5b60-47b5-be7a-fd1b10879d52.jpg)
![2](https://user-images.githubusercontent.com/53272125/200979506-2214bff2-06a8-4bd6-b30e-4226d499f112.png)
![3](https://user-images.githubusercontent.com/53272125/200979547-00f248ce-c459-4db6-93b5-9adeb181ee2c.png)

**Comment by ebruck** [comment]
@razbone sorry I don't support Deepin. You'll have to recompile and create a package yourself.
