### ISSUE TITLE
title and artist do not copy by mouse click

### ISSUE THREAD

**Issue by pivusan** [ebruck/radiotray-ng#191]
ubuntu 22.04
radiotray-ng_0.2.8_ubuntu_22.04_amd64.deb installed

```cat ~/.config/radiotray-ng/radiotray-ng.json 
{
	"bookmarks" : "/home/pav/.config/radiotray-ng/bookmarks.json",
	"debug-logging" : true,
	"disable-logging" : true,
	"ihr-title" : true,
	"last-station" : "Soundpark Deep",
	"last-station-group" : "root",
	"last-station-notifications" : true,
	"notification-verbose" : true,
	"notifications" : true,
	"root-group-bottom-pos" : false,
	"split-title" : true,
	"tag-info-verbose" : true,
	"track-info-copy" : true,
	"volume-level" : 100
}```
i click on icon radiotray-ng in tray 
i click on area where title and artist show
there is nothing in buffer

**Comment by ebruck** [comment]
@pivusan are you using wayland? It only works for me under xorg.

**Comment by ebruck** [comment]
From the little reading I've done, it may not be possible to set the clipboard contents (under wayland) unless your application window has focus. Since radiotray-ng doesn't have one there may be no way to make this work.

**Comment by pivusan** [comment]
thank you for answer. i do not know. i use standard preference. wayland default in ubuntu 22.04
there is the possibility add to radiotray-ng the functionality gnome radio with icon:
![изображение](https://user-images.githubusercontent.com/20986405/212495772-ac9c5fdb-359c-42e0-ad8e-b1ffc0c8dd38.png)

**Comment by HeidrHH** [comment]
Radiotray v0.2.8-2-g7fe8c4a

Operating System: TUXEDO OS 2 (Ubuntu 22.04.2 jammy)
https://www.tuxedocomputers.com/en/TUXEDO-OS_1.tuxedo#
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.2.0-10007-tuxedo (64-bit)


It would be a wish of me too that it would be possible to copy song title and artist to clipboard with a simple mouse click.

Radiotray is still my favorite app to stream radio from internet.

**Comment by ebruck** [comment]
I know this isn't a fix, but you could write a script and assign it to a hotkey that runs this command:

`wl-copy $(rtng-dbus get_player_state | jq -r '[.title,.artist] | @text')`
