### ISSUE TITLE
Tray icon not available in Fedora 37

### ISSUE THREAD

**Issue by reinhapa** [ebruck/radiotray-ng#192]
After installing `radiotray-ng-0.2.8-5.fc37.x86_64` the application seems to be running as the player state states hows: 

`qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state`

returns:

```
{
	"artist" : "",
	"bitrate" : "",
	"codec" : "",
	"group" : "",
	"image" : "radiotray-ng-notification",
	"mute" : false,
	"state" : "stopped",
	"station" : "",
	"title" : "",
	"url" : "",
	"volume" : "100"
}
```

But there is no tray icon 🙁

**Comment by ebruck** [comment]
Please have a look at https://github.com/ebruck/radiotray-ng/issues/176

**Comment by reinhapa** [comment]
@ebruck thanks for the hint, I somehow missed this in the README....
