### ISSUE TITLE
config file not preserving settings

### ISSUE THREAD

**Issue by kdeneve** [ebruck/radiotray-ng#194]
Hi All

i am using RTNG on a brand new Linux Mint 21.1 distro
I have seen that whenever I make a change in the config file, after a restart of RTNG the settings are always at default again
For bypassing this behavior i changed the ownership of the config file to root

The startup is not changing the config file anymore, but notifications are still generated when for example I reload the bookmarks.
What I am trying to disable is  the general notification in this file:  ~/.config/radiotray-ng/radiotray-ng.json
Someone any clue?

Regards
Kurt

**Comment by ebruck** [comment]
@kdeneve make sure you exit radiotray-ng before editing the config file.

**Comment by kdeneve** [comment]
Hi ebruck

Thanks for your reply. The config file was saved successfully now thanks to to your suggestion.
However, with all notification keys on false in the config file, I still receive notifications when for example I reload the favorites list ...

regard
Kurt

**Comment by MrHappy** [comment]
If I add configlines, they are removed when I open and close radiotray.
