### ISSUE TITLE
Displaying the menu

### ISSUE THREAD

**Issue by thespiderofanotherusername** [ebruck/radiotray-ng#195]
Let Radiotray-NG display its menu, as if being clicked on its tray icon, via dbus, command-line option and/or media key binding. This feature would make possible to select any station, not only that in the same group, AND with the keyboard ONLY. (Those of us who consider reaching sideways to find a mouse a waste of time and love keyboard shortcuts would certainly love this feature as well.)
Thanks & Regards, the.spider

**Comment by ebruck** [comment]
@thespiderofanotherusername this is not a feature that I'm considering.  If you are using X then perhaps you could tie this to a hotkey. You will have to find the coordinates of the tray icon.

`xdotool mousemove 3610 10 click 3 # coordinates on my 4K monitor`

Have a look at this thread as it may give you some ideas if you're on wayland.
[https://superuser.com/questions/1032270/wayland-alternative-for-xorgs-xdotool](https://superuser.com/questions/1032270/wayland-alternative-for-xorgs-xdotool)
