### ISSUE TITLE
Remove Hidden=false from .desktop files

### ISSUE THREAD

**Issue by petsam** [ebruck/radiotray-ng#196]
As the relevant [XDG protocol explains](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html), the Hidden key is not required (Table 2, column _REQ?_) in a .desktop file, unless the intention is to _hide_ the entry from menus, or autostart mechanisms (Hidden=true).

So, Hidden=false has no sensible meaning in an initial installation, neither in menu nor in autostart directories.
[app](https://github.com/ebruck/radiotray-ng/blob/84648e8d06fd2676f28dc671d5748d4032094ddf/data/radiotray-ng.desktop#L5)  [bookmark editor](https://github.com/ebruck/radiotray-ng/blob/84648e8d06fd2676f28dc671d5748d4032094ddf/data/rtng-bookmark-editor.desktop#L5)

I came into this, when parsing `.desktop` files, and radiotray-ng files were the only ones with such a key=value entry on my system.

As I checked, it was like this from the first commit, probably from the previous developers.

Thanks for maintaining this nice application!

**Comment by ebruck** [comment]
Thanks for reporting this issue.
