### ISSUE TITLE
Station urls old and new fail to play

### ISSUE THREAD

**Issue by GrulClatu** [ebruck/radiotray-ng#197]
Hello friends,

I am running radiotray-ng on Debian 12.0
Radiotray-NG is at version v0.2.8 (v0.2.8-1-g0bbc344)

URLs from stations have changed or simply don't load anymore. I restarted my system to be sure it is a permanent error.

Changed urls, e.g Deutschlandradio Kultur:
https://st02.sslstream.dlf.de/dlf/02/128/mp3/stream.mp3?aggregator=web

Urls from Somafm that don't load anymore, e. g.:
https://somafm.com/u80s256.pls

rtng tells
Error
Failed to download playlist

All can be played using mpv cli or webbrowser.

From the stations shipped with rtng, some fail, too, I have checked now:
Smooth Jazz - keeps being silent, no artist or title information
Reggaeton 24/7 - Internal data stream error
181.FM Classic Hits - Die Art des Datenstroms konnte nicht ermittelt werden
CINEMIX - Das scheint eine Textdatei zu sein
WQXR - Die Art des Datenstroms konnte nicht ermittelt werden
BBC Radio 3 - Failed to download playlist
AM600 Conyers OTR - Das scheint eine Textdatei zu sein
Rumsey Retro Radio - Das scheint eine Textdatei zu sein
WNAR-AM Radio - Failed to download playlist
Lounge Radio - Title tells Playing, but no song, keeps being silent
Somafm Live - Failed to download playlist
Highway 181 - Die Art des Datenstroms konnte nicht ermittelt werden
Country 108 - Das scheint eine Textdatei zu sein
DubStep Beyond - Das scheint eine Textdatei zu sein
hard-fm.de - Failed to download playlist

Is this a situation solely to me or can you verify?

**Comment by ebruck** [comment]
That's odd @GrulClatu, those links work fine for me.

**Comment by GrulClatu** [comment]
> That's odd @GrulClatu, those links work fine for me. You may be missing some codecs.

Thanks for answering and telling that this my local problem. I'll try to investigate it. If lucky I will tell, else I will close this issue.

**Comment by GrulClatu** [comment]
Ok, I found out, that my bookmarks.json is outdated for some of the stations.
And that I have a problem  with radiotray-ng and gtk:
`(radiotray-ng:437535): Gtk-CRITICAL **: 09:48:33.944: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
[2023-04-10 10:06:39.368925] [0x00007fac0ec14ac0] [info]    (bookmarks.cpp:75) - saving: /home/user/.config/radiotray-ng/bookmarks.json
`
It lead RTNG to not reading the bookmarks file even when telling so.
So this is my problem, indeed.
Thanks for your attention, ebruck.
So I close this issue.
Keep on rocking radiotray-ng!
