### ISSUE TITLE
new feature - radiotray-ng on shell terminal 

### ISSUE THREAD

**Issue by catafest** [ebruck/radiotray-ng#198]
will be great if this software will have the option to run into a terminal area without a G.U.I.  environment like a Gnome, KDE, or something else.
maybe using the ncurses library can be a good idea .

**Comment by ebruck** [comment]
I originally was going to create an ncurses front-end and had "something" working, but decided it wasn't anything that I'd be interested in using.

This is as far as I got.
![image](https://github.com/ebruck/radiotray-ng/assets/1168556/98c74966-47fe-41e0-a784-605ef2e1513d)
