### ISSUE TITLE
32 bit binary(deb) ?

### ISSUE THREAD

**Issue by khurshid-alam** [ebruck/radiotray-ng#2]
Can we have 32 bit binary for deb?

Thanks.

**Comment by ebruck** [comment]
I'd like to target 16.04 for that. Is this the release you are using?

**Comment by khurshid-alam** [comment]
Yes.

**Comment by khurshid-alam** [comment]
@ebruck 

Thanks for quick fix. 

Now that it got fixed will it be possible to have a PPA for easy installation and updates? If yes, then I can help you with that.
