### ISSUE TITLE
Wrong separators in menu

### ISSUE THREAD

**Issue by TomaszGasior** [ebruck/radiotray-ng#20]
You are using wrong separators in tray menu. Instead of GtkMenuItem with empty label you should use GtkSeparatorMenuItem. See screenshots below. (nm-applet context menu on second screenshot).

![screenshot1](https://user-images.githubusercontent.com/1395027/30005537-05c717e4-90e5-11e7-9b60-7ea90b218fed.png)
![screenshot2](https://user-images.githubusercontent.com/1395027/30005538-05cd620c-90e5-11e7-9cf9-ba1ef92b76e7.png)

**Comment by ebruck** [comment]
I'll have a look, but I'm using the C API. There is a config option to turn off separators if you want.

**Comment by ebruck** [comment]
I just tried gtk_separator_menu_item_new(), but I get the same result as before. What app are you comparing Radiotray-NG to in your screenshot?

**Comment by ebruck** [comment]
Perhaps it's theme related? Can you build and run my v0.1.8-dev branch?

**Comment by TomaszGasior** [comment]
— Problem is not related to theme. Adwaita theme is affected also.
— I didn't test v0.1.8-dev but I changed `gtk_menu_item_new()` to `gtk_separator_menu_item_new()` in `appindicator_gui.cpp`. It works, see screenshot. I see that you did the same in v0.1.8-dev. So problem is solved.
https://i.imgur.com/EruNSvf.png

**Comment by ebruck** [comment]
@TomaszGasior Thanks for testing it!
