### ISSUE TITLE
AUR build script error

### ISSUE THREAD

**Issue by CHJ85** [ebruck/radiotray-ng#201]
I'm trying to install Radiotray-ng on Manjaro.
The AUR script does not work.
ERROR. PKGBUILD: line 23: patch: command not found.

**Comment by ebruck** [comment]
Looks like you need to install the patch utility.

**Comment by CHJ85** [comment]
Thanks. I did that, even though Pamac does that automatically. There's an issue with the build script.
But now it says that Cmake was unable to find a build program corresponding to "Unix Makefiles" CMAKE_MAKE_PROGRAM is not set.
CMAKE_CXX_COMPILER not set, after EnableLanguage.

**Comment by CHJ85** [comment]
UPDATE! I figured out what the problem was.
Turns out it wasn't the installation script after all.
I somehow didn't have the "base-devel" package installed.
I'm sorry for thinking the problem was on your end.
