### ISSUE TITLE
Update Needed On IHR Stream for 2023

### ISSUE THREAD

**Issue by LinuxMint20** [ebruck/radiotray-ng#209]
I know this is an old topic, I have been researching it. It's all over here and (https://askubuntu.com/questions/470269/how-do-i-add-iheartradio-stations-to-radio-tray)

Im opening this here because I can't even open up an account on Ask Ubuntu or Stack Exchange. Frustrating. So it was here or reddit.

I am able to extract a link from the Firefox Inspector Panel (I am attaching a screenshot), and filtering out everything but Network links and Media, as you can see below. These links, and there are many of them, only play little excerpts of songs. A few seconds, just enough to get your hopes up, then Radiotray stops playing and won't start again until you select another station.

![ihrstream](https://github.com/ebruck/radiotray-ng/assets/80086659/bb67e3ff-935a-431f-ba65-d5c298e8f913)

This is the link I was able to get from the highlit entry.

[https://custom-hls.iheart.com/ihr-ingestion-pipeline-production-fuga/encodes/Jan17/012817/curb/1211960416-0080688555269/0080688555269_1_06_mp3_vbr_320.m4a-25.aac](url)

**Comment by ebruck** [comment]
These are part of an HTTP live stream. You need to find the playlist URL which ends in .m3u8.

https://en.wikipedia.org/wiki/HTTP_Live_Streaming

**Comment by LinuxMint20** [comment]
I extracted the m3u8 playlist, but they've gotten smarter. It only streams for one song. May I ask how YOU do it, assuming you still do? Im uploading some more pics to illustrate the process.

![M3U8 Playlist IHR](https://github.com/ebruck/radiotray-ng/assets/80086659/c122fb52-cbdc-4e87-96ae-2f3819399b2f)
![IHR Null Link](https://github.com/ebruck/radiotray-ng/assets/80086659/b03265b5-2c5a-4870-9744-dee8772157c4)

![IHR Null Link](https://github.com/ebruck/radiotray-ng/assets/80086659/b03265b5-2c5a-4870-9744-dee8772157c4)
