### ISSUE TITLE
Show title/artist persistently in tray next to app icon?

### ISSUE THREAD

**Issue by thebordella** [ebruck/radiotray-ng#212]
Amazing - finally found the radio player I want for Linux. Simple, unobstrusive, easily accessible. I compiled source for Ubuntu 23.10 and it works great. But...

Is there any way to show the title/artist not just in the dropdown menu but in the tray area itself, so it is always visible? I have plenty of horizontal real estate available. What would be the best way to go about this? Through the source code? Some kind of dbus scripting? Would be a great enhancement to an otherwise excellent app. Thanks!

**Comment by ebruck** [comment]
@thebordella it certainly can be done. Here's a quick hack:

![image](https://github.com/ebruck/radiotray-ng/assets/1168556/c2c7e827-3c3b-44bf-8cb7-17eab3143035)
![image](https://github.com/ebruck/radiotray-ng/assets/1168556/d94bab30-be0e-437b-a421-82d0d6307ef9)
![image](https://github.com/ebruck/radiotray-ng/assets/1168556/adac7925-744c-4056-ae45-879183073028)

I'll have to play around with it some more to properly add updates/blanking etc.  I'll probably add a configurable max length to prevent it from being WAY too long.

**Comment by thebordella** [comment]
@ebruck 

Thanks for the quick reply - those 'quick hacks' look great! Exactly what I had in mind. I'll look out for an update or patch to the source...

**Comment by ebruck** [comment]
@thebordella please checkout my **v0.2.9-dev** branch which has this new feature.

There are three new config entries for it. Please see the README.md file for defaults etc. Also, do not edit the config while radiotray-ng is running or you will lose your changes.

Please let me know how it works for you and if you find any bugs.

**Comment by thebordella** [comment]
@ebruck This is great! I built the 0.2.9-dev branch and it works exactly as described. One small question - what controls the color of the artist/title text in the tray? On my system that text is black although the other items in my tray are an off-white.

![Snapshot_2024-01-04_08-38-00](https://github.com/ebruck/radiotray-ng/assets/4489495/fa065363-d853-4ea5-9b8f-d661bf9811bc)

**Comment by ebruck** [comment]
In Gnome I believe it's controlled by the theme you are using. It appears you may be using KDE? If so then it may be that the the appindicator support is not quite complete. I've seen this before. #159, #68

**Comment by thebordella** [comment]
@ebruck Thanks. My screenshot is actually from Ubuntu Budgie, which I believe is based on Gnome. I can experiment with theme settings. Definitely not a big deal!
