### ISSUE TITLE
Trying to install... gstreamer1.0-dev wont install

### ISSUE THREAD

**Issue by bonelifer** [ebruck/radiotray-ng#213]
Xubuntu 22.04

radio.sh
```
# You should make sure these are installed before trying to build RadioTray-NG on Ubuntu
#
# sudo apt install libayatana-appindicator3-dev libwxgtk3.0-gtk3-dev libwxgtk3.0-gtk3-0v5 lsb-release libcurl4-openssl-dev libjsoncpp-dev libxdg-basedir-dev libnotify-dev libboost-filesystem-dev libboost-log-dev libboost-program-options-dev libgtk-3-dev libnotify-dev lsb-release libbsd-dev libncurses5-dev libglibmm-2.4-dev cmake

# Can't install: libgstreamer1.0-dev 
echo "Hello"
# On initial RUN, run these five commands before running this script
#mkdir ~/CODE/
#cd ~/CODE/
#git clone https://github.com/ebruck/radiotray-ng.git
#cd radiotray-ng
#mkdir build

cd ~/CODE/radiotray-ng/
mkdir -p build
git pull
cd build

cmake .. -DCMAKE_BUILD_TYPE=Release
make package
filename=$(find . -maxdepth 1 -name radiotray-ng*.deb | sed -e 's/.\///g')
#echo $filename
sudo dpkg -i ./$filename
sudo apt-get install -f

```
trying to install libgstreamer1.0-dev
```
❯ sudo apt install libgstreamer1.0-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgstreamer1.0-dev : Depends: libgstreamer1.0-0 (= 1.20.3-0ubuntu1) but 1.20.5-1~20.04.sav1 is to be installed
                       Depends: gir1.2-gstreamer-1.0 (= 1.20.3-0ubuntu1) but 1.20.5-1~20.04.sav1 is to be installed
E: Unable to correct problems, you have held broken packages.

```
❯ bash radio.sh 
Already up to date.
-- wxWidgets: Found gtk3 version, using it.
-- Checking for one of the modules 'gstreamer-1.0'
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:890 (message):
  None of the required 'gstreamer-1.0' found
Call Stack (most recent call first):
  CMakeLists.txt:48 (pkg_search_module)

Building version: 0.2.8 for ubuntu 22.04 -- DEB packaging...
-- Configuring incomplete, errors occurred!
See also "/home/william/CODE/radiotray-ng/build/CMakeFiles/CMakeOutput.log".
make: Nothing to be done for 'package'.
dpkg: error: archive './' is not a regular file
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
```

**Comment by ebruck** [comment]
@bonelifer not sure what is going on for you, but on Ubuntu 22.04 I had no problems following these instructions.
https://github.com/ebruck/radiotray-ng#to-build-on-ubuntu

One thing I do see is that your apt install doesn't include ' libgstreamer1.0-dev'.
