### ISSUE TITLE
Stream could not be played (Antenne Vorarlberg)

### ISSUE THREAD

**Issue by Jambola77** [ebruck/radiotray-ng#218]
I am not able to get the streams from Antenne Vorarlberg working:
e.g. https://web.radio.antennevorarlberg.at/av-chillout/stream/mp3

All streams are listet here:
https://www.antennevorarlberg.at/aktuelles/meldungen/neu-unsere-aktuellen-webradio-streaming-urls/

When I try to turn on an URL, the icon in the tray bar becomes white for a second, but nothing happens.

**Comment by Jambola77** [comment]
Error message: 
[0x000076b586e77d00] [debug] (notification.cpp:63) - notify: Error, Internal data stream error., radiotray-ng-notification

**Comment by ebruck** [comment]
For now you can try the same URL using http instead of https which seems to work for me.

**Comment by ebruck** [comment]
Something about the stream gstreamer doesn't like:

```
$> gst-play-1.0 "https://web.radio.antennevorarlberg.at/av-chillout/stream/mp3"
Press 'k' to see a list of keyboard shortcuts.
Now playing https://web.radio.antennevorarlberg.at/av-chillout/stream/mp3
ERROR Internal data stream error. for https://web.radio.antennevorarlberg.at/av-chillout/stream/mp3
ERROR debug information: ../libs/gst/base/gstbasesrc.c(3132): gst_base_src_loop (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
streaming stopped, reason error (-5)
Reached end of play list.
```

**Comment by ebruck** [comment]
@Jambola77 I found the issue. My "direct stream" detection did not take into account what the mime type is. If you can build from source then use my v0.2.9-dev branch.

**Comment by ebruck** [comment]
r

**Comment by Jambola77** [comment]
@ebruck 
When trying to install the package it complains about a library:

Entpacken von radiotray-ng (0.2.9-dev) über (0.2.8) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von radiotray-ng:
 radiotray-ng hängt ab von libjsoncpp1; aber:
  Paket libjsoncpp1 ist nicht installiert.

I use linux mint 21.3 (virginia/jammy), I saw in https://github.com/ebruck/radiotray-ng/issues/204 that this issue was already fixed?

**Comment by ebruck** [comment]
@Jambola77 please pull the latest from my dev branch. I added 23.1 to the packaging script.

**Comment by Jambola77** [comment]
Hi @ebruck, 
thanks for your quick support! I had to change 23.1 to 21.3 and then I was able to install flawlessly the package.
Music works again like a charm :-)

**Comment by ebruck** [comment]
Whoops! I knew I should of double checked that. I'll fix it ASAP. 🤦‍♂️
