### ISSUE TITLE
reverse menu on bottom panels

### ISSUE THREAD

**Issue by atommixz** [ebruck/radiotray-ng#22]
I have usability issue, cause my tray is at the bottom. It must be reversed on bottom panels. U can just create option in preference.

**Comment by ebruck** [comment]
Something like this?

![reversed_menu1](https://user-images.githubusercontent.com/1168556/30007460-05fada32-90c4-11e7-8ec4-2d410ca6e4aa.png)

**Comment by atommixz** [comment]
yes

**Comment by ebruck** [comment]
@atommixz if possible please test my v0.1.8-dev branch.
