### ISSUE TITLE
Package cannot be installed (libjsoncpp1 and libwxgtk3.0-gtk3-0v5 not found)

### ISSUE THREAD

**Issue by Jambola77** [ebruck/radiotray-ng#222]
After making the package the installer raises some errors:
```

dpkg: Abhängigkeitsprobleme verhindern Konfiguration von radiotray-ng:
 radiotray-ng hängt ab von libjsoncpp1; aber:
  Paket libjsoncpp1 ist nicht installiert.
 radiotray-ng hängt ab von libwxgtk3.0-gtk3-0v5; aber:
  Paket libwxgtk3.0-gtk3-0v5 ist nicht installiert.
```

I cannot find libjsoncpp1, it seems to be deprecated. I use latest Linux Mint.

**Comment by Jambola77** [comment]
The Problem with libjsoncpp1 can be solved according to https://bugs.launchpad.net/ubuntu/+source/libjsoncpp/+bug/1928695:

In CPackConfig.cmake the entry libjsoncpp1 must be replaced by libjsoncpp-dev.

set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6, libbsd0, libcurl4, **libjsoncpp-dev**, libxdg-basedir1, libnotify4, python3, python3-lxml, libglibmm-2.4-1v5, libboost-filesystem1.83.0, libboost-system1.83.0, libboost-log1.83.0, libboost-thread1.83.0, libboost-program-options1.83.0, libgstreamer1.0-0, libappindicator3-1, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, libwxgtk3.0-gtk3-0v5")

**Comment by ebruck** [comment]
@Jambola77 could you please try this patch?

> --- a/package/CMakeLists.txt
> +++ b/package/CMakeLists.txt
> @@ -55,7 +55,7 @@ if (LSB_RELEASE_EXECUTABLE)
>              string(REPLACE "libjsoncpp1" "libjsoncpp24" CPACK_DEBIAN_PACKAGE_DEPENDS ${CPACK_DEBIAN_PACKAGE_DEPENDS})
>          endif()
>  
> **-        if (${RELEASE} STREQUAL "22.04" OR ${RELEASE} STREQUAL "23.04" OR ${RELEASE} STREQUAL "23.10" OR ${RELEASE} STREQUAL "21.3")**
> **+        if (${RELEASE} STREQUAL "22.04" OR ${RELEASE} STREQUAL "23.04" OR ${RELEASE} STREQUAL "23.10" OR ${RELEASE} STREQUAL "21.3" OR ${RELEASE} STREQUAL "22")**
>              string(REPLACE "libjsoncpp1" "libjsoncpp25" CPACK_DEBIAN_PACKAGE_DEPENDS ${CPACK_DEBIAN_PACKAGE_DEPENDS})
>              string(REPLACE "libappindicator3-1" "libayatana-appindicator3-1" CPACK_DEBIAN_PACKAGE_DEPENDS ${CPACK_DEBIAN_PACKAGE_DEPENDS})
>          endif()
> @@ -86,7 +86,7 @@ if (LSB_RELEASE_EXECUTABLE)
>          endif()
> 
> **-        if (${RELEASE} STREQUAL "23.04" OR ${RELEASE} STREQUAL "23.10")**
> **+        if (${RELEASE} STREQUAL "23.04" OR ${RELEASE} STREQUAL "23.10" OR ${RELEASE} STREQUAL "22")**
>              message(STATUS "Official packaging assumes gtk3 dependency for 'rtng-bookmark-editor'")
>              string(REPLACE "libwxgtk3.0-gtk3-0v5" "libwxgtk3.2-1" CPACK_DEBIAN_PACKAGE_DEPENDS ${CPACK_DEBIAN_PACKAGE_DEPENDS})
>          endif()
