### ISSUE TITLE
restore the state

### ISSUE THREAD

**Issue by atommixz** [ebruck/radiotray-ng#23]
It should restore the state "Turn on / Turn off" after restart

**Comment by ebruck** [comment]
If you like for Radiotray-NG to start playing on startup there is a new --play command line argument.

**Comment by ebruck** [comment]
I don't think this is something that is needed. Radiotray-NG already saves the last station and group information. If someone wants to have it play automatically on startup then they can add the new --play command line option to the desktop file: /etc/xdg/autostart/radiotray-ng.desktop #
