### ISSUE TITLE
mouse clicks

### ISSUE THREAD

**Issue by atommixz** [ebruck/radiotray-ng#25]
left click on ico should on/off radio, right click - popup menu

**Comment by ebruck** [comment]
I'm sorry appindicators don't work that way.

**Comment by guzzard** [comment]
Hi @ebruck,

I would also like a behavior to use only one mouse click (left, or middle as original radiotray) to turn on/off playback. 50% the work compared to now with two mouse clicks.

I searched but I cannot find the design guidelines for appindicators stating that this behavior is not OK. Where can I find the design guidelines? Checked the Gnome website, Ubuntu website, and searched Google..

Gnome doesn't want any status menu at all, very strange since there are meny applications that only use a status menu and doesn't even have a main window.

On the Ubuntu site i found [this](https://wiki.ubuntu.com/CustomStatusMenuDesignGuidelines#What_should_be_in_a_custom_status_menu.3F):
![screenshot-area-2017-09-12-102419](https://user-images.githubusercontent.com/9007314/30315542-9dfa7b4e-97a4-11e7-8f00-fb094379b5a8.png)

So the Ubuntu guys seem OK with having custom actions based on single and double clicking on the status icon?

**Comment by ebruck** [comment]
It is my understanding that the appindicator library does not emit any of the click events. I've certainly never seen it in all the years I've been fiddling with appindcators. I just tried to register a handler for button-press-event (using appindcator extension), but it does not succeed. I'd welcome a patch if someone can make work. The alternative is to use a hotkey and the new dbus interface or the media keys.

**Comment by guzzard** [comment]
Hi @ebruck,

Looks like at least middle mouse button click should be possible.

From [askubuntu](https://askubuntu.com/questions/224709/how-to-run-an-action-when-clicking-on-an-appindicator):
![screenshot-area-2017-09-13-115755](https://user-images.githubusercontent.com/9007314/30371439-da4a021e-987a-11e7-95ab-6706035eafe2.png)

Link to [API ref](https://developer.ubuntu.com/api/devel/ubuntu-13.10/python/AppIndicator3-0.1.html).

Also see [this solution example](https://www.linuxquestions.org/questions/ubuntu-63/how-to-add-the-middle-click-functionality-to-the-appindicator-4175608994/).

**Comment by ebruck** [comment]
Did this work using the gnome appindicator extension?

**Comment by guzzard** [comment]
Hi @ebruck,

Did some investigating on this..

In GNOME Shell with the [appindicator extension](https://github.com/ubuntu/gnome-shell-extension-appindicator) installed:
- single click (left/middle/right): brings up the appindicator menu
- double click (left/middle/right): executes the "secondary_activate_target" if enabled in the application

In Cinnamon with appindicator support enabled:
- left single click: brings up the appindicator menu
- middle single click: does nothing
- right single click: brings up the menu for the cinnamon system tray applet

Double clicking in Cinnamon just shows and quickly hides the menus again.

To enable the "secondary_activate_target" to start/stop the currently selected radio (if supported by the desktop environment) only one line of code is needed:
```cpp
void AppindicatorGui::build_action_menu_item()
{
    this->action_menu_item = gtk_menu_item_new_with_label("action");
    gtk_menu_shell_append(GTK_MENU_SHELL(this->menu), this->action_menu_item);
    gtk_widget_show(this->action_menu_item);

    g_signal_connect(G_OBJECT(this->action_menu_item), "activate", G_CALLBACK(on_action_menu_item), gpointer(this));

    // this line:
    app_indicator_set_secondary_activate_target(this->appindicator, this->action_menu_item);

    this->update_action_menu_item(STATE_STOPPED);
}
```

**Comment by ebruck** [comment]
Thanks for digging into these issues. I'll add this to my latest dev branch.

**Comment by ebruck** [comment]
Strange... doesn't work for me. The menu appears and disappears. What version of gnome and the appindicator extension are you using?

**Comment by ebruck** [comment]
Works on Unity.

**Comment by guzzard** [comment]
Hi @ebruck,

Works great for me.

![output2](https://user-images.githubusercontent.com/9007314/30421716-e7e25606-993d-11e7-9d49-92e8d7af4631.gif)

GNOME Shell 3.24.3
gnome-shell-extension-appindicator v20 (metadata.json says version 21 when installed from extensions.gnome.org, but it is v20.. I confirmed with Meld)

**Comment by ebruck** [comment]
What distro are you using?  I'm using 17.04, but am still on gnome shell 3.24.2.

**Comment by guzzard** [comment]
Arch Linux, fully updated

**Comment by guzzard** [comment]
@ebruck did a quick test on Ubuntu GNOME with GNOME Shell 3.24.0. Double clicking did not work for me either.

When double clicking these error messages could be seen in the journal:
```
Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'Activate'
Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'Activate'
Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'Activate'
Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'Activate'
```

So I think that it must be an issue that was fixed recently since it's working fine for me?

**Comment by ebruck** [comment]
Here's what went into 3.24.3:

> git log 3.24.2..3.24.3 --oneline
ecea0218f (tag: 3.24.3) Bump version to 3.24.3
3478715e6 padOsd: Disallow help/switch monitor actions on rings/strips
cb6d9c927 padOsd: Implement edition of actions for rings/strips
7f693ed2c padOsd: strengthen ring/strip label creation
44908cf47 padOsd: Refactor function setting label after edition into separate function
7db7b7dcb shellDBus: Avoid access to undefined properties
a8b457b52 dateMenu: Set _delegate on non-menu-item menu child
cd678d86e notificationDaemon: Avoid access to undefined property
384ef7e10 calendar: Fix access to undefined property
451c753e4 windowManager: Fix a warning
ebc74957c layout: Skip strut computation in the no-monitor case
70f1f2d7b layout: Range-check index before array lookup
1be2102d2 ibusManager: Fix a warning
114f37175 history: Fix bogus return value
363d35a3e panel: Fix a JS warning
26433c2cb remoteMenu: Add actionGroup accessor
db81ef3e9 dash: Fix some JS warnings
091fb4ba2 Don't use 'undefined' as boolean
54891a4cd Initialize properties in _init()
31c9d2cf7 system: Emulate click action button release
1b8bba559 Fix translation headers
180a89758 notificationDaemon: Fix fallback icon names
95dba9304 st: Don't try to create shadow for empty texture
35eddb3df util: Force text direction of time strings
aa08bd75d portalHelper: Fix auth URI not being passed to window
d104ebf61 portalHelper: Don't go through proxies for captive portals
e7ad9d721 Update Turkish translation
35e6a3198 tests: Update markup test for function moved to messageList
4c1467196 Update Serbian Latin translation
732972121 Update Serbian translation
946ff3b38 Update German translation
0c584182d Fix bashism in autogen.sh

**Comment by guzzard** [comment]
@ebruck downgraded my gnome-shell package to 3.24.2 and tested and it works for me in that version as well, so I have no idea what's going on.. perhaps the issue is caused by something in another gnome-* package which I did not downgrade etc.. or perhaps DBus related? No idea.. but it works perfectly fine for me at least :smile:

**Comment by ebruck** [comment]
running dbus-monitor:

method call time=1505439707.523144 sender=:1.530 -> destination=:1.202 serial=1171 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.kde.StatusNotifierItem; member=Activate
   int32 0
   int32 0
error time=1505439707.523360 sender=:1.202 -> destination=:1.530 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=1171
   string "No such method 'Activate'"

**Comment by atommixz** [comment]
I need install 32 pks for gnome-shell-extension-appindicator. 
I have installed libappindicator-gtk3 but behavior absolutely the same as before. 
Version from v0.1.8-dev - v0.1.7-3-g7531eeb

**Comment by atommixz** [comment]
the best way would be to use Qt or Gtk tray optional

**Comment by guzzard** [comment]
Hi @ebruck,

**Activate method is visible when checking in d-feet:**
![d-feet](https://user-images.githubusercontent.com/9007314/30472905-9acfdb4c-99fe-11e7-88ed-2cb49beaf4e9.png)

**dbus-monitor when i double click to start radio:**
```
method call time=1505462507.451121 sender=:1.90 -> destination=:1.158 serial=1191 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=Event
   int32 0
   string "opened"
   variant       int32 0
   uint32 0
method call time=1505462507.451200 sender=:1.90 -> destination=:1.158 serial=1192 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=AboutToShow
   int32 0
method return time=1505462507.451373 sender=:1.158 -> destination=:1.90 serial=222 reply_serial=1191
method return time=1505462507.451379 sender=:1.158 -> destination=:1.90 serial=223 reply_serial=1192
   boolean false
method call time=1505462507.582253 sender=:1.90 -> destination=:1.158 serial=1193 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=Event
   int32 0
   string "closed"
   variant       int32 0
   uint32 0
method return time=1505462507.582490 sender=:1.158 -> destination=:1.90 serial=224 reply_serial=1193
method call time=1505462507.583360 sender=:1.90 -> destination=:1.158 serial=1194 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.kde.StatusNotifierItem; member=Activate
   int32 0
   int32 0
method call time=1505462507.583698 sender=:1.158 -> destination=:1.90 serial=225 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "radiotray-ng"
   uint32 1
   string "radiotray-ng-notification"
   string "Connecting"
   string "Radiotray-NG"
   array [
   ]
   array [
   ]
   int32 -1
method return time=1505462507.593719 sender=:1.90 -> destination=:1.158 serial=1195 reply_serial=225
   uint32 1
signal time=1505462507.593922 sender=:1.158 -> destination=(null destination) serial=226 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.kde.StatusNotifierItem; member=NewIcon
method call time=1505462507.594418 sender=:1.90 -> destination=:1.158 serial=1196 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.kde.StatusNotifierItem"
   string "IconPixmap"
method call time=1505462507.594437 sender=:1.90 -> destination=:1.158 serial=1197 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.kde.StatusNotifierItem"
   string "IconName"
error time=1505462507.594465 sender=:1.158 -> destination=:1.90 error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=1196
   string "No such property 'IconPixmap'"
method return time=1505462507.959218 sender=:1.158 -> destination=:1.90 serial=228 reply_serial=1194
method return time=1505462507.959227 sender=:1.158 -> destination=:1.90 serial=229 reply_serial=1197
   variant       string "radiotray-ng-on"
signal time=1505462507.959289 sender=:1.158 -> destination=(null destination) serial=230 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=ItemsPropertiesUpdated
   array [
      struct {
         int32 2
         array [
            dict entry(
               string "label"
               variant                   string "Turn Off "Groove Salad""
            )
         ]
      }
   ]
   array [
   ]
method call time=1505462508.347381 sender=:1.158 -> destination=:1.90 serial=231 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "radiotray-ng"
   uint32 1
   string "radiotray-ng-notification"
   string "Buffering"
   string "Groove Salad"
   array [
   ]
   array [
   ]
   int32 -1
method return time=1505462508.351960 sender=:1.90 -> destination=:1.158 serial=1198 reply_serial=231
   uint32 1
signal time=1505462510.620203 sender=:1.158 -> destination=(null destination) serial=232 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=ItemsPropertiesUpdated
   array [
      struct {
         int32 4
         array [
            dict entry(
               string "label"
               variant                   string "Playing"
            )
         ]
      }
   ]
   array [
   ]
```

**when i double click to stop radio:**
```
method call time=1505463016.838484 sender=:1.90 -> destination=:1.158 serial=1345 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=Event
   int32 0
   string "opened"
   variant       int32 0
   uint32 0
method call time=1505463016.838557 sender=:1.90 -> destination=:1.158 serial=1346 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=AboutToShow
   int32 0
method return time=1505463016.838742 sender=:1.158 -> destination=:1.90 serial=277 reply_serial=1345
method return time=1505463016.838775 sender=:1.158 -> destination=:1.90 serial=278 reply_serial=1346
   boolean false
method call time=1505463016.964596 sender=:1.90 -> destination=:1.158 serial=1347 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=Event
   int32 0
   string "closed"
   variant       int32 0
   uint32 0
method return time=1505463016.964805 sender=:1.158 -> destination=:1.90 serial=279 reply_serial=1347
method call time=1505463016.965870 sender=:1.90 -> destination=:1.158 serial=1348 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.kde.StatusNotifierItem; member=Activate
   int32 0
   int32 0
method call time=1505463016.966181 sender=:1.158 -> destination=:1.90 serial=280 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "radiotray-ng"
   uint32 1
   string "radiotray-ng-notification"
   string "Stopped"
   string "Groove Salad"
   array [
   ]
   array [
   ]
   int32 -1
method return time=1505463016.981437 sender=:1.90 -> destination=:1.158 serial=1349 reply_serial=280
   uint32 1
signal time=1505463016.983893 sender=:1.158 -> destination=(null destination) serial=281 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.kde.StatusNotifierItem; member=NewIcon
method return time=1505463016.983983 sender=:1.158 -> destination=:1.90 serial=282 reply_serial=1348
signal time=1505463016.984066 sender=:1.158 -> destination=(null destination) serial=283 path=/org/ayatana/NotificationItem/radiotray_ng/Menu; interface=com.canonical.dbusmenu; member=ItemsPropertiesUpdated
   array [
      struct {
         int32 4
         array [
            dict entry(
               string "label"
               variant                   string "Stopped"
            )
         ]
      }
      struct {
         int32 2
         array [
            dict entry(
               string "label"
               variant                   string "Turn On "Groove Salad""
            )
         ]
      }
   ]
   array [
   ]
method call time=1505463016.996805 sender=:1.90 -> destination=:1.158 serial=1350 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.kde.StatusNotifierItem"
   string "IconPixmap"
method call time=1505463016.996905 sender=:1.90 -> destination=:1.158 serial=1351 path=/org/ayatana/NotificationItem/radiotray_ng; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.kde.StatusNotifierItem"
   string "IconName"
error time=1505463016.996976 sender=:1.158 -> destination=:1.90 error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=1350
   string "No such property 'IconPixmap'"
method return time=1505463016.997062 sender=:1.158 -> destination=:1.90 serial=285 reply_serial=1351
   variant       string "radiotray-ng-off"
```

**Comment by guzzard** [comment]
@ebruck did a test now with a [Manjaro live cd/iso](https://downloads.sourceforge.net/manjarolinux/manjaro-gnome-17.0.4-stable-x86_64.iso) in Virtual Box. Double clicking works fine there as well (comes with GNOME Shell 3.24.3). So if you want to investigate further you can use Manjaro to quickly get an environment where it works.

1. Boot up Manjaro in Virtual Box
2. Install packages needed to build (git, gcc, cmake, libappindicator-gtk3, perhaps some other packages I forgot)
3. git clone v0.1.8-dev
4. Build and install
5. Install and enable the gnome-shell-extension-appindicator
6. Restart GNOME Shell (Alt+F2, r) just in case..
6. Start radiotray, start double clicking

**Comment by ebruck** [comment]
I installed the latest daily for 17.10 (gnome 3.26.0) in vbox and it did not work. Same missing "Activate" errors as before.

**Comment by guzzard** [comment]
@ebruck no idea what's going on with the Ubuntu based distros.. as I wrote before it didn't work in Ubuntu GNOME either.

Anyway, it ***does*** work in Arch and in Manjaro (which is based on Arch). Give the Manjaro live cd/iso a try. No installation to hard drive necessary.

**Comment by guzzard** [comment]
@ebruck did some more digging.. with the gnome-shell-extension-appindicator installed double clicking the appindicator icon triggers DBus to call the method "Activate", this works in Arch based distros, but not Ubuntu based distros.

I think [this patch](https://git.archlinux.org/svntogit/community.git/tree/trunk/improved-plasma.patch?h=packages/libappindicator) is the reason it works in Arch. The patch adds a method into the libappindicator library called "Activate" which is normally used in KDE I assume based on the naming of the patch. The "Activate" method is not available in the [source package](https://launchpad.net/ubuntu/zesty/+source/libappindicator) used by Ubuntu as far as I can tell.

My guess is that Unity triggers the "SecondaryActivate" method which is available in both the Ubuntu version as well as the Arch version of the libappindicator library. While the gnome-shell-extension-appindicator triggers the "Activate" method for some reason instead of the "SecondaryActivate" which seems to be the Ubuntu standard method?

Will try to modify the gnome-shell-extension-appindicator so that it triggers the "SecondaryActivate" method instead and see what happens.

**Comment by ebruck** [comment]
That's awesome! Thanks again for digging into this issue.

**Comment by ebruck** [comment]
I've been able to make it work by doing:

diff --git a/appIndicator.js b/appIndicator.js
index ea78f38..a8b27fb 100644
--- a/appIndicator.js
+++ b/appIndicator.js
@@ -199,7 +199,7 @@ const AppIndicator = new Lang.Class({
         // nor can we call any X11 functions. Luckily, the Activate method usually works fine.
         // parameters are "an hint to the item where to show eventual windows" [sic]
         // ... and don't seem to have any effect.
-        this._proxy.ActivateRemote(0, 0)
+        this._proxy.SecondaryActivateRemote(0, 0)
     },
 
     scroll: function(dx, dy) {
diff --git a/interfaces-xml/StatusNotifierItem.xml b/interfaces-xml/StatusNotifierItem.xml
index bf47abe..71b6df1 100644
--- a/interfaces-xml/StatusNotifierItem.xml
+++ b/interfaces-xml/StatusNotifierItem.xml
@@ -32,7 +32,7 @@
 
 
     
-    <method name="Activate">
+    <method name="SecondaryActivate">
         <arg name="x" type="i" direction="in"/>
         <arg name="y" type="i" direction="in"/>
     </method>

**Comment by guzzard** [comment]
@ebruck :+1: got that working here as well.. currently trying to implement a single middle mouse button click instead to activate the secondary action.. to not break the current behavior.. trying to find a way to trigger a close of the appindicator menu after a single middle mouse click.. right now the secondary action is triggered, but the menu remain open.

**Comment by ebruck** [comment]
That would be great. On Unity the middle click activates and does not show the menu.

**Comment by guzzard** [comment]
@ebruck [this pull req](https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/90)  adds the functionality to single middle mouse click the appindicator without opening the menu. Hopefully it's merged soon.

**Comment by ebruck** [comment]
@guzzard Just tried it out. Great work!
