### ISSUE TITLE
Radio tray icon not showing up in GS

### ISSUE THREAD

**Issue by monochromec** [ebruck/radiotray-ng#26]
Great to have a fork of the apparently dead RT project which is under active development - much appreciated! 

Unfortunately, the app icon is not showing in the application / systray area in gnome shell (although
topicons is installed as an extension). GS version is 3.24.2-0ubuntu0.1; let me know if you need more details.

**Comment by ebruck** [comment]
It works fine using the appindicator extension.

**Comment by monochromec** [comment]
Thanks for the hint - works like a charm
