### ISSUE TITLE
Sound output strange behavior

### ISSUE THREAD

**Issue by guzzard** [ebruck/radiotray-ng#27]
Hi @ebruck,

Sometimes the sound from radiotray-ng comes out of the wrong sound output. I have two sound cards which I switch between, one goes to speakers, the other goes to headphones.

If I switch sound output while radiotray-ng is playing something the output is changed correctly, however if I change the sound output while radiotray-ng is off it is not updated correctly, and radiotray-ng still uses the previous sound output while all other sound from the computer uses the selected sound output.

I can reproduce this very easily by doing this:
1. Start radiotray-ng playback, and stop it again (first time playback is started correct sound output is always used).
1. Change sound output in the sound settings.
1. Start some other audio playback. Sound comes out of selected sound output.
1. Start radiotray-ng playback. Sound from radiotray-ng comes out of previously selected sound output.

Are you able to reproduce this behavior, or is this something specific to my setup?

radiotray-ng 0.1.7
pulseaudio 11.0
alsa 1.1.4
kernel 4.9.41 and 4.12.12 (tested on both)

**Comment by ebruck** [comment]
@guzzard I am able to repro this. I'm by no means a gstreamer expert so it will take me some time to research this one.

**Comment by guzzard** [comment]
Hi @ebruck,

I'm sure there is a proper way to do this, but as a quick fix it looks like it would work to reinit (stop and start the gstreamer link) on play_next() to get it working.

I did a quick dirty test:
```cpp
bool Player::play_next()
{
	this->stop();

	this->gst_start(); // reinit gstreamer (in a ugly way without cleanup etc.)

	if (!this->current_playlist.empty())
```

This worked and correct sound output is always used when starting playback.

**Comment by ebruck** [comment]
@guzzard thanks for looking into it.

I believe I should be using:

https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-autoaudiosink.html

**Comment by ebruck** [comment]
It does work on Unity... no surprise there. :(

**Comment by ebruck** [comment]
@guzzard  seems to work now. Please give it a try.

**Comment by guzzard** [comment]
Hi @ebruck,

Yes, works great now! :+1:  :+1:
