### ISSUE TITLE
Popups do not disappear

### ISSUE THREAD

**Issue by baimafeima** [ebruck/radiotray-ng#28]
![radio](https://user-images.githubusercontent.com/23112309/30776886-ef3e51b6-a0ae-11e7-8ea9-1e7c4a241ee0.png)
radiotray-ng 0.1.6
The popup (see screenshot) indicating channel, artist and song always reappear after clicking them away. Is there any option to disable them in the settings? Is this already fixed in 0.1.7?

**Comment by ebruck** [comment]
Yes you can, but your particular issue is addressed in the next release. It's briefly buffering and the popup keeps showing up. I too have been hit with that one. ;-)

To turn off notification add the following option to your config file, but only after exiting.

"notifications" : false,

**Comment by ebruck** [comment]
Are you test the v0.1.8 branch?

**Comment by ebruck** [comment]
Commit 724b07f043259eaf0c23e0d60aa377d830217617  removed the final notification that we are playing, but the real problem is that buffer-size was set incorrectly. Fixed by this commit: 8f259a772e4a43bef36cb9ea3833b13a676e970c

I will revert the change I made in the next release.
