### ISSUE TITLE
Error building dev-0.1.8

### ISSUE THREAD

**Issue by Swipe650** [ebruck/radiotray-ng#29]
Hi,

Just tried building dev-0.1.8 using my Arch Linux PKGBUILD and get the following error. I did this the exactly same way I used to build dev-017 and 0.1.6 which always built successfully. Any ideas. Some reference to _error adding symbols: DSO missing from command line_

```
/usr/bin/ld: CMakeFiles/radiotray-ng.dir/main.cpp.o: undefined reference to symbol '_ZN5boost6detail12get_tss_dataEPKv'
/usr/lib/libboost_thread.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/radiotray-ng/CMakeFiles/radiotray-ng.dir/build.make:135: radiotray-ng] Error 1
make[1]: *** [CMakeFiles/Makefile2:132: src/radiotray-ng/CMakeFiles/radiotray-ng.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
This is my PKGBUILD I'm using:

```
pkgname=radiotray-ng
pkgver=0.1.8
pkgrel=1
pkgdesc="An Internet radio player for Linux"
arch=('i686' 'x86_64')
url="https://github.com/ebruck/radiotray-ng"
license=('GPL')
depends=('boost-libs' 'curl' 'gstreamer' 'jsoncpp' 'libappindicator-gtk2'
         'libbsd' 'libnotify' 'libxdg-basedir' 'glibmm' 'libappindicator-gtk3' 'glibmm')
makedepends=('cmake' 'boost' 'lsb-release')
optdepends=('python2-lxml: Convert radiotray bookmarks to radiotray-ng format')
options=('!libtool')
#source=("${pkgname}.tar.gz::https://github.com/ebruck/radiotray-ng/archive/v${pkgver}.tar.gz")

source=("${pkgname}.tar.gz::https://github.com/ebruck/radiotray-ng/archive/v${pkgver}-dev.tar.gz")

sha256sums=('b816f5b6e10277633d7935920d637c31d99f85c6fc2a740a97c76ef332c543db')

build() {
  cd "${srcdir}/${pkgname}-${pkgver}-dev"
  [ -d build ] && rm -r build
  mkdir build
  cd build

  cmake .. -DCMAKE_BUILD_TYPE=Release
  make
}

package() {
  cd "${srcdir}/${pkgname}-${pkgver}-dev/build"
  make DESTDIR="$pkgdir" install
}

```

**Comment by ebruck** [comment]
I believe it's the addition of libboost-program-options that is giving you problems. 
Have a look at this line for the latest changes:

https://github.com/ebruck/radiotray-ng/blob/08e56c7e1fe8d58f77db6528361e128b2695e896/debian/CMakeLists.txt#L25

**Comment by Swipe650** [comment]
That's strange as libboost-program-options.so is included in the Arch Linux [ boost-libs 1.65.1-1](https://www.archlinux.org/packages/extra/x86_64/boost-libs/files/) package which is set a dependency for radiotray-ng in my PKGBUILD file

**Comment by ebruck** [comment]
That's not enough to get it to link against it.

**Comment by ebruck** [comment]
It may be something else then.

**Comment by ebruck** [comment]
Can you try this change?

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0b72b5b..c8dfcbc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -36,7 +36,7 @@ list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR})
 # search for libs
 find_package(CURL      REQUIRED)
 find_package(PkgConfig REQUIRED)
-find_package(Boost     REQUIRED filesystem system log program_options)
+find_package(Boost     REQUIRED filesystem system log program_options thread)
 find_package(GMock)
```

**Comment by Swipe650** [comment]
That change allowed me to compile without any errors and successfully generated a deb. Please could you commit that change so I can use my PKGBUILD to build an arch package?

**Comment by Swipe650** [comment]
Thanks. I was now able to successfully build an Arch package. BTW you need to update the version number to 0.1.8 in 'About'

**Comment by ebruck** [comment]
I only do that when there's an official release. During dev you see the last version plus how many commits ahead it is along with the git hash used to create the binary.
