### ISSUE TITLE
Icon is the wrong size in xfce-panel

### ISSUE THREAD

**Issue by dflock** [ebruck/radiotray-ng#3]
I'm using the latest radiotray-ng and running Xubuntu 16.04.2 - using xfce as my Desktop Environment. I'm using xfce's panels and the radiotray-ng icon appears to be stretched, or the wrong size. It's the second icon from the right, just between the sound menu and network manager:

![screenshot_2017-02-17_11-12-33](https://cloud.githubusercontent.com/assets/47756/23079570/4fef6620-f502-11e6-98a4-d3919fc1f23e.png)

The icon in the notifications look fine:

![screenshot_2017-02-17_11-19-04](https://cloud.githubusercontent.com/assets/47756/23079751/1b6550bc-f503-11e6-953b-cb494e36979e.png)

I haven't changed radiotray-ng's config at all, so far.

If there's any more information I can provide to help debug, let me know.

Thanks!

**Comment by ebruck** [comment]
Looks like xfce isn't resizing the 256x256 image like Unity is doing. Next release I'll switch to a 24x24 and we'll see how it works for you.

**Comment by dflock** [comment]
Much better, thanks:

![screenshot_2017-02-18_16-25-22](https://cloud.githubusercontent.com/assets/47756/23097961/240adf62-f5f7-11e6-907c-bde247a09c72.png)

(The panel on this machine is set to semi-transparent, and has a Chrome window behind it)

Is there any way to customize the icon? Will it use an icon from the theme, if there's an appropriate one available?

**Comment by ebruck** [comment]
If you add an icon to some other theme then you'll want to run:  sudo gtk-update-icon-cache -f -t <theme-dir> so your desktop environment picks up your latest changes. You can see how I add them to hicolor, ubuntu-mono-dark & ubuntu-mono-light.  The icons Radiotray-NG uses are:

radiotray-ng-on
radiotray-ng-off
radiotray-ng-notification
