### ISSUE TITLE
[Debian: Xfce4-Desktop] Volume settings are lost when turning off station

### ISSUE THREAD

**Issue by Wasnix** [ebruck/radiotray-ng#32]
radiotray-ng lost the volume settings when turning off radio station or quit program. On my desktop the volume is much to high, so I decreased volume. But when turning off and on a station the volume is again much to high.

I edited config file and changed volume level to "10". The new level is displayed as "Volume: 10%" in popup menu. But the displayed level seems to have no effect on volume of played streams.

Via pulseaudio/pavucontrol it's possible to reduce the volume for radiotray-ng. That works as expected. But when turning on any station the volume level jumps back to inital high value.  I didn't find a way to decrease volume permanently.

My system is Debian/Stretch amd64 with Xfce4-Desktop, pulseaudio and some Gnome apps. Rhythmbox works fine. Dito gnome-music.

Output of pulseaudio `pacmd list-sink-inputs` :
----------
index: 2753
	driver: <protocol-native.c>
	flags: START_CORKED 
	state: RUNNING
	sink: 1 <alsa_output.pci-0000_04_06.0.analog-stereo>
	volume: front-left: 12065 /  18% / -44,10 dB,   front-right: 12065 /  18% / -44,10 dB
	        balance 0,00
	muted: no
	current latency: 116,00 ms
	requested latency: 96,00 ms
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Stereo
	resample method: (null)
	module: 10
	client: 1135 <Radiotray-NG>
----------

After turning off/on a station index and module number changed and volume level is much too high:
----------
    index: 2758
	driver: <protocol-native.c>
	flags: START_CORKED 
	state: RUNNING
	sink: 1 <alsa_output.pci-0000_04_06.0.analog-stereo>
	volume: front-left: 30419 /  46% / -20,00 dB,   front-right: 30419 /  46% / -20,00 dB
	        balance 0,00
	muted: no
	current latency: 116,00 ms
	requested latency: 96,00 ms
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Stereo
	resample method: (null)
	module: 10
	client: 1166 <Radiotray-NG>
----------

**Comment by ebruck** [comment]
There is only one way to change the volume levels so I'm at a lose as to what this could be. There however is a change coming that uses the proper output audio sink. Perhaps you can test my v0.1.8-dev branch?

**Comment by ebruck** [comment]
@Wasnix please test the latest release.

**Comment by ebruck** [comment]
@Wasnix any improvement?

**Comment by johnraff** [comment]
I can confirm this issue with 0.1.8 built today on Debian Stretch.

On first run, when a station is selected the volume is at max. If I turn it down to my preferred 60%, after changing the station, or temporarily stopping the current station, it reverts to 100%.

I also noticed that ~/.config/radiotray-ng/radiotray-ng.json is much simpler than the example on this site https://github.com/ebruck/radiotray-ng , so I copied in that and edited "volume-level" : 60
After that the volume no longer goes up to 100%, but it still jumps up to ~80%, so I have to bring it back down with my system volume control (volumeicon-alsa or pnmixer, via pulseaudio). 

The volume in radiotray-ng.json got rewritten to 50 (happens even if I change it back to 60), which is what the radiotray popup claims the volume to be, but the real volume has jumped to 80 again. Readjusting lasts only as long as the current station.

**Comment by ebruck** [comment]
Can you try enabling debug logging and post what is being written when the volume is adjusted?

Set:
debug-logging: true

The logs are in your ~/.config/radiotray-ng directory.

**Comment by ebruck** [comment]
@johnraff Did you build radiotray-ng from source?

**Comment by ebruck** [comment]
I've not been able to reproduce this.  I installed Debian Stretch in a VM and built radiotray-ng.
I had no problems adjusting volume levels and restoring them even after restarting radiotray-ng. The only oddity I found is that the volume level doesn't change if the menu is being displayed, but that's more of how well appindicator support is in xfce.

**Comment by johnraff** [comment]
OK short answers first.
I built radiotray-ng from source, on Debian Stretch in a VirtualBox VM.

Initial run: behaviour as reported by Wasnix, volume reverting to 100% after every new station or start/stop. I found the app had created a default radiotray-ng.json:
```
{
   "bookmarks" : "/home/john/.config/radiotray-ng/bookmarks.json",
   "last-station" : "Groove Salad",
   "last-station-group" : "Chill",
   "notification-verbose" : true,
   "notifications" : true,
   "split-title" : true,
   "volume-level" : 103
}
```
After pasting in the suggested config file, and adjusting volume-level to 60, the behaviour is now:
- App is off, check config file - unchanged. 
- Set master volume to 60 (with pnmixer).
- Start app, state "stopped": master vol. still 60, app popup menu also shows "Volume:60%".
- Start radio station: master volume jumps (at the "buffering" stage) to 84%, popup still shows "Volume:60%", config file volume also still at 60.
- Adjust master volume back to 60%: file and display volume both still at 60.
- Stop/start station, or choose new one: master volume back to 84%.
- Readjust master vol. back to 60.
- Close app: vol still at 60. Config file unchanged throughout, except for station names.

My feeling is that radiotray-ng should not be touching the master volume setting at all. 

**BUT** After writing the above, I checked Pulse Audio settings, and set `flat-volumes = no` in /etc/pulse/daemon.conf. *This fixes the issue.* 

There still might be scope for looking at how radiotray-ng interacts with PA though - the flat-volumes setting should not really be necessary to prevent radiotray-ng from resetting the master volume.

**Comment by ebruck** [comment]
There is nothing I can do. Found this old ticket that goes into a lot of details:

> * in non-flat volume model, application-specific volumes are relative to the device volume, which can be adjusted independently;
> * in flat volume model, they are absolute, and the "device volume" is just a convenient handle to adjust them all together.

https://bugzilla.redhat.com/show_bug.cgi?id=1265267

**Comment by johnraff** [comment]
Yes, it seems to be basically a PulseAudio issue. However, some comments in this [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837637) suggest that apps can alleviate the problem at their end too.

> The volume is reset by applications that try to set the master volume to 100%. Most applications don't try doing that anymore.

**Comment by ebruck** [comment]
I suppose, but that would mean an option to disable volume control?

**Comment by johnraff** [comment]
I'm not an authority on audio, but don't some apps change their local volume without resetting PA's master volume?

(Anyway, I prefer flat-volumes off, so the issue is gone for me.)

**Comment by Docdez** [comment]
Well, I am from the #42 issue (I closed it).
Problem and the app version are similar. But setting the "flat-volumes" to off mode not helped.

**Comment by Docdez** [comment]
I think that the "volume-level" is good feature.
But why doesn't it work correctly?

**Comment by ebruck** [comment]
It works fine for me on Ubuntu 16.04, 16.10, 17.04 & 17.10 and it appears as well for others using Arch and Solus. I don't know why Debian would have an issue. My guess right now is that it may be how pulseaudio is configured or the version being used. I have only one API to modify the stream playing audio level and that's it.

**Comment by Docdez** [comment]
I had some stupidity, I needed uncomment the "flat-volumes = no".
It works fine now)

**Comment by johnraff** [comment]
I think Ubuntu (and some others) set flat volumes *off* in the PA configuration (which solves this, and some other issues) while Debian, at the moment anyway, are leaving flat volumes *on*, following the current PA default. This seems to make the master volume jump to 100% when apps try to change it.
