### ISSUE TITLE
Better Interpret iHeartRadio tags

### ISSUE THREAD

**Issue by bonelifer** [ebruck/radiotray-ng#37]
![iheartradio](https://user-images.githubusercontent.com/121736/32277486-9ad14566-bee0-11e7-833e-a1ac03d13fb1.png)

KSSN 96: http://c4icyelb.prod.playlists.ihrhls.com/105_icy

**Comment by ebruck** [comment]
I have a simple parser to pull out text=".."  after splitting the tag into title and artist. I will probably turn this feature off by default using config option:  iheartradio-tag-parsing

Do you have any other stations I can test with?

**Comment by bonelifer** [comment]
24/7 Comedy Live: http://c3icyelb.prod.playlists.ihrhls.com/4902_icy

Big 94.9: http://c10icyelb.prod.playlists.ihrhls.com/101_icy

If you need anymore, just go to iheart.com, go to a channel, then search the source for:
"shoutcast_stream": or _icy portion that seems to be in all the shoutcast stream urls. The majority of channels or at least most should have a shoutcast stream.

**Comment by ebruck** [comment]
**ihr-title** config setting will control this. **split-title** must be enabled for it to work.

**Comment by bonelifer** [comment]
Just downloaded and compiled the v0.2.0-dev branch. The deb file installed without problem. Works great.   Thanks.

**Comment by ebruck** [comment]
I'm going to make this on by default.

**Comment by bonelifer** [comment]
Has iheart changed something, now getting "text=" being displayed instead.
