### ISSUE TITLE
Bad Quailty Warning while installing on software center

### ISSUE THREAD

**Issue by teslaji** [ebruck/radiotray-ng#4]
The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

> Lintian check results for /tmp/mozilla_lucy0/radiotray-ng_0.1.3_ubuntu_16.04_amd64.deb:
> E: radiotray-ng: control-file-has-bad-permissions postinst 0775 != 0755
> E: radiotray-ng: control-file-has-bad-permissions postrm 0775 != 0755
>

**Comment by ebruck** [comment]
*sigh* cmake is doing that...
On 16.10 version 3.5.2 seems to be doing a better job. 

I fixed a similar issue for the Flatabulous packaging:
https://github.com/anmoljagetia/Flatabulous/blob/master/debian/CMakeLists.txt#L47

For now I would just install at the command line using dpkg and then "apt-get install -f" to install the dependencies.
