### ISSUE TITLE
When notifications turned off Radio can't be turned off

### ISSUE THREAD

**Issue by igor2x** [ebruck/radiotray-ng#5]
I installed Radiotray-ng on Ubuntu 16.04 32-bit.

1. Close down Radiotray-ng.
2. Open ~/.config/radiotray-ng/radiotray-ng.json and change:
`   "notifications" : false,`
3. Start Radiotray-ng and click on icon and select "Turn on {radio station}".
4. Notifications are off which is great. But now lets disable the radio, click on icon and select "Turn off  {radio station}". Radio is turned off like for half a second and then it is turned on automatically. It looks to me when notifications are off radio can't be turned off.

To confirm, I have shut down program. I reversed json config setting back to:
`"notifications" : true,`
and started a program. Notifications reappears as expected and now radio can be turned off clicking on icon and selecting "Turn off {radio station}".

Also setting both settings:
```
"notification-verbose" : false,
"notifications" : false,
```
and the problem is the same.

But settings:
```
"notification-verbose" : false,
"notifications" : true,
```
and radio can be turned off, but there are still notifications.

**Comment by ebruck** [comment]
Thanks for digging into this. It's a silly bug and I'll have a fix soon. I'm going to hold off releasing a new version until I fix #4.
