### ISSUE TITLE
Lack of notification icon in black

### ISSUE THREAD

**Issue by anechampenois** [ebruck/radiotray-ng#50]
When I tried to solve my issue with the icons (see [issue #49 ](https://github.com/ebruck/radiotray-ng/issues/49)) I noticed that the notification icon is only in a white version.
For users like me using light color destop environment, it's a real problem because it's almost invisible.
It could be usuful to have a second version of this icon in black in radiotray-ng/data/hicolor/256x256/apps/ (if I'm not wrong) and to allow in the config file the use of this icon by an option just like radiotray-ng-on and radiotray-ng-off icons.

**Comment by ebruck** [comment]
You can change it.  There's a black version located in /usr/share/radiotray-ng used for the about box.

> radiotray-ng-notification: installed theme icon name for "notification" or path to image

**Comment by ebruck** [comment]
Before I close this issue, could you please tell me what desktop environment you are using and which theme? Perhaps I can create dark version for it in a future release.

**Comment by anechampenois** [comment]
OK Thanks for your lights on theming radiotray-ng.
I use xfce 4.12 with the breeze-X theme (a GTK theme similar to breeze, a KDE5 theme). It's specific to SolydXK. If you want, I can send you a screenshot.
I'd like to say that, with the theming in radiotray-ng, I can modify icon in the tray, notification's icon, but I can use a theme for my menu called [whisker menu](https://gottcode.org/xfce4-whiskermenu-plugin/).
Thanks for your patience and your work.

**Comment by ebruck** [comment]
I'm starting to see theme creators add radiotray-ng icons.  You'll have to file a feature request with your icon theme's maintainer.
