### ISSUE TITLE
bookmark editor does not work

### ISSUE THREAD

**Issue by granthgh** [ebruck/radiotray-ng#51]
Have installed radiotray-ng_0.2.0_ubuntu_17.10_amd64.deb on kubuntu_17.04 and radiotray runs fine, however the bookmark editor does not work. Is this a known issue?
Also would be possible to compile a ubuntu 17.04 radiotray package if that is the problem?

**Comment by granthgh** [comment]
Running the editor from the command line gives:
rtng-bookmark-editor: relocation error: rtng-bookmark-editor: symbol _ZNK8wxWindow7IsShownEv, version WXU_3.0 not defined in file libwx_gtk2u_core-3.0.so.0 with link time reference.

Hopefully this will help localize the issue.

**Comment by ebruck** [comment]
I'm sorry the package will not work on 17.04. If you look at the readme there are instructions on how to build from source. I will have to look at creating a PPA in the near future.

**Comment by ebruck** [comment]
@granthgh I've uploaded a 17.04 package.

**Comment by granthgh** [comment]
Thank you for the PPA update.

**Comment by CPUGPU** [comment]
Thank you for the 17.04 release.  Installed and working!  (Editor doesn't.  Will add info to existing issue.)

**Comment by ebruck** [comment]
It's working fine for me on 17.04 when I build it there. I may of missed a dependency.
Having said that 17.04 will reach EOL on January 13, 2018.

**Comment by CPUGPU** [comment]
Ah, time for me to upgrade.  Don't waste your time fixing it for 17.04 if we only have 6 days left!

**Comment by CPUGPU** [comment]
Upgraded to 17.10, can confirm the bookmark editor works just fine.

**Comment by mburns83** [comment]
I have not been able to replicate this issue. However, research has shown that other products have experienced similar issues on Ubuntu 17.04 and derivatives. The typical solution for those other products have been to rebuild them locally against a pre-3.0 version of wxWidgets. Unfortunately, the editor uses capabilities that are not available in pre-3.0 versions of wxWidgets.

The following fixes the issue, but wxWidgets 3.0.3 is not provided in Ubuntu updates for 17.04. It is available on 17.10.

[https://dev.solus-project.com/T3481](https://dev.solus-project.com/T3481)
