### ISSUE TITLE
Internet Radio Directory Integration

### ISSUE THREAD

**Issue by al-right** [ebruck/radiotray-ng#52]
Hi,
This is feature suggestion:
Integration of an external Internet radio directory (IRD) such as e.g. Dirble https://dirble.com/developer/
It is already being used by others: https://dirble.com/developer/applications 

Ideas:
* Search for Internet radio stations and add them via the Bookmark editor. E.g. via search from categories, but also via a search field if one has some keywords available such as station name (and optional maybe genre.)
Requirement: User would likely need to have a user account. E.g. in the case of Dirble it seems to be requirement to get access to the API that in the free version is limited to 1500 requests per month. https://dirble.com/plans

* Optional: Provide a link inside of the Bookmark editor to the IRD (e.g. Dirble) if one wants to be taken to the home page of the directory to add a station to the directory, add or change an existing stream to a station.

* Optional: Option for automatic updating stations/streams stored locally in the bookmark json file as they become updated on e.g. Dirble when someone adds/updates a station stream. E.g. have I previously added Fréquence 3 and the URL to the stream changes then automatic update the stream URL to avoid broken stations that would otherwise require manual updating.
Requirement: Depending on how much traffic that goes to the IRD the automatic checking for station updates might needs to be limited to once a day, once a week or once per startup of Radiotray-NG.

* Optional: Selection of either best quality or specific stream (e.g. a pls might have different streams available 192 kbit/s, 128 kbit/s or 96 kbit/s) and some might prefer mp4 over mp3 etc.

Thanks for Radiotray-NG! It works really well!

**Comment by ebruck** [comment]
@al-right thanks these are great ideas.

**Comment by evdbovenkamp** [comment]
Integration/link with radio-browser.info would be a very (!!!) nice feature.

**Comment by surruk51** [comment]
Maybe allow users to share their list of stations to a central point (optional of course), that could be searched by others to add items to their own station list.

**Comment by mxmilkiib** [comment]
Given all the links above 404 and the homepage is "Apache2 Debian Default Page", I'm unsubscribing from this issue and subscribing to #189. radio-browser.info is the way this kinda system was achieved in the end, which is why [RadioDroid](https://github.com/segler-alex/RadioDroid) and [Radiolise](https://radiolise.gitlab.io/) are my streaming apps of choice.

**Comment by gcqmkm02** [comment]
wontfix et maintenant radiotray-ng est mort :(
