### ISSUE TITLE
[Feature req] Suppress notification for some radio stations

### ISSUE THREAD

**Issue by guzzard** [ebruck/radiotray-ng#54]
Would be really nice to be able to enable/disable notifications per radio stations in the station configuration. Some stations spam with ads etc in the notifications with very short intervals.

**Comment by ebruck** [comment]
@mburns83 please add editor support for the new toggle. thx!

**Comment by ebruck** [comment]
@guzzard editor changes by @mburns83 have been merged into v0.2.2-dev. If you can build and test that would be very helpful.

**Comment by guzzard** [comment]
Cool! Will test tonight!

**Comment by guzzard** [comment]
@ebruck  @mburns83 working great for me! Settings apply on bookmark refresh. Thanks!

**Comment by ebruck** [comment]
That's great. Thanks for testing!
