### ISSUE TITLE
Copy current artist and title to clipboard

### ISSUE THREAD

**Issue by zhukovra** [ebruck/radiotray-ng#58]
Hi @ebruck! Thank you for supporting Radiotray!

Please implement that feature: left mouse click in area copies this text to clipboard:
![image](https://user-images.githubusercontent.com/289431/38609644-48fc71ea-3d87-11e8-8c94-14793d033606.png)

**Comment by ebruck** [comment]
No events are fired when clicking on a disabled menu entry. Perhaps you could put this into a script or assign to a hotkey?

> $ qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -a .title,.artist | xclip -sel clip

**Comment by zhukovra** [comment]
Thank you for hint, it works.

But maybe someone have a time to make that function. Can you label it with "enhancement"?

**Comment by ebruck** [comment]
There is no event that can be acted upon when the menu item is disabled.

**Comment by zhukovra** [comment]
I'm OK, why not? If you can suggest better UX to copy current song info - let's talk about it!

**Comment by ebruck** [comment]
@zhukovra can you build the v0.2.2-dev branch and test the new feature?

**Comment by zhukovra** [comment]
@ebruck a bit later, thanks.
