### ISSUE TITLE
radiotray stopped playing specific m3u8 radio

### ISSUE THREAD

**Issue by sispus** [ebruck/radiotray-ng#59]
Hi, thanks for keeping ailve this wonderful radiotray.
My radiotray (v0.2.2-dev and v0.2.1) on manjaro xfce (17.1.8) now stop playing TRT Radyo 3, and other TRT channels. 
http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/master.m3u8
how can i fix it?

**Comment by sispus** [comment]
another m3u8 stream, not working. they were working couple of days ago.
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_world_service.m3u8

**Comment by ebruck** [comment]
@sispus BBC World service is working for me.

**Comment by sispus** [comment]
yes, now bbc works here too, sorry. but trt3 one doesn't.

**Comment by zboraon** [comment]
@sispus For Trt3, try this:

http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/index_96_a-p.m3u8?sd=10&rebase=on

**Comment by ebruck** [comment]
@sispus try this: http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/segment152390126_96_a-p.ts

**Comment by ebruck** [comment]
It appears m3u8 (application/vnd.apple.mpegurl) files need special handling and it's not a typical m3u file as radiotray-ng assumes. It can contain paths to other resources. I've looked at how VLC handles them:

https://mailman.videolan.org/pipermail/vlc-commits/2013-June/020701.html
https://mailman.videolan.org/pipermail/vlc-commits/2015-July/031403.html

I need to research this a bit more. Best bet is to try to find an alternate URL if possible or walk the chain of m3u8 files and find a stream URL that works for you.

**Comment by sispus** [comment]
There is no alternative stream URL, unfortunately. 

I have plenty of time :)  so tried these, without knowing if they will help you:
 1. 
http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/segment152390126_96_a-p.ts
"Failed to download playlist"
2.
http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/segment152390126_96_a-p.ts?sd=10
"Failed to download playlist"
3.
I had already extracted this one from another m3u8 file. It is another TRT radio, "TRT Türkü". It  plays but corrupted, plays in small, repeating fractions and then stops:
http://trtcanlifm-lh.akamaihd.net/i/TRTTURKU_1@182246/index_96_a-p.m3u8?sd=10&rebase=on
4. 
I tried ...`a-b.m3u8?sd=10` ,  ...`a-b.m3u8?sd=10&rebase=on` and ...`a-p`.... versions, they all play similarly corrupted way.
5. 
in terminal, 'gst-play-1.0' plays correctly `a-p.m3u8` and `a-b.m3u8` versions, with `sd=10` but "without" `&rebase=on` parts (and also original .m3u8 file); but not `a-p.ts` and versions (says 404 not found).
```
gst-play-1.0 http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/index_96_a-p.m3u8
Press 'k' to see a list of keyboard shortcuts.
Now playing http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/index_96_a-p.m3u8
Redistribute latency...
Prerolled.
```
6.
`cvlc` also plays but constantly gives errors and stops, like:
```
cvlc http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/master.m3u8
VLC media player 3.0.2 Vetinari (revision 3.0.1-222-gdabb17b575)
```
`ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095` 
`main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 1000 ms)`
`[00007f5ba8002d40] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095`
`[00007f5bb8002f20] adaptive stream error: Failed reading http://trtcanlifm-lh.akamaihd.net:80/i/RADYO3_1@181946/segment152391128_96_a-p.ts?sd=10&rebase=on: HTTP/1.1 404 Not Found`
7.
I think, the "segment" number of the links changes constantly. 
8.
gst-discoverer reports BBC and TRT links similarly, the only difference is BBC is `seekable=yes` but TRT =no. 

```
$ gst-discoverer-1.0 http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/master.m3u8
Analyzing http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/master.m3u8
Done discovering http://trtcanlifm-lh.akamaihd.net/i/RADYO3_1@181946/master.m3u8

Topology:
  container: application/x-hls
    container: MPEG-2 Transport Stream
      audio: MPEG-2 AAC
        audio: MPEG-4 AAC

Properties:
  Duration: 0:00:00.000000000
  Seekable: no
  Live: no
  Tags: 
      audio codec: MPEG-2 AAC

```
```
$ gst-discoverer-1.0 http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_world_service.m3u8
Analyzing http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_world_service.m3u8
Done discovering http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_world_service.m3u8

Topology:
  container: application/x-hls
    container: MPEG-2 Transport Stream
      audio: MPEG-2 AAC
        audio: MPEG-4 AAC

Properties:
  Duration: 0:00:00.000000000
  Seekable: yes
  Live: no
  Tags: 
      audio codec: MPEG-2 AAC
```

**Comment by ebruck** [comment]
TuneIn doesn't even try to play these streams: https://tunein.com/radio/TRT-Radyo-3-912-s14307/

**Comment by ebruck** [comment]
I watched gst-play in Wireshark and I can see that it's constantly requesting the playlist. I believe this is required once it's played the segments. This is certainly something I could do, but would require a major rewrite of the player and playlist downloader code. To be honest this isn't something I'm interested in doing as there are thousands of other stations to listen to.

**Comment by sispus** [comment]
I don't blame you for that, but let me be sad shortly :( It is the only station that I want to listen in Turkish while working.
Actually I have a consolation that it is an official nationwide broadcast here and I have a radio receiver for that :)
Thank you for your patience and keeping radiotray alive, again.

**Comment by sispus** [comment]
Now its working well! I'm here to thank you :)
v0.2.5-dev
(v0.2.4-18-g0384bc4-dirty)

**Comment by ebruck** [comment]
@sispus glad to hear it's working for you.
