### ISSUE TITLE
Compilation problem on Archos

### ISSUE THREAD

**Issue by CelsiusX** [ebruck/radiotray-ng#6]
Hi, I am in trouble with compiling latest version of radiotray-ng on Archos distro. Output with error is attached. Thanks for help.
[output.txt](https://github.com/ebruck/radiotray-ng/files/801994/output.txt)

**Comment by ebruck** [comment]
It appears that gmock is not installed correctly. Did you follow my instructions or use the package that came with your distro? The recommended usage is to build and install googletest from source and not use what came with your distro.

**Comment by CelsiusX** [comment]
[output_II.txt](https://github.com/ebruck/radiotray-ng/files/802283/output_II.txt)
I used the package from repository, so I uninstalled it, and compiled fresh googlemock to the system. Compilation was succesful, but when I try to run app, it crash with SIGBART signal.

**Comment by ebruck** [comment]
Could you please post a stack trace?  I know it's not the same, but I just tried building and running on Ubuntu 17.04 and had no problems.

**Comment by CelsiusX** [comment]
I am not sure, if this is what you ask me for. I ran the "strace -o strace.txt radiotray-ng " command and output is attached.
[strace.txt](https://github.com/ebruck/radiotray-ng/files/804748/strace.txt)

**Comment by CelsiusX** [comment]
I found, that my config folder does not contain radiotray-ng.json file, what caused the crash. I created new one config and now it working well. Thank you for your time and support. Regards C.

**Comment by ebruck** [comment]
That's odd as I create a default config if it's not there.
