### ISSUE TITLE
The donation notification is too frequent

### ISSUE THREAD

**Issue by Kabouik** [ebruck/radiotray-ng#61]
I understand that this notification is there and cannot be disabled, but it is just too frequent when it pops in several times during one single track. I don't actually know how notifications work, because the track name notification seems to kick in several times during a track. Is it timer-based?

**Comment by Kabouik** [comment]
Nevermind, the notifications were coming from the radio I was listening. Sorry about the noise.

**Comment by ebruck** [comment]
With the latest release you can now turn "notify" off for a specific station in the bookmark editor.

**Comment by Kabouik** [comment]
Nice, looking forward to getting the update in the Solus repository then! At the moment it seems we just have 0.2.1 available.
