### ISSUE TITLE
Compatibility with http://www.radio-browser.info/

### ISSUE THREAD

**Issue by Kabouik** [ebruck/radiotray-ng#62]
On my Sailfish phone, I use Allradios all the time, an Internet radio application that uses http://www.radio-browser.info/gui/#/ for listing radios. Gradio uses that too. Is there a way this base could work directly within Radiotray-ng? The number of listed radios is impressive, and the tagging system makes it easy to find radios (and most importantly, discover new radios). I would love to have a browser like that implemented in radiotray-ng, where stations could be bookmarked and listed in the main list afterwards for instance. 

Allradios is open source so the code could be partly reused to, maybe one day, implement a radio browser in radiotray-ng, if deemed relevant for the scope of radiotray-ng: https://github.com/nesnomis/harbour-allradio

I discovered Radiotray-ng just today, and I'm loving it so far, simple and efficient.

**Comment by ebruck** [comment]
This is similar to #52.
I'll keep radio-browser.info in mind as another possible source for a new directory browser.
thx!

**Comment by Kabouik** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Oh right, I missed #52 sorry. The author indicated that the database he mentioned would require user
accounts though, and I don't think this is necessary with www.radio-browser.info, since I use no
accounts for Allradios and Gradio, so that would be a good candidate. I am not sure whether there is
a limit to the number of request can do, but I've never reached, if any. Dirble looks interesting
too.


Ed Bruck <notifications@github.com> wrote:
> This is similar to #52.
> I'll keep radio-browser.info in mind as another possible source for a new directory browser. thx!
>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBCgAGBQJa4tN+AAoJEEu01Puy7YOY/doH/RVKf8DVXqNfg7VRG6BGUYTP
GisAoo9aGHUegNTHSPexcEA9pOnJriq7y/saYXVzp8wtjuJO8hOBm41P2tUdA2bI
vfMDYUAwbQwjw0TO6mLb+7d7r5qVrs20CIwMoBQno2jFtwXJfCpOeEJGte6B0xHt
1nO8vYPYhWcUMLiB1o59m2l4DKx2nuuBdfzE2I7MKMNHGpEiAYcE6lHAnuArEek7
evhBuyWWYIZv/H8K5i9+BkVfxUue5nFAOG6JrVfSbxrbAngUcS0AIEpiSgPvT++5
mQ44NGpsmByxXejgE6zywA7/9RDf6kU6F6tJY0W2/RSvgzbght1NLdlGFSk0T64=
=odgX
-----END PGP SIGNATURE-----
