### ISSUE TITLE
Dependencies issue to install on ubuntu 16.04

### ISSUE THREAD

**Issue by rcspam** [ebruck/radiotray-ng#63]
Hi, thanks for this wonderful app.
Installation of the 0.22 version deb file on ubuntu 16.04 require libcurl4...
I know this package is for 18.04, but is it possible to produce one for 16.04LTS

**Comment by ebruck** [comment]
I'll have to detect 16.04 builds to address this issue: https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294

I should have something soon.

**Comment by ebruck** [comment]
16.04 package added: 
https://github.com/ebruck/radiotray-ng/releases/download/v0.2.2/radiotray-ng_0.2.2_ubuntu_16.04_amd64.deb

**Comment by ebruck** [comment]
32 bit builds are no longer being generated.

**Comment by rcspam** [comment]
I gave compile a deb package without problem on 16.04, i have just remove libcurl4 depend from the cmakelist and so from the control debian file.
