### ISSUE TITLE
"Currently Playing" only alotted one line in Plasma 

### ISSUE THREAD

**Issue by vtpoet** [ebruck/radiotray-ng#68]
Have been using radiotray/radiotray-ng for years and love your work on it.

An ongoing issue that I've noticed ever since using Radiotray & Radiotry-NG on Plasma: When right clicking the drop down menu in the panel, only one line is allotted to the "currently playing" slot (unlike in Linux Mint/GTK desktops). This just about always makes it impossible to read what's currently being played. All descriptions are truncated.

![radiotray](https://user-images.githubusercontent.com/26415181/40874458-7bc2bf1a-663d-11e8-98cb-8d7bebe8c376.png)

**Comment by ebruck** [comment]
I imagine multiple lines are not supported in Plasma/Qt. Have you seen any other app use multiple lines in KDE?

I'll do a bit of research, but if it's not supported then the only thing I can do is insert a menu item for each line, but that with the spacing would make the menu rather long.

**Comment by ebruck** [comment]
Another thing to try is not use line breaks and see if Plasma wraps the line for me.

**Comment by vtpoet** [comment]
Well, it's minor. If it's an easy fix, then great. If not, I'll just keep using as is. But as an alternate solution, what about hovering over the panel icon to display "now playing" info? --- or does Plasma also get in the way of that?

**Comment by ebruck** [comment]
Tooltips seem to of been removed by most desktop environments. I don't believe appindicators ever supported them.

**Comment by vtpoet** [comment]
Bother...

I just updated RadioTray after updaing to 18.04. The new editor is great. :)

**Comment by ebruck** [comment]
Check out the new **invert-menu** option if you use adiotray-ng on a "bottom" dock.

**Comment by ebruck** [comment]
Just tried running radiotray-ng under Kubuntu 18.04 and multiline menu items are certainly not supported well. I've tried \r vs \n and I can make it "sort" of work, but KDE isn't expanding the menu item to accommodate the second line. Also, If I disable the 40 column line wrapping I use it sometimes ignores the line break using \r and renders it all on one line.

![image](https://user-images.githubusercontent.com/1168556/40880099-a6c5a354-665f-11e8-8926-f500c1a4d3c1.png)

I've reverted my code changes and tried "split-title" : false," and with the tiny font the desktop is using it certainly looked better and probably the best I can do. Please give it a try.

**Comment by ebruck** [comment]
I also noticed that middle click does work for starting/stopping playback. Sadly mouse scroll events are not being sent so you can't adjust the volume. You can use the dbus interface to adjust the volume levels if you want.

**Comment by vtpoet** [comment]
Glad to give it a try. Is there a deb file or do I need to clone your GIT repository?

**Comment by ebruck** [comment]
No, just exit radiotray-ng and edit your ~/.config/radiotray-ng/radiotray-ng.json config file.

**Comment by vtpoet** [comment]
Okay, just tried it. And the result:
![radiotray dropdown](https://user-images.githubusercontent.com/26415181/40881698-5bf7258c-669b-11e8-8376-a196a4a02bf3.png)

Better than it was. I can live with it. :)

**Comment by ebruck** [comment]
I think I'll add an option in the next release to disable the word wrapping.

**Comment by ebruck** [comment]
@vtpoet can you build my v0.2.3-dev branch and test this change? Also, you can not edit the config while radiotray-ng is running or it will revert any change you made.

**Comment by vtpoet** [comment]
Hi ebruck, I do a build about once every other year (and out of desperation); and always have to relearn everything. I'm game, but you're going to have to prime the spark plug. "I'm a Doctor, not a bricklayer." (Star Trek reference...)

So, to make sure we're on the same page:

1.) Download radiotray-ng-master.zip? Is that your v0.2.3-dev branch?
2.) sudo apt install libcurl4-openssl-dev libjsoncpp-dev libxdg-basedir-dev libnotify-dev libboost-filesystem-dev libgstreamer1.0-dev libappindicator3-dev libboost-log-dev libboost program-options-dev libgtk-3-dev libnotify-dev lsb-release libbsd-dev libncurses5-dev libglibmm-2.4-dev libwxgtk3.0-dev libwxgtk3.0-0v5  (Which then asks me to install about half a gig's worth of dev dependencies.)
3.)  Then this:

$ cmake <path-to-source>/radiotray-ng -DCMAKE_BUILD_TYPE=Release
$ make package
$ sudo dpkg -i ./radiotray-ng_x.y.z_<i386|amd64>.deb
$ sudo apt-get install -f

The last three commands are straightforward enough. But could you give me an example of the cmake command?

If this is all wrong, just tell me.

**Comment by ebruck** [comment]
1. use: https://github.com/ebruck/radiotray-ng/archive/v0.2.3-dev.zip
2. That is the correct cmake command. Just make sure the first parameter points to where the source code is.

**Comment by vtpoet** [comment]
Yeah... Okay, you clearly don't get just how little how do this sort of thing: 

:)

$ cmake radiotray-ng -CDMAKE_BUILD_TYPE=Release 
loading initial cache file DMAKE_BUILD_TYPE=Release
CMake Error: Error processing file: DMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/vtpoet/Downloads/radiotray makefile/radiotray-ng-0.2.3-dev/src/CMakeFiles/CMakeOutput.log".

**Comment by ebruck** [comment]
Are you building in the directory where you unpacked the source code?
That cmake_minimum_required should not be there as I have it set in my code. 

Perhaps the first parameter needs to be set to the location of the code?

`$ cmake <path-to-src>/radiotray-ng -CDMAKE_BUILD_TYPE=Release`

**Comment by vtpoet** [comment]
Yes to your first question. That seemed the simplest thing to do. Below is what I was looking at when running Cmake:

![cmake radiotray](https://user-images.githubusercontent.com/26415181/40889500-b161fb9c-6735-11e8-8bd5-cb01463ad7f5.png)

**Comment by ebruck** [comment]
Ok then you should just do:   cmake . -DCMAKE_BUILD_TYPE=Release

**Comment by vtpoet** [comment]
Like magic. So you know, the last time I coded was with a TRS-80 Pocket Computer (which I still have) and later an Apple IIe (which I tragically don't) --- Basic, Pascal and a smattering of machine language. My knowledge of programming is a little dated.

radiotray-ng:
  Installed: 0.2.3-dev
  Candidate: 0.2.3-dev
  Version table:
 *** 0.2.3-dev 100
        100 /var/lib/dpkg/status

And here's what it looks like:

![radio tray rev](https://user-images.githubusercontent.com/26415181/40890523-a826b60c-6745-11e8-9839-82f7f56bdbc1.jpg)

**Comment by ebruck** [comment]
Now exit and edit your config and make sure these are set to:

"split-title" : false
"wrap-track-info" : false

**Comment by vtpoet** [comment]
Hmmm.... Don't see the second option:

![radiotray config](https://user-images.githubusercontent.com/26415181/40890749-c402d290-6748-11e8-90d6-fd840927fead.jpg)

**Comment by ebruck** [comment]
Please add it.

**Comment by vtpoet** [comment]
Sweet. Been trying different channels. A huge improvement for a Plasma user. Every once in a while I'd hear a piece and not know what it was. I'd have to go to the actual website to sort it out.

Some of the "now playing" titles are long (classical music...). Makes the drop down menu stretch half across the desktop, but doesn't bother me at all. Might be too much work, or not  necessary, but might want to consider some code preventing it from exceeding the width of a given screen.

**Comment by vtpoet** [comment]
Right now, if my counting's right, the current title is 121 characters long:

![121 characters](https://user-images.githubusercontent.com/26415181/40891441-79daab88-6753-11e8-9dbf-7178fa4438fa.png)

80 Characters is probably too short. I'd speculate something like 160 characters and adds... That should work for anyone still using 1366x768? 

Here's what's playing on Radio Classique:

![and beethoven](https://user-images.githubusercontent.com/26415181/40891477-48db3d6c-6754-11e8-849e-b3fe4a99f07c.png)

**Comment by ebruck** [comment]
160 may be way too big, but I could also make that configurable.

With this option:

>            "track-info-copy" : true,

You can copy the text to the clipboard paste into a search.  I'll make sure that when I cut the text off that the original is still copied to the clipboard.

**Comment by vtpoet** [comment]
Up to you, obviously, but if I had to choose I'd rather see the listing than have to copy/paste.  It presently works beautifully on a 1080 screen.

**Comment by vtpoet** [comment]
That's sensible. If it's customizable, then no reason to complain. 

How will this feature be discoverable?

**Comment by ebruck** [comment]
I don't plan to create a preference editor. For most people the defaults are fine.

**Comment by vtpoet** [comment]
Thanks ebruck! And thanks for the work you've done on this little app. I use it every day. :)
