### ISSUE TITLE
Can't find gstreamer plugin...

### ISSUE THREAD

**Issue by vtpoet** [ebruck/radiotray-ng#7]
Hi, I'm a newcomer to github. Not sure if I'm doing things right but...

Thank you so much for reviving radiotray -- my fav internet radio app. Just wanted to forward an intermittent bug. Sometimes, after resuming from suspend,  rt-ng will complain that it can't stream a given station:  (gstreamer plugins are unavailable or not installed). The bug is exceedingly minor -- the workaround is to simply quit radiotray and restart. For informational purposes, I'm using a fresh install of Mint.

4.10.1-041001-generic x86_64 (64 bit) Desktop: Cinnamon 3.2.7 Distro: Linux Mint 18.1 Serena

**Comment by ebruck** [comment]
Were you playing a stream when your system went to sleep?
I've researched this a bit and it could be a gstreamer issue, which means there's not a lot I can do about it.

**Comment by ebruck** [comment]
Another thing to try is install the "ugly" gstreamer package if you've not done so already. I'd be curious to see if that fixes things. This is a guess of course, but I'd be interested to see if it helps as I have never had this problem and I regularly suspend my laptop everyday without any problems.

**Comment by vtpoet** [comment]
Sorry I didn't get back sooner. Have to carpenter for a living... 

1.) I'm fairly certain I wasn't streaming when I suspended my system, but I'll pay more attention and also experiment with that --- see if it reproduces the bug.

2.) Just checked and the 'ugly' plugins were already installed.

**Comment by vtpoet** [comment]
And there it is again. I know it wasn't playing when suspended.

Error: Your Gstreamer installation is missing a plugin. 

Quit. Restarted. Works fine. It's such a minor bug that I'll leave it at that. Just out of curiosity, though, I'll restart RTNG in terminal and if something useful pops up I'll send it along.

**Comment by ebruck** [comment]
Can you try enable debug logging? You'll find the logs in your ~/.config/radiotray-ng/logs

To enable:

1. exit radiotray-ng
2. edit ~/.config/radiotray-ng/radiotray-ng.json and add the following:

debug-logging" : true

Be careful with the commas before or after this entry. Parsing may fail otherwise.

**Comment by ebruck** [comment]
I've been running radiotray-ng on three systems that I regularly "sleep" and I've never seen this issue.
