### ISSUE TITLE
MPRIS support?

### ISSUE THREAD

**Issue by terinjokes** [ebruck/radiotray-ng#71]
I have integrations with the MPRIS D-Bus specification. I know not all the methods make sense for internet radio, but I think it would still be great to support it alongside the custom D-Bus interface.

The MPRIS specification allows us to signal support for track controls and seeking with booleans such as `CanGoNext` and `CanGoPrevious`.

Is there any interest in working on this? If not, would you accept a patch for adding it?

**Comment by ebruck** [comment]
@KOT040188 I'm sure you can always use the dbus interface along with hotkeys to control the player. Yes, it's not mpris, but right now that is the best you can do under KDE.

**Comment by KOT040188** [comment]
Most of all I need support for kdeconnect.

**Comment by terinjokes** [comment]
I'm going to try to add MPRIS as a patch.

**Comment by KOT040188** [comment]
@terinjokes, thank you!

**Comment by KOT040188** [comment]
@terinjokes, how long will it take? At least approximately.

**Comment by terinjokes** [comment]
No idea. This isn't my project and I'm working on it in my free time when I feel like it.

**Comment by TomaszGasior** [comment]
Please look at https://github.com/ebruck/radiotray-ng/pull/94

**Comment by ebruck** [comment]
Thanks @TomaszGasior for getting the ball rolling!

**Comment by ebruck** [comment]
@terinjokes can you use this as a starting point if you've not already begun development?

**Comment by ebruck** [comment]
@terinjokes any progress?

**Comment by KOT040188** [comment]
We are all really looking forward to the progress!

**Comment by terinjokes** [comment]
I'm unlikely to complete this. My interests have moved elsewhere.

**Comment by KOT040188** [comment]
Everything always has a bad ending…

**Comment by KOT040188** [comment]
I still hope ...

**Comment by thomas-mc-work** [comment]
Maybe you can elevate some volunteers to project members?

**Comment by terinjokes** [comment]
You don't need to be a project member to contribute?

**Comment by sispus** [comment]
MPRIS support would be good. For kdeconnect you can use commands for now.

**Comment by IngoMeyer441** [comment]
I have created a wrapper for Radiotray-NG which adds MPRIS support: <https://github.com/IngoMeyer441/radiotray-ng-mpris>.
This has the advantage that Radiotray-NG can keep its current DBus API. @ebruck If you find this useful, it would be nice if my script could be linked in your README file :innocent:.

**Comment by sispus** [comment]
@IngoMeyer441  Oh thank you! Works very well. I can manage the radiotray using kdeconnect from my phone. I can skip to next station in my bookmarks list.
I think volume cannot be adjusted by it.
Thanks alot <3

**Comment by IngoMeyer441** [comment]
@sispus Thanks for the feedback! Volume control *should* work. The bridge between MPRIS and the Radiotray-NG api [is implemented](https://github.com/IngoMeyer441/radiotray-ng-mpris/blob/develop/radiotray_ng_mpris/wrap.py#L273-L274), but honestly I forgot to test volume changes. Maybe we can get this working too.

**Comment by IngoMeyer441** [comment]
Ok, I can confirm that volume changes do not work currently. I will look into this ([opened an issue for this](https://github.com/IngoMeyer441/radiotray-ng-mpris/issues/1)).

**Comment by IngoMeyer441** [comment]
The volume can be adjusted in the bug fix release [v0.1.1](https://github.com/IngoMeyer441/radiotray-ng-mpris/releases/tag/v0.1.1).

**Comment by sispus** [comment]
now it's working. thanks

**Comment by ebruck** [comment]
@IngoMeyer441 thanks for writing this! I will be sure to include it in the readme.
