### ISSUE TITLE
Copy song title to clipboard

### ISSUE THREAD

**Issue by KOT040188** [ebruck/radiotray-ng#72]
I very often look for information in Google about the songs that I liked. Every time I have to type the name and author of the composition manually. I have to do this quickly while the song is playing, otherwise the next song will start playing and I will not record the name completely. It would be a good idea to add a button to copy the name of the song. Or you can do this by clicking on the name in the menu.

**Comment by ebruck** [comment]
Radiotray-NG already does this. Please have a  look at the config options in the readme.

>           track-info-copy: enable/disable track clicking to copy into clipboard

**Comment by KOT040188** [comment]
Sorry, I didn't notice…
