### ISSUE TITLE
No include directories:  Cannot build

### ISSUE THREAD

**Issue by brentr** [ebruck/radiotray-ng#73]
Under Debian Stretch 32-bit, cmake is not adding any include (-I) options to the c++ compiler commands.  It seems that none of the target_included_directories are being recognized.
Am I doing something stupid?
How do I satisfy the missing "user-agent" dependency?

To build from git:
# apt install libcurl4-openssl-dev libjsoncpp-dev libxdg-basedir-dev libnotify-dev libboost-filesystem-dev libgstreamer1.0-dev libappindicator3-dev libboost-log-dev libboost-program-options-dev libgtk-3-dev libnotify-dev lsb-release libbsd-dev libncurses5-dev libglibmm-2.4-dev libwxgtk3.0-dev libwxgtk3.0-0v5 cmake

$  cd git/radiotray-ng
$  cmake src/radiotray-ng -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at CMakeLists.txt:39 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "user-agent" of target "radiotray-ng" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/brent/git/radiotray-ng

$  make package
make: *** No rule to make target 'package'.  Stop.
#  OK, so there's no 'package' target.  Let's try the default make target:
$  make
Scanning dependencies of target radiotray-ng
[ 33%] Building CXX object CMakeFiles/radiotray-ng.dir/main.o
In file included from /home/brent/git/radiotray-ng/src/radiotray-ng/main.cpp:18:0:
/home/brent/git/radiotray-ng/src/radiotray-ng/radiotray_ng.hpp:20:54: fatal error: radiotray-ng/notification/notification.hpp: No such file or directory
 #include <radiotray-ng/notification/notification.hpp>
                                                      ^
compilation terminated.

$  make -n 
/usr/bin/cmake -H/home/brent/git/radiotray-ng/src/radiotray-ng -B/home/brent/git/radiotray-ng --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/brent/git/radiotray-ng/CMakeFiles /home/brent/git/radiotray-ng/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make -f CMakeFiles/radiotray-ng.dir/build.make CMakeFiles/radiotray-ng.dir/depend
cd /home/brent/git/radiotray-ng && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/brent/git/radiotray-ng/src/radiotray-ng /home/brent/git/radiotray-ng/src/radiotray-ng /home/brent/git/radiotray-ng /home/brent/git/radiotray-ng /home/brent/git/radiotray-ng/CMakeFiles/radiotray-ng.dir/DependInfo.cmake --color=
make -f CMakeFiles/radiotray-ng.dir/build.make CMakeFiles/radiotray-ng.dir/build
/usr/bin/cmake -E cmake_echo_color --switch= --green --progress-dir=/home/brent/git/radiotray-ng/CMakeFiles --progress-num=1 "Building CXX object CMakeFiles/radiotray-ng.dir/main.o"
/usr/bin/c++     -O3 -DNDEBUG   -o CMakeFiles/radiotray-ng.dir/main.o -c /home/brent/git/radiotray-ng/src/radiotray-ng/main.cpp
/usr/bin/cmake -E cmake_echo_color --switch= --green --progress-dir=/home/brent/git/radiotray-ng/CMakeFiles --progress-num=2 "Building CXX object CMakeFiles/radiotray-ng.dir/radiotray_ng.o"
/usr/bin/c++     -O3 -DNDEBUG   -o CMakeFiles/radiotray-ng.dir/radiotray_ng.o -c /home/brent/git/radiotray-ng/src/radiotray-ng/radiotray_ng.cpp
/usr/bin/cmake -E cmake_echo_color --switch= --green --bold --progress-dir=/home/brent/git/radiotray-ng/CMakeFiles --progress-num=3 "Linking CXX executable radiotray-ng"
/usr/bin/cmake -E cmake_link_script CMakeFiles/radiotray-ng.dir/link.txt --verbose=
/usr/bin/cmake -E cmake_echo_color --switch= --progress-dir=/home/brent/git/radiotray-ng/CMakeFiles --progress-num=1,2,3 "Built target radiotray-ng"
/usr/bin/cmake -E cmake_progress_start /home/brent/git/radiotray-ng/CMakeFiles 0

**Comment by ebruck** [comment]
This is incorrect:  

> cmake src/radiotray-ng -DCMAKE_BUILD_TYPE=Release

It should be pointing to the root of the repo:

> cmake . -DCMAKE_BUILD_TYPE=Release
