### ISSUE TITLE
Move root group up

### ISSUE THREAD

**Issue by KOT040188** [ebruck/radiotray-ng#75]
Radio stations added to the root group are located at the very bottom under all groups. Is it possible to transfer them to the very top of all groups?

**Comment by ebruck** [comment]
No, this is by design.

**Comment by KOT040188** [comment]
Too bad…

**Comment by ebruck** [comment]
@KOT040188 you could try this config option:

  >            invert-menu : menu rendered in reverse order

**Comment by ebruck** [comment]
I'll see how easy it is to add a flag to move it to the top.

**Comment by KOT040188** [comment]
Thank you. I'll check tomorrow.

**Comment by ebruck** [comment]
@KOT040188 please pull down v0.2.4-dev branch and test new config option.
