### ISSUE TITLE
How does one generate rtng_user_agent.hpp?

### ISSUE THREAD

**Issue by brentr** [ebruck/radiotray-ng#76]
I see a custom command in the CMakeLists.txt
It does not seem to be invoked automatically.
The package builds if I simply copy the *.in to .hpp
But, I'm sure that wasn't your intent...

``
$ make package
[  4%] Built target appindicator_gui
[  9%] Built target config
[ 12%] Building CXX object src/radiotray-ng/playlist/CMakeFiles/playlist.dir/playlist_downloader.cpp.o
/home/brent/git/radiotray-ng/src/radiotray-ng/playlist/playlist_downloader.cpp:21:31: fatal error: rtng_user_agent.hpp: No such file or directory
 #include <rtng_user_agent.hpp>
                               ^
compilation terminated.
src/radiotray-ng/playlist/CMakeFiles/playlist.dir/build.make:158: recipe for target 'src/radiotray-ng/playlist/CMakeFiles/playlist.dir/playlist_downloader.cpp.o' failed
make[2]: *** [src/radiotray-ng/playlist/CMakeFiles/playlist.dir/playlist_downloader.cpp.o] Error 1
CMakeFiles/Makefile2:253: recipe for target 'src/radiotray-ng/playlist/CMakeFiles/playlist.dir/all' failed
make[1]: *** [src/radiotray-ng/playlist/CMakeFiles/playlist.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
``

**Comment by ebruck** [comment]
I'm not sure why you are having so many problems. All targets depend on the user-agent "target".
What do you see when you run this?

> make user-agent

It would be helpful if you could paste the output from cmake when you point it to the root of the repo.

**Comment by brentr** [comment]
make user-agent works after I run:

$  rm -rf *
$  git reset --hard

Oddly, git clean -f was not sufficient to reset the state of the build in this case.

Could you revise the readme.md to refer to the top directory of the repo rather than to the "source" directory.  There is a directory called src which is obviously where the radiotray-ng source lives.  Thanks!

Everything builds fine now.
Here's the output you requested.  Looks good, I think...

```
$ cmake . -DCMAKE_BUILD_TYPE=Release
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CURL: /usr/lib/i386-linux-gnu/libcurl.so (found version "7.52.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   log
--   program_options
--   thread
--   date_time
--   log_setup
--   chrono
--   atomic
-- Found wxWidgets: -L/usr/lib/i386-linux-gnu;-pthread;;;-lwx_gtk2u_core-3.0;-lwx_baseu-3.0;-lwx_gtk2u_adv-3.0 (found version "3.0.2") 
-- Checking for one of the modules 'jsoncpp'
-- Checking for one of the modules 'gstreamer-1.0'
-- Checking for one of the modules 'libxdg-basedir'
-- Checking for one of the modules 'libbsd'
-- Checking for one of the modules 'appindicator3-0.1'
-- Checking for one of the modules 'libnotify'
-- Checking for one of the modules 'glibmm-2.4'
-- Checking for one of the modules 'giomm-2.4'
Building version: 0.2.3...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/brent/git/radiotray-ng

```

**Comment by ebruck** [comment]
@brentr I'll fix the readme. It does seem a bit confusing.
thx!
