### ISSUE TITLE
Debian package does not install in "Stretch"

### ISSUE THREAD

**Issue by brentr** [ebruck/radiotray-ng#77]
On "master" branch, generated DEB package with

$  make package

but the resulting package fails to install:

```
# gdebi radiotray-ng_0.2.3_i386.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libcurl4

```

It seems that libcurl4*dev packages ultimately depend on the libcurl3 package.
Nutty, but there it is.

Changed libcurl4 ==> libcurl3 in CPackConfig.cmake:

`SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6, libbsd0, libcurl3, libjsoncpp1, libxdg-basedir1, libnotify4, python2.7, python-lxml, libglibmm-2.4-1v5, libboost-filesystem1.62.0, libboost-system1.62.0, libboost-log1.62.0, libboost-thread1.62.0, libboost-program-options1.62.0, libgstreamer1.0-0, libappindicator3-1, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, libwxgtk3.0-0v5")
`

Now it installs.
Seems to run fine.

**Comment by ebruck** [comment]
My package targets the latest Ubuntu (18.04) release. For 16.04 I have to modify the Debian package before each release and change it to version 3. This is one of the reason why I'm thinking of abandoning packaging and let each distro if they choose do it for their users.

More info:

https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294

I do not plan to support anything other than Ubuntu right now so I am going to close this issue.
