### ISSUE TITLE
Jazz > Smooth Jazz and both Latin channels doesn't play

### ISSUE THREAD

**Issue by baimafeima** [ebruck/radiotray-ng#78]
Clicking on Jazz > Smooth Jazz leads to: `error: failed to download playlist`
Both latin channels also don't work.

**Comment by ebruck** [comment]
What version are you using? 
It should of been fixed in v0.2.3 with https://github.com/ebruck/radiotray-ng/commit/eab37323bdbbd1d15ef60d88fe961697ccb1b132

**Comment by ebruck** [comment]
This was fixed in v0.2.4. Please ask the packager to update the Solus version.
