### ISSUE TITLE
Icon inconsistency/invisibility in Budgie menu

### ISSUE THREAD

**Issue by baimafeima** [ebruck/radiotray-ng#79]
I use [Solus](https://getsol.us/home/) Budgie as it has `radiotray-ng `in its repositories. Unfortunately, when launching the application from Budgie menu, the icons are invisible and when using the mouse cursor on the empty space where the icon usually is, then the - I assume - previous icon ("transmitting station icon") appears in almost invisible white. This icon is different from the icon ("the radiobox icon") which is visible in the tray icon. I really prefer the latter one in the tray/panel but not the one in the menu. Can this be fixed? This also appears to be specific to `radiotray-ng` as none of the other applications show this kind of behavior so I think it's safe to assume that this is not a Budgie menu issue.

**Comment by ebruck** [comment]
It's hard to come up with a set of icons that will work for every distro's default theme.  Have a look at the readme as it shows how you can override the icons being used. I'm happy to accept a pull request that installs icons for Solus' default theme. I will only accept colour variations though.

One change that is coming is a new notification image that has a thin broder around the "tower". https://github.com/ebruck/radiotray-ng/commit/9f85c47c2d75adbee09ccd2a81f241db53f894ca  It's not perfect but at least you can see it on a white background notification window. Ubuntu is my only target as far as themes are concerned. Sorry.

**Comment by ebruck** [comment]
@baimafeima can you try this as sudo?

`gtk-update-icon-cache -f -t -q /usr/share/icons/hicolor/`

If this fixes the invisible icon issue then there's an eopkg problem.

**Comment by ebruck** [comment]
I installed Solus-3.9999-Budgie and other than being a version behind, it seems to work just fine. It's showing up with a different icon, but that appears from the Papirus theme.

![image](https://user-images.githubusercontent.com/1168556/46922043-ef90a900-cfb7-11e8-8b53-fcb92e1a5585.png)

**Comment by ebruck** [comment]
I'm closing this as it seems to work fine and overrides such as:

```
{
...
   "radiotray-ng-off" : "/usr/share/icons/hicolor/256x256/apps/radiotray-ng-off.png",
   "radiotray-ng-on" : "/usr/share/icons/hicolor/256x256/apps/radiotray-ng-on.png",
...
}
```
are working as expected.

**Comment by ebruck** [comment]
I should add that the menu icon is different because the Papirus them is incomplete. It just replaces the on/off icons and not the notification one.
