### ISSUE TITLE
self-compiled deb when try to install procudes error: radiotray-ng depends on libcurl4

### ISSUE THREAD

**Issue by igor2x** [ebruck/radiotray-ng#80]
I am using Ubuntu 16.04 **32-bit** on old laptop.

I installed radiotray-ng_0.2.1_ubuntu_16.04_i386.deb few months ago from official download and it was working fine without any issue at all.

But today I noticed new version 0.2.3 is available, but unfortunately 32-bit deb package is not available to download.

I tried to compile it myself following the instructions on official site:
```
git clone https://github.com/ebruck/radiotray-ng.git
cd radiotray-ng
mkdir build
cd build/
cmake .. -DCMAKE_BUILD_TYPE=Release
make package
sudo dpkg -i ./radiotray-ng_0.2.3_i386.deb 
sudo apt-get install -f
```
One before last command `sudo dpkg -i ./radiotray-ng_0.2.3_i386.deb` returns:
> (Reading database ... 260050 files and directories currently installed.)
> Preparing to unpack radiotray-ng_0.2.3_i386.deb ...
> Unpacking radiotray-ng (0.2.3) over (0.2.3) ...
> dpkg: dependency problems prevent configuration of radiotray-ng:
>  radiotray-ng depends on libcurl4; however:
>   Package libcurl4 is not installed.
> 
> dpkg: error processing package radiotray-ng (--install):
>  dependency problems - leaving unconfigured
> Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
> Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
> Processing triggers for mime-support (3.59ubuntu1) ...
> Processing triggers for hicolor-icon-theme (0.15-0ubuntu1.1) ...
> Errors were encountered while processing:
>  radiotray-ng
> 

and the last command `sudo apt-get install -f` just deletes radiotray-ng:
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Correcting dependencies... Done
> The following packages will be REMOVED:
>   radiotray-ng
> 0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
> 1 not fully installed or removed.
> After this operation, 1157 kB disk space will be freed.
> Do you want to continue? [Y/n] y
> (Reading database ... 260049 files and directories currently installed.)
> Removing radiotray-ng (0.2.3) ...
> Processing triggers for hicolor-icon-theme (0.15-0ubuntu1.1) ...
> Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
> Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
> Processing triggers for mime-support (3.59ubuntu1) ...

I have checked the obvious ` sudo apt install libcurl4-openssl-dev` but lib is already installed:
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> libcurl4-openssl-dev is already the newest version (7.47.0-1ubuntu2.9).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I did another test. From build directory I have run `./radiotray-ng` it outputs error:

> (radiotray-ng:30390): Gtk-WARNING **: Error loading icon from file '/usr/share/radiotray-ng/radiotray-ng.png':  Failed to open file '/usr/share/radiotray-ng/radiotray-ng.png': No such file or directory

Program can't find the icon, so I get missing icon in my tray, but everything else (also radio plays without problem) seems to work fine. From program's About menu selection it is displayed:
> Radiotray-NG
> v0.2.3

Any idea why radiotray-ng_0.2.3_i386.deb package can't be installed. Which dependency is really missing? Like I understand the purpose of deb package is to have dependencies list stored in deb file and before installing program itself it should offer to install dependencies first.

Any help is appreciated.

**Comment by ebruck** [comment]
This is an issue that has been a pain for a while now and the reason I will no longer create binary releases. 

You can read the details here (https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294), Just change lbcurl4 to libcurl3 in `debian/CMakeLists.txt` and it should work fine.  I can change the build code to do that for you automatically next release.

The alternative is to unpack the deb file and fixup the dependencies then repack, which I used to do for each release.

**Comment by igor2x** [comment]
Thanks, your solution works excellent.

Just for reference, I did:
1. Downloaded official 0.2.3 version from:
https://github.com/ebruck/radiotray-ng/archive/v0.2.3.zip
2. Unzipped the file
3. Copied text from https://raw.githubusercontent.com/ebruck/radiotray-ng/af37cd65e251d66631f70f905b3ca3eaa17e8580/debian/CMakeLists.txt
and saved it into file CMakeLists.txt
4. Replace file debian/CmakeLists.txt with file from step 3.
5. Executed commands:
```
cd radiotray-ng
mkdir build
cd build/
cmake .. -DCMAKE_BUILD_TYPE=Release
make package
sudo dpkg -i radiotray-ng_0.2.3_i386.deb
```
6. Searched radiotray-ng from Ubuntu Dash and started the program. Icon appears in tray. About option displays version "v0.2.3". Tested and everything works as expected.

Thanks a lot for help. You can close down this bug report as problem solved.

**Comment by ebruck** [comment]
Thanks for verifying my fix.
