### ISSUE TITLE
Add more icons in tray to indicate the volume level, buffering, radio on/off

### ISSUE THREAD

**Issue by igor2x** [ebruck/radiotray-ng#85]
Hi,
this is enhancement request.

I really like radiotray-ng program. I like to use program without notifications, to not disturb me on my daily work. I may lose some info because of this like buffering new radio station and similar.

If I compare wifi and sound icons I see there are many icons to indicate strength of wifi and volume of the sound. But radiotray-ng has only two icons "radio is on" (white icon) and "radio is off" (grey icon).

May I suggest to add more icons to indicate the radiotray-ng's sound level and also to indicate radio is on and off state and also buffering new sound (during buffering process icons are exchanging like when wifi is searched)

Please see bellow picture for my suggestion. I hope you like the idea.
Regards

![icons_suggestion](https://user-images.githubusercontent.com/10895030/47109295-2aac0a00-d24e-11e8-8dac-897c3487d198.png)

**Comment by ebruck** [comment]
I'm not sure how useful this sort of info is since the icon is so small. I can also see a bunch of tickets being filed, because someone's theme isn't complete and the icon is flashing between stock and theme images all the time.

As for volume level I certainly can add an option to enable text like this next to the icon:

![screenshot from 2018-10-17 12-37-57](https://user-images.githubusercontent.com/1168556/47111951-cb2c0b00-d209-11e8-8e9f-81150605792f.png)

**Comment by igor2x** [comment]
I know icon is small, but the wifi and sound icons are also small. In my humble opinion it would be nice if sound indication is implemented as I suggested.

I actually don't know how many uses are using volume inside radiotray-ng, maybe users more use system sound. If this is true, then it is actually waste of your time to implement such a feature.

I actually don't like icons that are having additional percentage. They consume too much space and are sometimes confusing for which icons percentage is suppose to indicate.

If you think my idea is not so good, no harsh feelings. Not a problem, I was just pointing out an idea, you are the project leader and you should decide what is the best for the program.

**Comment by ebruck** [comment]
Sorry I don't plan to do this. I'd have to take away theming to ensure the feature works consistently.
