### ISSUE TITLE
Add Chinese channel

### ISSUE THREAD

**Issue by baimafeima** [ebruck/radiotray-ng#88]
It would be great to add a new _Chinese_ channel to allow listening to Chinese classical and contemporary music. If you think mixing C-Pop and Chinese Classical is not such a good idea, it would also make sense to add the Chinese classical station to the _Classical_ channel. Both are fairly different and I would group them together. My station recommendations for a new _Chinese_ channel would be: 
- CCM (Chinese Classical Music): https://chinesemusicworld.com/radio/ and http://radio2.chinesemusicworld.com/index.html
- Douban.FM: https://douban.fm/
- Mandarin Radio: https://www.mandarinradio.com/
- YES 933: https://radio.toggle.sg/en/yes-933-fm and https://www.radioguide.fm/internet-radio-singapore/yes-933fm
- Love 972: https://www.meradio.sg/radio/love-972

**Comment by Swipe650** [comment]
You can add all these channels yourself via the bookmark editor

**Comment by baimafeima** [comment]
I think it would be great to have a new channel which is pre-configured and working out-of-the-box. Otherwise everything has to be manually set up each time on every new machine. Having a Chinese channel would allow my Chinese friends to use radiotray-ng and I believe make this application much more popular.

**Comment by Swipe650** [comment]
Only needs to be done once. Just copy your bookmarks config to your other machines and upload it to github and share with your friends.

**Comment by ebruck** [comment]
@baimafeima do you have the URL for the live streams?

**Comment by ebruck** [comment]
@baimafeima any luck?
