### ISSUE TITLE
"Currently Playing" No Longer Updates 

### ISSUE THREAD

**Issue by vtpoet** [ebruck/radiotray-ng#89]
On both my systems, Mint and KDE, Radio Tray is no longer updating the "Currently Playing"  play list. Currently, it continues to list the music that was playing when I first connected. If I stop and restart Radio Tray, the playlist updates to the current title, but still won't update after that.

**Comment by ebruck** [comment]
Works fine for me on Mint 19 MATE.

**Comment by vtpoet** [comment]
//What version of Mint? Which KDE distro? What version of radiotray-ng?//

Apologies, should have included all that.

System:    Host: vtpoet-Lenovo-Yoga-2-11 Kernel: 4.18.0-041800-generic x86_64 bits: 64 Desktop: Cinnamon 3.8.9 Distro: Linux Mint 19 Tara

radiotray-ng:
  Installed: 0.2.3
  Candidate: 0.2.3
  Version table:
 *** 0.2.3 100
        100 /var/lib/dpkg/status

KDE will be forthcoming soon as I'm on that machine....

**Comment by ebruck** [comment]
Can you try upgrading to 0.2.4?

**Comment by ebruck** [comment]
I've tried Cinnamon Linux Mint 19 and it's working fine with v0.2.4.
Could you please list exactly the steps you use to reproduce your issue?

**Comment by ebruck** [comment]
Tested on KDE Neon with no problems other than know AppIndicator quirks we previously addressed in #68.
