### ISSUE TITLE
Current blockers to make radiotray-ng available in Solus

### ISSUE THREAD

**Issue by baimafeima** [ebruck/radiotray-ng#9]
I have suggested radiotray-ng to be included in the software repositories of Solus: https://dev.solus-project.com/T2649

Could you address the issues mentioned by the Solus devs in an upcoming version? Many thanks. 

Josh Strobl from the Solus team wrote: 

> So I have this compiled, however here are the issues:
> 
> - It doesn't create any of the configuration files, nor does it ship any default ones, which means unless the end-user knows that they'll need to manually configure it, it will fail in the least obvious way, which is coredump.
> - Even if radiotray-ng did ship defaults, it isn't checking its own data directory, only the user's .config/radiotray-ng, which means there is really no way for us to get this to work OOTB (and thus validate) without severely patching it. Thus rejecting under our Stack Complexity rule.
>

**Comment by ebruck** [comment]
Thanks for the report! 

Radiotray-NG does include all of the files it needs, but it seems on some systems a different exception is thrown when trying to load a config that isn't there. I've found the problem and will address it in the next release which I am planning on doing after Ubuntu 17.04 is released. 

Here's a quick test if you want to see if radiotray-ng works for you:

diff --git a/src/radiotray-ng/config/config.cpp b/src/radiotray-ng/config/config.cpp
index 1e630b4..a907ec3 100644
--- a/src/radiotray-ng/config/config.cpp
+++ b/src/radiotray-ng/config/config.cpp
@@ -69,7 +69,7 @@ bool Config::load()
                        return false;
                }
        }
-       catch(std::ios_base::failure& /*e*/)
+       catch(...) // std::ios_base::failure& /*e*/)
        {
                LOG(error) << "Failed to load: " << this->config_file << " : "<< strerror(errno);
                return false;

**Comment by baimafeima** [comment]
Thanks for your quick response. Once your next release lands, I'll suggest radiotray-ng to be reevaluated on the Solus dev tracker.

**Comment by ebruck** [comment]
More info: https://gcc.gnu.org/ml/gcc-help/2016-10/msg00100.html

**Comment by baimafeima** [comment]
Just want to inform you that it is now included in the Solus repository: https://dev.solus-project.com/source/radiotray-ng/
