### ISSUE TITLE
cmake complaining on missing "appindicator3-0.1" on debian testing

### ISSUE THREAD

**Issue by fieserWolF** [ebruck/radiotray-ng#93]
when trying to build radiotray-ng, cmake complains:

-- Checking for one of the modules 'appindicator3-0.1'
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:679 (message):
  None of the required 'appindicator3-0.1' found
Call Stack (most recent call first):
  CMakeLists.txt:57 (pkg_search_module)

I have installed everything available  on debian, nothing works:
libappindicator3-1
libappindicator3-0.1-cil
libappindicator3-0.1-cil-dev
gir1.2-appindicator3-0.1
libappindicator3-dev

only thing that worked out: commenting out the check in "CMakeLists.txt" (line 55):

```
# notification & ncurses based on platform
if (CMAKE_SYSTEM_NAME MATCHES "Linux")
#    pkg_search_module(APPINDICATOR REQUIRED appindicator3-0.1)
#if (NOT APPINDICATOR_FOUND)
    pkg_search_module(NCURSES      REQUIRED ncurses)
#endif()
```

compiling works then, but of course only compiles the ncurses gui.

**Comment by ebruck** [comment]
What version of Debian are you using? Just tried Debian 9.6 with no problems building except for having to hack the required cmake version.

**Comment by ebruck** [comment]
I had installed libappindicator3-dev in Debian testing and there was no pkg-config entry.
I next tried apt-get install indicator* which finally added it. Not sure what packages I installed exactly to get that. Since this is testing I would not spend much time assuming it works 100% so I'm closing this ticket.

**Comment by killerhippy** [comment]
libindicator3-dev soved my case.
