### ISSUE TITLE
Server does not support seeking

### ISSUE THREAD

**Issue by igor2x** [ebruck/radiotray-ng#97]
Hi,
I have self-compiled Radiotray-NG few weeks ago and installed it on Ubuntu 16.04 desktop **32-bit**. In About menu option there is info: v0.2.4.

I am using program for many years and time to time I get the error "Server does not support seeking". This error is displayed on operating system notification. When this happens music stops playing and Radiotray-NG icon changes from white to grey indicating musing stopped. In the first option menu there is always "Turn on _radio_station_", so music has stopped. Clicking on this option music always starts playing.

I just don't know what is the cause of this problem, but it happens quite often like at least once per e.g. two hours.

Is it possible to set somehow in this problem appears that Radiotray-NG is automatically turned on again. The best would be without operating system notification.
Regards

**Comment by ebruck** [comment]
This is an odd error gstreamer is giving when there's an issue playing a station. I've seen this myself as well when a station halts sending packets. Give v0.2.5-dev a try as there has been some minor changes that "should" make radiotray-ng restart the stream.

**Comment by ebruck** [comment]
Some info I found: http://gstreamer-devel.966125.n4.nabble.com/Souphttpsrc-error-Server-does-not-support-seeking-td4239793.html

**Comment by igor2x** [comment]
I have now compiled and installed as suggested and from About menu entry I see: v0.2.5-dev.

Like few minutes after starting Radiotray-nG I have heart music stop, Radiotray-NG icon was still white, no operating system notification (I like this) and then automatically music continue to play after 3 seconds. I don't know if this was this bug solution, just pointing out.

I can't see anything special logged in $HOME/.config/radiotray-ng/log/radiotray-ng-<largest_number>.log

Should there be anything special in logs? It would be nice if some flag or something is logged, so we know the code to work-around this problem was triggered. What do you think? I am willing to recompile if you add some info to the logs.

**Comment by ebruck** [comment]
You have to turn on debug logging.
This bug (#95) prevented radiotray-ng from returning to a "playing" state.

**Comment by igor2x** [comment]
Hi,
two days ago in $HOME/.config/radiotray-ng/radiotray-ng.json I have added `"debug-logging" : true`
and today suddenly the same problem appeared like in first post.

See attachment for debug log.
[radiotray-ng-00005.log](https://github.com/ebruck/radiotray-ng/files/2730493/radiotray-ng-00005.log)

Can you please reopen a bug report.
Regards

**Comment by igor2x** [comment]
Hi,
just in case if something new jumped into development branch I have re-compiled it. Deleted log files and started the app. After half an hour the same problem appears.

See log file: 
[radiotray-ng-00000.log](https://github.com/ebruck/radiotray-ng/files/2730559/radiotray-ng-00000.log)

Regards

**Comment by ebruck** [comment]
@igor2x try pulling v0.2.5-dev again.

**Comment by ebruck** [comment]
I can't reproduce this on 18.10 using:

```
$ gst-launch-1.0 --version
gst-launch-1.0 version 1.14.4
GStreamer 1.14.4
https://launchpad.net/distros/ubuntu/+source/gstreamer1.0
```

**Comment by ebruck** [comment]
It seems there are "several" redirects (verified in wireshark) occurring that gstreamer for you is not handling: 

> 2019-01-06 14:11:42.919614] [0xb504a900] [error] (player.cpp:204) - debugging information: gstsouphttpsrc.c(1294): gst_soup_http_src_got_headers_cb (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
> Server does not accept Range HTTP header, URL: http://listenwmp.cinemix.fr, **Redirect to: http://94.23.51.96:8001/**

For me it seems the latest gstreamer is handling it.

I'm not sure what else I can do here. Try changing the url for this station to http://94.23.51.96:8001/ or use:  http://yp.shoutcast.com/sbin/tunein-station.pls?id=1263172

**Comment by igor2x** [comment]
Just a humble idea, no pressure at all, as I see Ubuntu 18.10 (your install) and Ubuntu 16.04 are not using the same GStreamer version. Now we are getting into the different distribution default libraries hell. I know you are busy, but in order to eliminate problems of this type we should probably consider to create cross-distribitions binary package with one of them: Snap, Flatpack or AppImage. In this case all of the distributions and all sub-distribution versions would use exactly the same combination of "Radiotray-NG binary + libraries" and all kind of problems would probably be reduced multiple times.

**Comment by igor2x** [comment]
Problem appeared. See log file:
[radiotray-ng-00000.log](https://github.com/ebruck/radiotray-ng/files/2733475/radiotray-ng-00000.log)

**Comment by ebruck** [comment]
Have you tried the other URLs I mentioned?

 http://94.23.51.96:8001/ or: http://yp.shoutcast.com/sbin/tunein-station.pls?id=1263172

**Comment by igor2x** [comment]
I have overlooked your suggestion. Today I have changed to IP address and listened music for one hour and then changed to domain name and listened to one hour and problem did not appear. This may be a solution or problem just hasn't happened yet.

**Comment by igor2x** [comment]
Unfortunately problem reappeared when using domain name.
[radiotray-ng-00002.log](https://github.com/ebruck/radiotray-ng/files/2737653/radiotray-ng-00002.log)

**Comment by igor2x** [comment]
And few minutes after setting it to IP address the same problem.
[radiotray-ng-00000.log](https://github.com/ebruck/radiotray-ng/files/2737680/radiotray-ng-00000.log)

**Comment by ebruck** [comment]
This issue is the same and there's a patch I can try.
https://github.com/clementine-player/Clementine/issues/5116

**Comment by ebruck** [comment]
@igor2x please pull down latest seek-test branch. It "should" recover if the stream is dropped.

**Comment by ebruck** [comment]
@igor2x any updates?

**Comment by igor2x** [comment]
I have pulled down seek-tests branch 2 days ago and since no "seeking" error appeared.

I see plenty of GST_STATE_PAUSED and GST_STATE_PLAYING, but since I have no trouble with program,
I don't care about this messages.

Maybe you can close down this bug report and if problem reappeared I will add comment to it.
Thank you for taking time to help me out with this problem. I really enjoy this tool. Thanks.

**Comment by igor2x** [comment]
Now first time since 2 days music stopped playing, but it started continue playing after 3 seconds. This happened two times in a role 3 minutes apart. In error log there is logged "restarting stream". Is this it?
If yes, then this problem is fixed with work-around.

See log: 
[radiotray-ng-00001.log](https://github.com/ebruck/radiotray-ng/files/2750084/radiotray-ng-00001.log)

**Comment by ebruck** [comment]
Buffering stalled so the timer fired and the stream was restarted.

**Comment by ebruck** [comment]
Any seek messages in the logs? I'm interested in learning if my change allows playing to recover if a redirect is sent and gstreamer tries to do a seek.

**Comment by igor2x** [comment]
There are plenty of seek errors, but I haven't noticed radiotray-ng program to stop and stayed in stopped state. I have now few days let program to run for hours. I lot of time I haven't listened to the music at all, but when coming back music was playing. The original problem when seek error appeared radiotray-ng was stopped and stayed in stopped state.

I have compressed the log files. See attachment. Do the following:
1. Download file and create a directory where you will extract files.
2. Extract file: `tar xf RadioLogs.tar.gz`
3. Search for seek error: `grep "seek" *.log`

[RadioLogs.tar.gz](https://github.com/ebruck/radiotray-ng/files/2767359/RadioLogs.tar.gz)

**Comment by ebruck** [comment]
@igor2x thanks
