### ISSUE TITLE
[opensuse Leap 15.0 / KDE] Icons barely visible

### ISSUE THREAD

**Issue by macplaxton** [ebruck/radiotray-ng#98]
After a long break of using radiotray / radiotray-ng, I spent a few hours methodically working through a manual compilation of the 0.2.4 source.

The icon appears in the tray and on the pop-up notifications, but is barely visible against the stock system colours.

If I fix the colours, could an additional set be included in the source so those building for opensuse can see them?

**Comment by ebruck** [comment]
I've noticed that when trying KDE myself recently. A theme specific icon for Breeze would be nice. Please ensure dark mode is also supported. You may be able to reuse the old Unity icons under data/ubuntu-mono-light & data/ubuntu-mono-dark.

**Comment by macplaxton** [comment]
Thanks, I will look into that later.

**Comment by macplaxton** [comment]
I've done some recolouring of the icons and have them sort of working. I've still to sort the playing icon.

Given the frequent buffering in issue #99 what I have thought about is perhaps a change in the way buffering is notified. Should an instance of buffering occur, instead of triggering a pop-up dialogue box appearing in the bottom corner of the screen, could the "radio waves" of the icon not change to semi-red? Conversely if the app is playing, could the waves not be solid green?

Something like this for playing:

![radiotray-ng-on](https://user-images.githubusercontent.com/8209325/51068308-4425dd80-1614-11e9-9dea-f8f0dc279aa1.png)

and something this for buffering:

![radiotray-ng-buffering](https://user-images.githubusercontent.com/8209325/51068351-b5fe2700-1614-11e9-9bd1-757b626d763f.png)

and this for stopped:
![radiotray-ng-off](https://user-images.githubusercontent.com/8209325/51068327-67e92380-1614-11e9-9fb9-891a2450278e.png)

If this idea has legs, I can fix some icons sets up.

**Comment by ebruck** [comment]
This has been suggested in the past (#85) and I've decided the icons are much too small to show any meaning full info. 

I can also see the tickets coming in asking for different colours, which is why I like simple dark/light icons and let theme creators use whatever they want.

**Comment by macplaxton** [comment]
I can agree with the second point, although I wouldn't say they were too small to show some status changes, even if it was to differentiate better between just on and off.

I had a bit of trouble with the radiotray-ng-on icon, but I've found the procedure to flush the cache that stores that one (had no trouble with the rest oddly enough) and will test a bit more before submitting a KDE Breeze set.

**Comment by ebruck** [comment]
@macplaxton any progress?

**Comment by macplaxton** [comment]
Not yet. Progress has stalled due to other things.

I had a play around with the Breeze / OpenSUSE Breeze variants in both light and dark. What I need to do is make a suitable pair of icons, but as svg, not png. I had something of a svg code working, but need to read up on it more to fill some gaps in my knowledge.
